### ISSUE TITLE
Grundlegende Felder festlegen

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/fau-person#1]
[Felder werden erst später eingebaut]
- Personendaten:
  -- Person => Checkbox
  Titel (Präfix) => Text
  Abschluss (Suffix) => Text
  Vorname => Text, synchronisierbar
  Nachname => Text, synchronisierbar
  -- Funktionseintrag => Checkbox
  Name => Text
- Zugehörigkeit:
  Institution/Abteilung => Text
  Position/Funktion (evtl. nur über Kategorien managen) => Text
- Kontaktinformationen:
  Straße und Hausnummer => Text
  PLZ => Text
  Stadt => Text
  Land => Text
  Raum => Text
  Telefon => Text [aufgeteilt in Länderkennung, Vorwahl, Telefonnr., Durchwahl]
  Telefax => Text [siehe Telefon]
  [evtl. später mit Postanschrift / private Anschrift / Besuchsadresse ergänzen]
- Social Media:
  E-Mail => Text
  Webseite => Text
  [Blog-URL]
  [Facebook]
  [Twitter]
  [RSS]
- Weitere Informationen:
  Freitext => Textarea
  [Sprechzeiten]
  [Publikationen]
- [Synchronisierung mit externen Daten (jeweils Auswahl einzelner Felder möglich, bei jeder Person extra einstellbar):]
  Import aus UnivIS - mit Checkbox und Möglichkeit, Personen-ID anzugeben (dafür muss irgendwo eine Suche nach der Personen-ID anhand des Namens liegen)
  Import aus IdM - mit Checkbox
  Import aus CRIS - mit Checkbox

**Comment by endv02** [comment]
Fehlt noch ein ausführlicheres Feld für die Single-Darstellung -> hier das Content-Feld verwenden

**Comment by cibsell** [comment]
Es fehlen als Felder:

Arbeitskreis-URL
Forschungsschwerpunkte
Upload-Möglichkeit für Portraitfoto

**Comment by endv02** [comment]
Upload-Möglichkeit für Portraitfoto: aktuell soll das Beitragsbild für diesen Zweck genutzt werden.

**Comment by endv02** [comment]
Forschungsschwerpunkte und CV sind im allgemeinen Eingabefeld eingebbar
Arbeitskreis-URL wird mit Umstrukturierung in Version 2 hinfällig, da dort der Arbeitskreis separat von der Person eingegeben werden kann
