### ISSUE TITLE
Kontakt-IDs für Redakteure

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#100]
Die Kontakt-IDs werden ja im Backend angezeigt - leider aber nur für Admins. Wenn Redakteure einen Kontakt mit [person id="123"] einpflegen möchten, haben sie keine Möglichkeit, die ID herauszufinden. Kann man das den Redakteuren im Backend ebenfalls anzeigen?
![bildschirmfoto 2015-08-18 um 16 32 58](https://cloud.githubusercontent.com/assets/11296947/9333954/882c712c-45cc-11e5-9ccf-286576f0154e.png)

**Comment by endv02** [comment]
Verstehe ich nicht, bei mir als Redakteur sehe ich die Box genauso wie als Admin? Hast Du schon mal geschaut, ob die evtl. über die Options-Lasche ausgeblendet ist?

**Comment by AstridSemm** [comment]
Habe ich jetzt nicht nachgesehen, das trat in der MedFak auf. Wir haben ihnen letzte Woche bei der Besprechung gesagt, sie möchten das nachschauen. Ich warte auf Rückmeldung, denke aber, dass es das war.

**Comment by endv02** [comment]
konnte nicht mehr nachvollzogen werden.
