### ISSUE TITLE
Telefondaten aus UnivIS vereinheitlichen

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/fau-person#101]
Die Telefondaten aus UnivIS sollen in eine einheitliche Form gebracht werden, wenn sie falsch oder unvollständig geliefert werden (nur Durchwahlen oder falsch formatiert)

**Comment by cibsell** [comment]
Gibt es dafür schon eine Lösung?

**Comment by steffigebel** [comment]
Nein, da sind die UnivIS-Beauftragten selbst verantwortlich. Mehr Daten als über die Schnittstelle kriegen wir nicht, bzw können die in dem Schritt nicht formatieren oder erkennen. Müsste per Hand gemacht oder man pflegt seine Daten selbst im CMS.

Grüße, Steffi
--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: cibsell <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/fau-person <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Mittwoch, 11. November 2015 16:26
An: RRZE-Webteam/fau-person <fau-person@noreply.github.com<mailto:fau-person@noreply.github.com>>
Betreff: Re: [fau-person] Telefondaten aus UnivIS vereinheitlichen (#101)


Gibt es dafür schon eine Lösung?

**Comment by cibsell** [comment]
Könnte man ein Häkchen im Formular einbauen, über das man steuern kann, dass die Telefondaten (oder z. B. individuell andere Daten wie Raumnummern) überschrieben werden sollen, wenn im Feld Text steht?

**Comment by steffigebel** [comment]
Muss Frau Kimpan beantworten. Mein Stand ist: entweder via UnivIS syncen oder manuell pflegen pro Kontakt.

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: cibsell <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/fau-person <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Mittwoch, 11. November 2015 16:37
An: RRZE-Webteam/fau-person <fau-person@noreply.github.com<mailto:fau-person@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>
Betreff: Re: [fau-person] Telefondaten aus UnivIS vereinheitlichen (#101)


Könnte man ein Häkchen im Formular einbauen, über das man steuern kann, dass die Telefondaten (oder z. B. individuell andere Daten wie Raumnummern) überschrieben werden sollen, wenn im Feld Text steht?

**Comment by xwolfde** [comment]
Ne Steffi, das ist schon genau so gedacht, daß wir die Daten aus UnivIS "korrigieren".
Wenn dort jemand bspw "091 318 528 - 326"  schreibt, soll dies erkannt werden und bei der Darstellung in die gewünschte DIN-Form gewandelt werden.  Hier "+49 (0)9131 85-28326 "

Auch bei Eingaben der nur im Uninetz verwendbaren Form 06...  für Nürnberg soll es entsprechend erkannt und umgewandelt werden, damit es auch externe Leute nutzen können.

An der Stelle nehmen wir uns die Freiheit heraus, die Vereinheitlichung zu forcieren. Schließlich ist eigentlich die Form schon festgelegt wurden (siehe fau.de). Nur ist das Problem mit den UnivIS-Beauftragten da, dass diese häufig nicht geschult werden und dann frei Schnauze Dinge eingeben. Dies konnte trotz aller Appelle der vergangenen Jahre nicht behoben werden.
Allenfalls eine Option könnte eingebaut werden, daß man die internationale Vorwahl weglässt.

**Comment by xwolfde** [comment]
(Verflixt, ich könnte schwören, wir hatten die diesbezügliche Diskussion mit der Webredaktion irgendwo mal notiert).
Was ich aufg die scnelle gefunden hab, ist das uns mit M auf diese Form festgelegt haben, wie alle Telefonnummern aussehen sollen:
	

Uni-Interne Nummern für Erlangen in der internationalen Form: +49 9131 85-22222 
Für Nürnberg in der internationalen Form:  +49 911 5302-555 an, 
Uni-externe Nummern in der internationalen Form +49 9131 1111111.

Also nichts mit Klammer und führender Null, wie oben geschrieben.

**Comment by cibsell** [comment]
Aufgrund der dezentralen Univis-Verwaltung wird sich in Univis keine einheitliche Form durchsetzen. Daher wäre es zu begrüßen, wenn die Telefon- und Faxdaten automatisch beim Import ins CMS korrigiert werden. Denn sonst müssen alle anderen Daten auch im CMS gepflegt werden, was wieder doppelten Aufwand bedeutet, den aber viele nicht betreiben werden.

**Comment by endv02** [comment]
Stimme xwolfde zu, eine Autokorrektur der angezeigten Telefonnummern (egal ob aus UnivIS kommend oder bei der Eingabe) soll noch eingebaut werden.

**Comment by steffigebel** [comment]
Ist da schon was gemacht worden? Mir war so, als ja. @endv02 darüber hatten wir doch letztens mal gesprochen, als der Fall auftrat mit der Biologie, oder? @rvdforst kannst du mir da was dazu sagen auf die Schnelle?

**Comment by endv02** [comment]
Nein, ist noch nichts gemacht, sonst wäre das ja im Issue :-) kommt auch erst mit Version 2.x, in der alten Version mach ich nichts mehr.

Am 04.12.2015 14:00 schrieb Steffi <notifications@github.com>:

Ist da schon was gemacht worden? Mir war so, als ja. @endv02<https://github.com/endv02> darüber hatten wir doch letztens mal gesprochen, als der Fall auftrat mit der Biologie, oder? @rvdforst<https://github.com/rvdforst> kannst du mir da was dazu sagen auf die Schnelle?

**Comment by endv02** [comment]
Ist ab Version 2.0 zumindest grob vereinheitlicht. Sollte Text o.ä. in der Telefonnummer enthalten sein, wird allerdings nichts formatiert. Wie das mit der Fax-Nummer ist bleibt zu überlegen....

**Comment by endv02** [comment]
Ab Version 2.1.2 wirkt sich die Einstellung des Standortes auch auf die Faxnummer aus.

**Comment by xwolfde** [comment]
Da muss wohl nochmal ran.
Also: Egal ob die Telefonnummern manuell reinkommen oder über UnivIS (oder eine andere Quelle), möchte ich, dass wir die dann zwangsweise automatisch in der ANzeige vereinheitlichen, wenn man erkennen kann dass es sich um Uni-Nummern handelt.

Konkret sollen Uni-Nummern grundsätzlich so angezeigt werden:
* FAU-Nummern aus Erlangen: +49 9131 85-22222
* FAU-Nummern aus Nürnberg: +49 911 5302-555 ,
* Alle anderen Nummern (aus Deutschland): +49 9131 1111111.

Die einzige Option, die ich erlauben würde (via Backend-Option  für den Admin) wäre es, anstelle von "+49" die "0" vor der Vorwahl zu setzen.

Ich stelle mir bei der Umsetzung folgende Regeln udn Verfahren vor, die man dann via RegExpes umsetzen muss:

Mit $Eingabe = Wert den wir durch manuelle EIngabe oder über UnivIS oder irgendwann woanders her bekommen.

0. Wenn der String die Form /\+49 [0-9]{3,4} [0-9]{2,4}\-[0-9]+/ hat, ist alles in Ordnung. Tu nichts, breeche die Prüfung ab, zeige $Eingabe so an.

Wenn nicht, dann:
1. Aus der $Eingabe werden alle Zeichen entfernt, die nicht in folgender Menge enthalten sind: [0-9]+
  Also u.a. alle Leerzeichen, Minuszeichen, Klammer und Buchstaben raus.

3. Wenn $Eingabe mit "852" startet, ersetze die "852" durch  "+49 9131 85-2" . Füge dann den Rest ohne Leerzeichen hinzu. Break
4. Wenn $Eingabe mit "06" oder mit "5302" startet, dann ersetze dies durch "+49 911 5302-". Füge dann den Rest ohne Leerzeichen hinzu. Break
5. Wenn $Eingabe kleiner ist als 6 Zeichen, dann

   Wenn $Eingabe kleiner ist als 5 Zeichen, dann füge "+49 9131 85-" vorne an. Break
   
   Ansonsten
   a) Wenn $Eingabe mit einer "2"  oder einer "3" beginnt, füge "+49 9131 85-" vorne an. Break
   b) Wenn $Eingabe mit einer "6" beginnt, entferne die 6 und füge dann "+49 911 5302-" vorne an. Break

     Ansonsten füge "+49 9131 " vorne an. Break

6. Wenn $Eingabe 6 oder mehr Zeichen lang ist

**Comment by endv02** [comment]
Mögliche Ausgaben für interne Telefonnummern:
**Erlangen: **
- 5-stellige Durchwahl (beginnend mit 2, 3, 4 oder 6)
- 06- mit 5-stelliger Durchwahl (klappt auch von Nürnberg nach Erlangen...)
- 49 (0) 9131 85- oder 09131 85- mit 5-stelliger Durchwahl (mit allen möglichen Zeichen drin)
**Nürnberg: **
- 3-stellige Durchwahl
- 06- mit 3-stelliger Durchwahl
- 49 (0) 911 5302- oder 0911 5302- mit 3-stelliger Durchwahl (mit allen möglichen Zeichen drin...)
**Umsetzung:**
Wenn $Eingabe mit +49 9131 85- oder +49 911 5302- beginnt mach nichts; 
sonst wenn $Eingabe mit /\+49 [1-9][0-9]{3,6} [0-9]+/ übereinstimmt mach  nichts;
sonst schmeiße alles bis auf 0-9 aus $Eingabe raus und überprüfe auf Länge:
strlen = 3 ergänze mit Vorwahl Nbg
strlen = 5 ergänze mit Vorwahl Erl
strlen = 7 wenn mit 85 beginnend ergänze mit Vorwahl Erl, wenn mit 5302 beginnend ergänze mit Vorwahl Nbg
strlen = 9 wenn mit 0685 beginnend ergänze mit Vorwahl Erl, wenn mit 065302 beginnend ergänze mit Vorwahl Nbg
strlen = 11, 13 oder 14 wenn 9115302 enthalten ergänze mit Vorwahl Nbg
strlen = 12, 14 oder 15 wenn 913185 enthalten ergänze mit Vorwahl Erl 
Alles andere wird ignoriert und mit Admin-Notice an den Anwender übergeben, weil damit zu viele Sonderfälle verbunden sind die eine falsche Nummer ausgeben würden. Also keine allgemeine Umsetzung möglich.
Realisiert ab Version 2.1.4

**Comment by endv02** [comment]
Ausnahme: wenn die Daten nicht aus UnivIS kommen, sondern direkt im Formular eingegeben werden, soll beim default-Fall eine Admin-Notice an den Anwender erfolgen oder ein JavaScript-Hinweis.

**Comment by xwolfde** [comment]
Hm... also bei EZIRE hab iuch gerade so eine Telefonnummer entdeckt:
"09131/85-22239, Sekr. 09131/85-26398"
https://www.ezire.fau.de/dienstleistungen/

**Comment by endv02** [comment]
Jepp. Genau wegen solchen Fällen wird hier nicht radikal alles neu formatiert. Sobald hinter einem beginnenden 09131 85 - mehr oder weniger als 5 Ziffern kommen, wird der Inhalt des Feldes einfach so ausgegeben, weil viele hier mehrere Telefonnummern in UnivIS eingeben da Textfeld, und dann würde hier im blödesten Fall eine falsche Telefonnummer erscheinen. Und leider scheint anschließend keiner mehr die Ausgabe zu kontrollieren, sonst würde die Leute ja auch die Inkonsistenz in der Formatierung stören. Daher lieber eine korrekte Ausgabe und unterschiedliche Darstellungen statt falsche Informationen.

**Comment by xwolfde** [comment]
Gerade entdeckt, daß sich die Pressestelle aus Produzent der FAU-Visitenkarten selbst nicht an die interantionale Syntax hält.
Dort ist die Telefonnummer z.B. so: "09131/85-xxxxx"  (ohne jegliches Leerzeichen).
https://www.fau.de/intranet/fau-repraesentieren/visitenkarten-fuer-uni-angehoerige/

Auch auf der Website der fau.de nutzt die Webredaktion die deutsche Form der Telefonnummern und nicht die interantionale.   Egal. Es mag Gründe geben. Hauptsache, es bleibt bei nur diesen beiden gültigen Syntaxformen und es kommen keine weiteren hinzu.

Vorschlag: Wir machen im Plugin ein Schalter: "Internationale Darstellung von Telefon- und Faxnummern": [Ja/Nein]
Ein Attribut für den Shortcode würde ich aber absolut nicht wollen. Der Schalter sollte global für die gesamte Website gelten.

(Per Default dann "Ja" oder "Nein"? Ich tendiere wegen der größeren Zielgruppenreleveanz zur Nicht-Interantionalen Form)


Relevanz auch hierhin:
https://github.com/RRZE-Webteam/fau-person/issues/73

**Comment by xwolfde** [comment]
Hilfreiches JS für die Eingabevalidierung von Telefonnummern:
https://text-mask.github.io/text-mask/

**Comment by xwolfde** [comment]
Zum neuen Portal für Visitenkarten:
Das neue Portal für Visitenkarten ist offenbar so "flexibel", dass es beliebie Eingabeformen erlaubt.  Bei Default-Eingabe erhält man dort Nummern der Form: "+49 9131/12234". Das einzige Leerzeichen ist tatsächlich nur zwischen 49 und 9131. 
Da man aber ungeprüft Felder leer lassen kann oder Unsinnszeichen reinfügen kann, ist das was bei dem Portal rauskommt willkürlich und abhängig vom Eingeber.

tl;dr: Das FAU Visitenkartenportal bzw dessen Erzeignisse kann keinesfalls als Referenz genommen werden.
