### ISSUE TITLE
Mehr Link Defaultinhalt

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#102]
Im Backend steht , dass wenn der Mehr Link leer ist, daß dann dort der Default (Personenseite) verwendet wird.
Bei der Anzeige im Web funktioniert dies aber nicht. Dort wird der Link als Leer gesehen und daher der "Mehr Link" nicht angezeigt.

**Comment by endv02** [comment]
Korrigiert in Version 1.2.7
