### ISSUE TITLE
ID des Kontakts unter "Kontakt bearbeiten"

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#103]
Es wäre wünschenswert, wenn die ID des Kontakts irgendwo auf der Seite "Kontakt bearbeiten" angezeigt wird.

**Comment by xwolfde** [comment]
Man kann es oben in der URL sehen. Aber du hast recht, das geht auch schöner.
Vorschlag: An geeigneter Stelle wird auf der Bearbeiten-Seite eines Kontakts auch der Shortcode zum Einfügen in Seiten als Beispiel angegeben, so daß man dort dann einfach Copy&Paste machen könnte. 
Das haben wir an anderer Stelle schonmal gemacht.

**Comment by endv02** [comment]
Ist in der nächsten Version im Bereich der Kontexthilfe (= Hilfelasche) drin
