### ISSUE TITLE
HTML-Bug: div in li

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#104]
In shortcodes ganz unten ist die Personendesc als div in einer Liste angegeben. 
Wenn es in der Liste als Listelement ist, muss man ein span nehmen. Ansonsten darf es  erst ausserhalb der Liste (nach dem /ul ) kommen.

                $content .= '<div class="person-info-description">' . $description . '</div>';

Fehler vom Validator:
Element div not allowed as child of element ul in this context. (Suppressing further errors from this subtree.)

From line 220, column 2115; to line 220, column 2151

span></li><div class="person-info-description">Hier i

Contexts in which element div may be used:
    Where flow content is expected.
Content model for element ul:
    Zero or more li and script-supporting elements.

**Comment by endv02** [comment]
In Version 1.2.7 aus Aufzählung rausgenommen
