### ISSUE TITLE
Suffix: Komma fehlt

### ISSUE THREAD

**Issue by j-hofmann** [RRZE-Webteam/fau-person#105]
Hallo,
ich bastele zur Zeit mit Euren wirklich tollen Wordpress-Templates und Plugins für unsere neue Lehrstuhlwebseite und werde mich ab und zu mit Fragen, Bugs und Featurerequests hier melden.

Bei der Übernahme von Kontaktdaten aus dem Univis werden die Suffixe ohne "Komma" übernommen, siehe hier:
![image](https://cloud.githubusercontent.com/assets/14542489/9989408/4dac3c20-6058-11e5-8d9d-da59cb4aadc1.png) 
Im Univis stimmts noch:
![image](https://cloud.githubusercontent.com/assets/14542489/9989440/9472f392-6058-11e5-9686-5a814fc5b762.png)

Viele Grüße,
Jan Hofmann

**Comment by endv02** [comment]
Danke für den Hinweis, ist drin in Version 1.2.9
