### ISSUE TITLE
Absätze ohne Abstand beim Einbinden in einer Seite

### ISSUE THREAD

**Issue by shoprex** [RRZE-Webteam/fau-person#106]
Hallo zusammen,

lasse ich einen Kontakt direkt anzeigen werden Absätze mit richtigem Abstand angezeigt. Lasse ich den Kontakt in einer Seite mit [person id="579" format="page"] anzeigen, haben die Absätze keinen Abstand.

Beispiel:

Direkte Kontaktanzeige: https://sport.cms.rrze.uni-erlangen.de/person/ralf-sygusch/

Mit Einbindung: https://sport.cms.rrze.uni-erlangen.de/lehrstuehle-und-fachgebiete/bildung-im-sport/mitarbeiter/sygusch-prof-dr-ralf/

Als Hinweis vielleicht noch, ich habe damals das CSS angepasst für https://sport.cms.rrze.uni-erlangen.de/ Vielleicht habe ich selber da einen Fehler reingebracht. Leider habe ich kein Zugriff auf das CSS und konnte auch direkt keinen Fehler finden.

Viele Grüße
Andreas

**Comment by endv02** [comment]
Danke für den Hinweis. Ist korrigiert in Version 1.2.9.
