### ISSUE TITLE
Kontakt-Filter im Backend defekt

### ISSUE THREAD

**Issue by j-hofmann** [RRZE-Webteam/fau-person#107]
Filtern von Kontakten nach Kategorien scheint nicht zu funktionieren. Außer der Default-Ansicht ohne Filter (Alle anzeigen) wird eine leere Liste gezeigt:
![kontakt-filter-bug](https://cloud.githubusercontent.com/assets/14542489/10429419/b88dc288-70f8-11e5-8a22-c2e90c922ade.png)

**Comment by endv02** [comment]
Drin in Version 2.1.10
