### ISSUE TITLE
Übersicht über alle Parameter

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#108]
Kann bitte jemand eine Übersicht über alle aktuellen Parameter und deren Schreibweise erstellen? Die Angaben hier und auf wordpress.rrze.fau.de sind nicht einheitlich und imho konfus. Bitte eine zentrale Stelle anlegen, wo alle Parameter aufgelistet sind und aktuell gepflegt werden. Gerne auch mit Beispielen, wie sich die Anzeige durch die Verwendung von format="" ändert.

**Comment by steffigebel** [comment]
kommt gleich von Frau Kimpan! ;-)

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: cibsell <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/fau-person <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Mittwoch, 4. November 2015 17:03
An: RRZE-Webteam/fau-person <fau-person@noreply.github.com<mailto:fau-person@noreply.github.com>>
Betreff: [fau-person] Parameter (#108)


Kann bitte jemand eine Übersicht über alle aktuellen Parameter und deren Schreibweise erstellen? Die Angaben hier und auf wordpress.rrze.fau.de sind nicht einheitlich und imho konfus. Bitte eine zentrale Stelle anlegen, wo alle Parameter aufgelistet sind und aktuell gepflegt werden. Gerne auch mit Beispielen, wie sich die Anzeige durch die Verwendung von format="" ändert.

**Comment by cibsell** [comment]
Danke!

Christiane Sell, M.A.
Friedrich-Alexander-Universität Erlangen-Nürnberg
Naturwissenschaftliche Fakultät
Referentin für Öffentlichkeitsarbeit
Cauerstr. 11, Raum 02.341
91058 Erlangen, Germany

Phone:  + 49 9131 85-67093
Email:  nat-pr@fau.de<mailto:nat-pr@fau.de>
        christiane.sell@fau.de<mailto:christiane.sell@fau.de>
WWW:    http://www.nat.fau.de<http://www.nat.fau.de/>

Von: Steffi [mailto:notifications@github.com]
Gesendet: Mittwoch, 4. November 2015 17:08
An: RRZE-Webteam/fau-person <fau-person@noreply.github.com>
Cc: Sell, Christiane <christiane.sell@fau.de>
Betreff: Re: [fau-person] Parameter (#108)

kommt gleich von Frau Kimpan! ;-)

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de>>
www.rrze.fau.de<http://www.rrze.fau.de>

Von: cibsell <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>>
Antworten an: RRZE-Webteam/fau-person <reply@reply.github.com<mailto:reply@reply.github.com<mailto:reply@reply.github.com%3cmailto:reply@reply.github.com>>>
Datum: Mittwoch, 4. November 2015 17:03
An: RRZE-Webteam/fau-person <fau-person@noreply.github.com<mailto:fau-person@noreply.github.com<mailto:fau-person@noreply.github.com%3cmailto:fau-person@noreply.github.com>>>
Betreff: [fau-person] Parameter (#108)


Kann bitte jemand eine Übersicht über alle aktuellen Parameter und deren Schreibweise erstellen? Die Angaben hier und auf wordpress.rrze.fau.de sind nicht einheitlich und imho konfus. Bitte eine zentrale Stelle anlegen, wo alle Parameter aufgelistet sind und aktuell gepflegt werden. Gerne auch mit Beispielen, wie sich die Anzeige durch die Verwendung von format="" ändert.

**Comment by xwolfde** [comment]
Haha, da such ich auch gerade nach :)

**Comment by xwolfde** [comment]
Hierhin alles was die Parameter angeht: https://github.com/RRZE-Webteam/fau-person/issues/60
