### ISSUE TITLE
Zeilenumbrüche in Kontakten

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#109]
Bitte die Zeilenumbrüche in den Kontakten im Content-Feld entfernen. Das sieht einfach nicht schön aus und bricht auch schon bei kurzen URLs oder längeren E-Mail-Adressen um.

![zeilenumbrueche](https://cloud.githubusercontent.com/assets/8234890/10943850/9c5a9bc4-8316-11e5-9b3b-c6048115b7ec.png)

**Comment by steffigebel** [comment]
Das geht leider nicht, da ein unsichtbarer Trennstrich in der Mitte vorliegt, da theoretisch Platz für möglichen weiteren Inhalt wie z. B. Sprechzeiten etc. vorgehalten wird.
--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: cibsell <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/fau-person <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Mittwoch, 4. November 2015 17:08
An: RRZE-Webteam/fau-person <fau-person@noreply.github.com<mailto:fau-person@noreply.github.com>>
Betreff: [fau-person] Zeilenumbrüche in Kontakten (#109)


Bitte die Zeilenumbrüche in den Kontakten im Content-Feld entfernen. Das sieht einfach nicht schön aus und bricht auch schon bei kurzen URLS oder längeren E-mail-Adressen um.

[zeilenumbrueche]<https://cloud.githubusercontent.com/assets/8234890/10943850/9c5a9bc4-8316-11e5-9b3b-c6048115b7ec.png>

**Comment by endv02** [comment]
Das Problem hatten wir kürzlich auch bei der Med. Fak. und ist darin begründet, dass hier eigentlich ein zweispaltiger Kasten vorliegt. Hierzu unsere Stellungsnahme damals:

"Der Rahmen um die Personeneinträge im Text ist im FAU-Design festgelegt worden. Das wurde so damals auch von den Fakultäten abgesegnet. Beispiel: https://www.fau.de/universitaet/leitung-und-struktur/leitung/
Der Umbruch der Mailadresse liegt daran, dass gestalterisch vorgesehen ist, hier weitere Informationen in einer zweiten Spalte (bei Verwendung eines Bildes sogar in drei Spalten) einzupflegen.
Einzig in der Sidebar wird der Rahmen um die Personeneinträge weggelassen, aber gerade hier ist die Breite (logischerweise) ebenso begrenzt, daher bricht auch hier die Mailadresse um.
Das Problem mit dem begrenzten Platz für die Mailadresse, vor allem wenn in der rechten Spalte keine Informationen stehen, ist designtechnisch interessant, trat jedoch jetzt erstmals auf. Hierfür muss allerdings eine Lösung in den Themes gefunden werden, und größere Arbeiten an diesen müssen aufgrund aktuell anderer wichtiger Projekte leider bis zum nächsten Frühjahr ruhen, wie Herr Wiese bereits kommuniziert hatte."
Also sorry, geht grad im Moment leider nicht anders.

**Comment by cibsell** [comment]
Hallo endv02,

das wurde damals sicher nicht von den Fakultäten so abgesegnet. Die Fakultäten wurden nur bezüglich der Startseite der Fakultäten befragt und nicht bezüglich irgendwelcher Darstellungsmöglichkeiten irgendwelcher Plugins.  Pauschal zu sagen „die Fakultäten wollten das so“ ist falsch und schürt nur Unverständnis.

Es scheint sich, nach Ihrer Aussage, offensichtlich um ein Problem der Darstellung zu handeln, das mindestens an zwei Fakultäten nicht akzeptabel erscheint. Daher bitte ich um Nachbesserung.

Mit freundlichen Grüßen
Christiane Sell
--
Christiane Sell, M.A.
Friedrich-Alexander-Universität Erlangen-Nürnberg
Naturwissenschaftliche Fakultät
Referentin für Öffentlichkeitsarbeit
Cauerstr. 11, Raum 02.341
91058 Erlangen, Germany

Phone:  + 49 9131 85-67093
Email:  nat-pr@fau.de<mailto:nat-pr@fau.de>
        christiane.sell@fau.de<mailto:christiane.sell@fau.de>
WWW:    http://www.nat.fau.de<http://www.nat.fau.de/>

Von: endv02 [mailto:notifications@github.com]
Gesendet: Mittwoch, 4. November 2015 17:13
An: RRZE-Webteam/fau-person <fau-person@noreply.github.com>
Cc: Sell, Christiane <christiane.sell@fau.de>
Betreff: Re: [fau-person] Zeilenumbrüche in Kontakten (#109)


Das Problem hatten wir kürzlich auch bei der Med. Fak. und ist darin begründet, dass hier eigentlich ein zweispaltiger Kasten vorliegt. Hierzu unsere Stellungsnahme damals:

"Der Rahmen um die Personeneinträge im Text ist im FAU-Design festgelegt worden. Das wurde so damals auch von den Fakultäten abgesegnet. Beispiel: https://www.fau.de/universitaet/leitung-und-struktur/leitung/
Der Umbruch der Mailadresse liegt daran, dass gestalterisch vorgesehen ist, hier weitere Informationen in einer zweiten Spalte (bei Verwendung eines Bildes sogar in drei Spalten) einzupflegen.
Einzig in der Sidebar wird der Rahmen um die Personeneinträge weggelassen, aber gerade hier ist die Breite (logischerweise) ebenso begrenzt, daher bricht auch hier die Mailadresse um.
Das Problem mit dem begrenzten Platz für die Mailadresse, vor allem wenn in der rechten Spalte keine Informationen stehen, ist designtechnisch interessant, trat jedoch jetzt erstmals auf. Hierfür muss allerdings eine Lösung in den Themes gefunden werden, und größere Arbeiten an diesen müssen aufgrund aktuell anderer wichtiger Projekte leider bis zum nächsten Frühjahr ruhen, wie Herr Wiese bereits kommuniziert hatte."
Also sorry, geht grad im Moment leider nicht anders.

**Comment by xwolfde** [comment]
Das die Öffentlichkeitsarbeiter damals nicht richtig aufgepasst haben und nur ein simples Startseite-Images absegneten ohne nachzufragen ist deren Fail, für den ich diesen auch weiterhin die Verantwortung geben werde.
Die Entscheidung bedeutet, daß die "Öffentlichkeitsarbeiter "die Umsetzung und Arbeit uns überlassen haben. Daher müssen sie auch mit den Ergebnissen leben. Zumal diese nun seit Monaten testbar gewesen wären. 
Da keine Rückmeldungen erfolgten, ist diese Problem ganz offensichtlich auch nicht so wichtig.


Das Grundproblem sehe ich allerdings auch. Wir werden da bei Gelegenheit schauen, was sich da machen lässt. Eine hohe Priorität kann ich dem aber nicht geben, da andere Dinge -z.B. die Korrekturen des responsiven Designs- viel wichtiger sind.
Bereits jetzt kann man schon die Personenliste auch anders machen. Dann muss man eben mit den Shortcode-Kommandos was machen.
Aber das Ausgabeformat das hier gewählt wurde, müssen wir nunmal auf eine Weise fest legen.

**Comment by xwolfde** [comment]
Ergänzung/Konkretisierung:

https://github.com/RRZE-Webteam/fau-person/issues/60
Hier ist halt ein anderes Ausgabeformat zu definieren.
Bei dem jetzt gewählten ist alles richtig formatiert, allerdings fehlt die Perosneninfo, die in der zweiten Spalte angezeigt werden sollte. Da diese fehlt siht es jetzt doof aus. Das diese fehlt ist aber nicht Feil der Programmierung sondern der Eingabe bzw. der Auswahl des jetzigen Ausgabeformates.

**Comment by FlorianFiller** [comment]
Nur als Anmerkung nebenbei:
Da den "Öffentlichkeitsarbeitern" nur ein Screenshot einer Startseite zur Entscheidung vorgelegt wurde, bin ich weiterhin der Meinung, dass sich die Zustimmung auch nur auf das entsprechend grundlegende Layout der Startseite bezieht. Alle weiteren "Details" müssen eben nachverhandelt werden. Von "Fail" würde ich da nicht grundsätzlich sprechen - vielmehr von Kompromissbereitschaft (logischerweise auf beiden Seiten).

**Comment by xwolfde** [comment]
Nun, wir zwingen keiner Einrichtung das Theme auf. Wer nicht will, braucht nicht mitzumachen. 
Wer aber Änderungen möchte, möge auch daran aktiv mitarbeiten oder sie mit finanzieren.  Wünsche kann man gern äußern, aber diese können auch abgelehnt werden oder in der Priorität gering gewertet werden.

**Comment by xwolfde** [comment]
Nach div. Rücksprache:
Wir werden ein neuen Ausgabeformat (vgl. auch #60  ) einstellen für eine gekachelte Indexansicht.
Dazu ergänzte ich unter den Fall #60 dann ein entsprechender Punkt.
Für die Umsetzung in den Themes ergänze ich eigene Issues, da Optik dorthin gehört.

Diese sind:
https://github.com/RRZE-Webteam/FAU-Philfak/issues/76
https://github.com/RRZE-Webteam/FAU-Medfak/issues/28
https://github.com/RRZE-Webteam/FAU-Natfak/issues/16
https://github.com/RRZE-Webteam/FAU-RWFak/issues/7
https://github.com/RRZE-Webteam/FAU-Techfak/issues/2
https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/5

Bitte konkrete Wünsche und Vorstellungen wie diese besondere Indexdarstellung aussehen soll (mit welchen Inhaltsattributen genau) bitte in den Issues ergänzen. Wenn nichts angegeben ist, müssen wir hier wieder ein Best Fit machen.  Daher daran beteiligen oder für immer schweigen wenn es umgesetzt wurde :)
