### ISSUE TITLE
Import / Export von Kontakten von/zu Wordpress

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#110]
Ich habe mit der Export/Importfunktion von Wordpress die angelegten Kontakte von chem.nat.fau.de auf die neue Seite chemie.nat.fau.de exportiert. Das ist soweit auch gelungen, alle Kontakte sind vorhanden. Die neue Seite hat die ID-Nummern der alten Seite übernommen.

Nun habe ich aber z. B. bei der neuen Seite eine Lehrstuhlseite, auf der die Sekretärin als Kontakt angegeben ist: https://chemie.nat.fau.de/department/lehrstuehle/lebensmittelchemie/ . Ich habe folgenden Shortcode verwendet:

[person id="5698" hide="adresse, abteilung, organisation" show="fax, raum"]

Die ID ist auch die richtige, auf der neuen Seite ist der Kontakt unter dieser ID angelegt worden: https://chemie.nat.fau.de/person/christine-meissner/ 

Auf der Lehrstuhlseite ist allerdings die Verknüpfung fehlerhaft. 

Wenn ich den oben genannten Shortcode eingebe, dann verknüpft es den Kontakt immer noch mit der alten Seite unter http://chem.nat.fau.de/person/christine-meissner/ (die Seite lässt sich nur innerhalb eines bestimmten IP-Bereichs abrufen, aber sie funktioniert).

Was kann ich machen? Ich möchte nicht alle 150 Kontakte noch einmal neu eingeben müssen. Ich hatte es schon mit Cache löschen versucht und mit einem anderen Browser, aber die Verknüpfung ist weiterhin fehlerhaft.

**Comment by endv02** [comment]
Ich habe mir das gerade mal angeschaut, das Problem ist, dass das Feld "Name und "Mehr"-Link verlinken auf Seite ..." nicht leer ist sondern noch mit der alten URL belegt ist. Wurde das in jedem Kontakt eingepflegt?

**Comment by cibsell** [comment]
Das scheint der Fehler zu sein. Ich habe die Kontakte von einer Kollegin anlegen lassen. Sie wird die entsprechenden Felder löschen. Sie hat aber, soweit sie sich erinnern kann, unter "Name und Mehr"-Link nichts eingetragen, allerdings ist das Feld beim erneuten Aufruf des Kontakts im Backend gefüllt. Wird dieses Feld beim Speichern des Kontakts automatisch gefüllt?

**Comment by endv02** [comment]
Hm... kann das vielleicht mit dem Exportieren zusammenhängen? Oder wird das Feld erst in den importierten Kontakten immer wieder gefüllt? Bei mir ist auch nach mehrmaligem Öffnen eines Kontaktes das Feld nicht automatisch gefüllt worden.

**Comment by endv02** [comment]
Hallo Frau Sell, also, ich hab jetzt nochmal das mit dem Im- und Export getestet und bei mir gab es keine Probleme. Auch nach dem Import konnte das Feld problemlos geleert werden. Ich würde auch generell empfehlen, das Feld leer zu lassen, sofern es nicht zu einer speziellen anderen Seite als der Personen-Detail-Seite verweisen soll. 
Unterhalb des Feldes steht ja der Vermerk "Standardwert...", evtl. wurde hier beim Anlegen der Kontakte einfach der Wert mit in das Feld übernommen, so wie das ja mit den UnivIS-Anzeigen auch gemacht wird, und so kam der jetzt falsche Link hier rein?
Wenn Sie nicht jeden Kontakt einzeln anpassen wollen, können Sie auch die importierten Kontakte nochmal exportieren, dann den Link in der XML-Datei dementsprechend automatisiert anpassen (oder den Eintrag löschen) und dann die XML-Datei wieder importieren. Es kommt dann die Meldung, dass der Kontakt bereits existiert, aber die Daten werden aktualisiert. Also zumindest in meiner Testumgebung hat es so geklappt ;-)
Viele Grüße
Karin Kimpan
