### ISSUE TITLE
Abhängigkeit von internen Plugin

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#111]
"AB VERSION 1.2.0 FUNKTIONIERT DIE UNIVIS-ANBINDUNG NUR NOCH, WENN ZUSÄTZLICH DAS PLUGIN univis-data (https://gitlab.rrze.fau.de/rrze-webteam/univis-data) INSTALLIERT IST!"

Das ist gut und schön, aber das Gitlab-Plugin ist für niemand ausser uns zugreifbar :)
Daher wäre es gut, wenn es eine Möglichkeit gäbe, es auch ohne zu betreiben.

**Comment by endv02** [comment]
Nein, das Gitlab-Plugin ist öffentlich erreichbar. Und wegen der Cache-Funktionalität, die wir bestimmt auch beim rrze-univis-Plugin nutzen können, macht es evtl. Sinn, das in einem zentralen Plugin auszulagern.

**Comment by endv02** [comment]
Ab Version 1.3 erledigt, da das univis-data-Plugin geändert wurde und jetzt integriert ist.
