### ISSUE TITLE
Anlegen von Kontakten nur für Administratoren?

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#112]
Ist es richtig, dass nur Administratoren Kontakte anlegen können?

Es wäre gerade für die Departments- und Lehrstuhlseiten notwendig, dass auch Redakteure Kontakte anlegen können. Die Lehrstühle pflegen ihre Unterseiten auf der Webseite der Departments eigenständig und haben oft die Kontaktdaten ihrer Doktoranden etc. auch auf ihren Webseiten veröffentlicht. Diese Angaben sollten auf allen Seiten einer Webseite gleich aussehen.

**Comment by endv02** [comment]
Aktuell ist es so, dass nur der Administrator die Kontakte anlegen kann, evtl. wird in einer späteren Version die Einstellungs-Möglichkeit eingebaut, dass man entscheiden kann, ob auch Redakteure Zugriff bekommen. 
Bis dahin können aber problemlos mit dem Workflow-Plugin auch den Redakteuren die Rechte auf die Kontakte gegeben werden. Es gab schon mal das Issue "Redakteur kein Zugriff auf UnivIS-ID Suche #96", aus dem ich auch geschlossen habe, dass Sie das bisher erfolgreich genutzt haben?

**Comment by endv02** [comment]
@xwolfde ist das OK so, dass standardmäßgi nur Administratoren mit den Kontakten arbeiten sollen, und alles andere über das Workflow-Plugin gelöst werden soll?

**Comment by endv02** [comment]
Es wird erstmal weiterhin so bleiben, dass nur Administratoren Kontakte anlegen können. Evtl. später Regelung über Optionsseite, deshalb erst mal Issue closed
