### ISSUE TITLE
Bei englischer Seite 2x Contact 

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#113]
Bei einem englischsprachigen Wordpress-Auftritt steht in der linken Menüleiste zweimal "Contact", wenn man sowohl FAU Person als auch Contact Form 7 freigeschaltet hat. Das könnte zu Verwirrungen führen.

**Comment by xwolfde** [comment]
Das können wir nicht ändern. Die erste Bezeichnung "Contact" kommt aus dem Theme und beinhaltet die Verwaltung der Kontakte aus dem FAU Person.
Die zweite Bezeichnung kommt aus Contact Form 7, die ihre Lasche ebenfalls im englischen Contact nennt.
bei der zweiten Bezeichnung können wir nicht jedesmal, wenn es ein Update gibt, die Bezeichnung ändern. Bei der ersten Lasche möchte ich es nicht in was anderes umbenennen, weil es eben die Kontaktverwaltung ist und wir das genau so nennen.

Ich sehe keine Lösungsmöglichkeit für dieses Problem.

**Comment by endv02** [comment]
Ab der Version 2.1 wird der Menüpunkt in "Kontakte" umbenannt (bei Seiten etc. ist ja auch die Mehrzahl), damit erscheint in der englischen Version automatisch "Contacts" und man kann das unterscheiden.
