### ISSUE TITLE
Kontakt Kategorien anzeigen lassen

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#114]
Hallo,

ich habe die Möglichkeiten Kategorien im Kontakte-Plugin anzulegen. Gibt es die Möglichkeit auf einer Seite alle Personen der Kategorie auszulesen? Wie lautet hierfür der Shortcode? 

kontakt category="" bzw. kontakt categories="" geht nicht...

Bei Arbeitskreis-Seiten wäre es sehr praktisch, da hier viele Kontakte auf einmal angezeigt werden sollen (Doktoranden, Postdocs), aber nicht alle, die in UnivIS bei der Professur dabei stehen (z. B. nicht-wissenschaftl. Personal oder Emeriti)

**Comment by steffigebel** [comment]
Aktuell ist das nicht einsatzfähig. Aber ist natürlich ein guter Punkt.

Da man allerdings Einrichtungsadressen Kontakte zuweisen kann, wäre ich nicht sicher, ob da bald was kommen könnte.


--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: cibsell <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/fau-person <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Montag, 25. Januar 2016 15:04
An: RRZE-Webteam/fau-person <fau-person@noreply.github.com<mailto:fau-person@noreply.github.com>>
Betreff: [fau-person] Kontakt Kategorien anzeigen lassen (#114)


Hallo,

ich habe die Möglichkeiten Kategorien im Kontakte-Plugin anzulegen Gibt es die Möglichkeit auf einer Seite alle Personen der Kategorie auszulesen? Wie lautet hierfür der Shortcode?

kontakt category="" bzw kontakt categories="" geht nicht

Bei Arbeitskreis-Seiten wäre es sehr praktisch, da hier viele Kontakte auf einmal angezeigt werden sollen (Doktoranden, Postdocs), aber nicht alle, die in UnivIS bei der Professur dabei stehen (z B nicht-wissenschaftl Personal oder Emeriti)

**Comment by endv02** [comment]
Das geht bereits, und zwar mit dem Shortcode
persons category=" "
Die Anpassung auf einen anderen Shortcode kommt noch, dann wird es auch in der Doku aufgeführt werden. Der jetzige Shortcode wird jedoch weiter funktionieren.
