### ISSUE TITLE
Fehler bei Ausgabe Telefonnummer

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#115]
Habe aktuell den Fall, dass im Kontakt folgende Telefonnummer eingegeben wurde: +49 9131 85-27326 (B), -67506 (L1), -27315 (L2) . B steht für Büro, L für Labor. Diese Angabe findet sich häufiger in UnivIS bei Naturwissenschaftlern.

Diese wird hier https://chemie.nat.fau.eu/person/christian-papp/ so ausgegeben:

+49 9131 85-73152

**Comment by xwolfde** [comment]
Das ist aber erstmal ein Fehler bei der UnivIS-Eingabe.
Dann haben wir das Feature noch nicht, weitere Eingabefelder zu berücksichtigen.

Da hat der UnivIS-Beauftragte tatsächlich bei dem Feld der Telefonnummer den ganzen Schladeradatsch angegeben.
http://univis.uni-erlangen.de/form?__s=2&dsc=anew/tel_view&pers=nat/dchph/lpc2/pappch&anonymous=1&founds=nat/dchph/lpc2/pappch&sem=2015w&tel_nosem=1&__e=825

Aber das macht es nicht richtiger. Solche willkürlichen Eingaben können wir keinesfalls berücksichtigen. Es ist auch völlig unklar, was dort mit B, L1 oder L2 gemeint ist.
Ein Fehler ist es daher nicht -es ist gewollt, dass nicht erkennbarer, willkürlich gesetzter Text oder sonstiges rausgeworfen ist.

Korrekt wäre es im UnivIS einen zweiten oder dritten Adresseintrag zu machen.
Dazu muss der UnivIS-Beauftragte beim Bearbeiten der Person auf den Button "Weitere Anschriften eingeben" klicken und dann entsprechendes einfügen.

ich hab das mal bei mir gemacht:
http://univis.uni-erlangen.de/form?__s=2&dsc=anew/tel_view&pers=zwiss/rrze/abi/wiesew&anonymous=1&founds=zwiss/rrze/abi/wiesew&sem=2015w&tel_nosem=1&__e=825

Ich würde dies mal als Feature-Request vorschlagen: Weitere Adresseinträge aus UnivIS zur selben Person berücksichtigen (falls das nicht schon passiert),

**Comment by endv02** [comment]
Die Telefonnummernfelder werden unüberarbeitet ausgegeben, wenn beim Standortanschluss "Allgemeine Rufnummer" ausgewählt wird. Das wäre der schnelle Workaround.

Ansonsten sollten nur Ausgabeumformatierungen stattfinden, wenn eindeutig nur eine Telefonnummer enthalten ist. Das wird bei der nächsten Version korrigiert. 

Deshalb sollten auch nicht mehrere Telefonnummern in einem Feld drin stehen, sondern hierfür mehrere Anschriften in UnivIS verwendet werden. Allerdings wird das vom Personenplugin auch noch nicht umgesetzt...
