### ISSUE TITLE
Umlaute in UnivIs-ID-Suche

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#117]
Es ist leider nicht möglich, in der Suche (Vor- Nachname) Umlaute einzugeben. Das wäre ein nettes Feature für die Kunden, die dann etwas verstört wirken, wenn der Kontakt nicht gefunden werden kann. Oder man setzt ein Fehler-Pop-Up

**Comment by endv02** [comment]
Aber der HInweis steht doch bei beiden Eingabefelden eindeutig dabei, warum wirken sie dann verstört...? Ja, kann man evtl. noch optimieren später mal.

**Comment by endv02** [comment]
In Version 2.3.0 drin
