### ISSUE TITLE
Lehrveranstaltungsanzeige aus UnivIS bei Einzelseiten ergänzen

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#118]
siehe hier: http://www.str3.jura.fau.de/lehrveranstaltungen/wintersemester-201516/uebung-im-strafrecht-fuer-fortgeschrittene.shtml das wäre doch auch noch ne Option und würde da gut passen

**Comment by endv02** [comment]
Nachdem alle Lehrveranstaltungen in UnivIS drin sind, würde ich das einfach nur aus UnivIS rausnehmen und auf den Einzelseiten anzeigen lassen, so wie es beim Webbaukasten auf der Seite oben auch gemacht wird. Aber nicht so, dass man selber noch Lehrveranstaltungen eingeben kann, das wäre dann wirklich doppelte Datenpflege.

**Comment by xwolfde** [comment]
erstmal  nicht
