### ISSUE TITLE
Shortcode für Kontaktliste ändern

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#119]
Wenn man mehr als einen Konatt aufrufen will haben wir noch die Funktion fau_persons:
        add_shortcode( 'persons', 'fau_persons' );

Diese reagiert auf [persons]

ich würde folgende Änderung vorschlagen:

Shortcode [persons] wird nur noch als Fallback gelassen und geändert auf:
        add_shortcode( 'kontaktliste', 'fau_persons' );

Ausserdem würde ich in dem normalen
   [kontakt ... ]

gern als Alternative zu id="(Liste)" lieber category="(catslugtitle)" haben.
Also
  [kontakt catergy="kategorieslug"]

**Comment by endv02** [comment]
In Version 2.1.2 drin
