### ISSUE TITLE
Bug Compactindex format

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#120]
Zeile 334:
        if( $compactindex )     $content .= '<div class= "compactindex';

Div wird nicht richtig geschlossen?

**Comment by xwolfde** [comment]
Und eigentlich bedeutet compactindex dorch ein egewisse Auflistung an show/hide, oder? Die wird mir noch garnicht definiert Z 97. so wie bei format=plain und anderen

**Comment by endv02** [comment]
Bug ist in Version 2.0.2 korrigiert, angezeigt wurden die Standardangaben, die beim Default-Shortcode gezeigt wurden. Hab es jetzt angepasst auf die Angaben aus Issue #60:
Ausgabeattribute: Thumbnail, Fullname, Position, Telefon, E-Mail, Adresse
Mit <div class="compactindex"> umgeben, so dass die dritte Spalte über das Theme-css weggelassen werden kann.
