### ISSUE TITLE
Kurzauszug

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#122]
Wenn ich es recht verstanden habe, gehört der Kurzauszug nicht zu den default-Parametern, muss also mit "show" explizit angezeigt werden. Wird er nur unter bestimmten Bedingungen (Format oder ähnliches) angezeigt? Bei einem "normal" angegebenen Kontakt auf der Seite wird zwar die Kurzbeschreibung angezeigt, der Kurzauszug aber nicht.
Shortcode: [[kontakt id="132" show="kurzbeschreibung, fax, mobil, kurzauszug"]]
Ergebnis: 
![bildschirmfoto 2016-02-24 um 14 29 43](https://cloud.githubusercontent.com/assets/11296947/13286658/16de5310-db03-11e5-99cd-f9fdf3af837b.png)

**Comment by endv02** [comment]
kurzauszug habe ich laut meiner Übersicht nur bei format=sidebar oder beim Widget (was auch der Sidebar über den Ansprechpartner in den FAU-Themes entspricht)
In der normalen Darstellung ist weder Kurzauszug noch Kurzbeschreibung gewünscht gewesen, drum gab es da diesen Mehr-Button.
Der Inhalt wird noch bei format=page angezeigt, das was bei Kurzbeschreibung steht bei format=liste (alternativ der Excerpt aus dem Content, falls in der Kurzbeschreibung nichts drin steht).
