### ISSUE TITLE
Anpassungsmöglichkeiten für einzelne Kontakte auch für Kontaktliste erlauben

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-person#123]
Es wäre wünschenswert, wenn die Anpassungsmöglichkeiten wie sie bereits für einzelne Kontakte existieren (show, hide) auch für die Kontaktliste übernommen werden. 

(Wir versuchen dort wo es sich anbietet mit Kontakt-Kategorien zu arbeiten um die spätere Pflege der Inhalte zu erleichtern. Gleichzeitig bekommen wir aber auch oft Anfragen von Kollegen, um z.B. deren Portrait-Bilder einzubinden. Im Moment bietet die Kontaktliste allerdings leider keine Möglichkeit diese Anpassung (show="bild") vorzunehmen... )

**Comment by endv02** [comment]
Sollte mit Version 2.1 funktionieren (das show/hide wirkt sich halt dann auf alle Kontakte aus, da gibt es keine Ausnahme). Außerdem können die Formate auch für die Kategorien angewendet werden.
