### ISSUE TITLE
Individuellen Pfad für Mitarbeiter-Verzeichnis

### ISSUE THREAD

**Issue by fapfa** [RRZE-Webteam/fau-person#124]
Hallo,

momentan liegt jeder angelegte Kontakt unter .../{hauptseite für beiträge}/person/{name}.

Es wäre schön, wenn man den Pfad der angelegten Kontakte selbst definieren könnte. In unserem Fall gibt es eine Seite mit "Lehrstuhl-Team", die alle angelegten Kontakte auflistet. Klickt man einen Kontakt an, springt die Seite auf /aktuelles/person/...
Übrigens: Das Breadcrumb-Menü zeigt jedoch Startseite/Kontakt/{name}

**Comment by endv02** [comment]
Hm... hab das jetzt mal versucht nachzuvollziehen, kann es aber nicht rekonstruieren... haben Sie eine konkrete Seite für mich zum Anschauen?

**Comment by fapfa** [comment]
Natürlich... hier ein Beispiel:
https://www.kowi.rw.fau.de/lehrstuhl/lehrstuhlteam/
Das Breadcrumb zeigt regulär: "Startseite /Lehrstuhl /Lehrstuhlteam"

-> nun Klick auf eine Person, z.B. Prof. Holtz-Bacha --> Pfad springt zu "**/Aktuelles/Person/**..."
(https://www.kowi.rw.fau.de/aktuelles/person/christina-holtz-bacha/)
und das Breadcrumb zeigt: "**Startseite /Kontakt /**Prof. Dr. Christina Holtz-Bacha"

Schön wäre: https://www.kowi.rw.fau.de/**lehrstuhl/lehrstuhlteam/**christina-holtz-bacha/

**Comment by steffigebel** [comment]
Hm, aber die "schön wäre Seite" existiert gar nicht...

Die Personenseiten sind natürlich via Sitemap anders verortet. Die Breadcrumb ist an der Stelle richtig, denn die Personenseite lliegt ja in den Kontakten und nicht im Lehrstuhlteam. Das ist so gewollt. Ansonsten kann auf der Seite auch die Vollansicht der Person gezeigt werden, was aber eher nicht erwünscht ist, wie ich das verstehe. Dank "zurück-Button" kommen die Besucher wieder auf die Lehrstuhlteam-Seite.


________________________________
Von: fapfa [notifications@github.com]
Gesendet: Montag, 4. April 2016 20:26
An: RRZE-Webteam/fau-person
Betreff: Re: [RRZE-Webteam/fau-person] Individuellen Pfad für Mitarbeiter-Verzeichnis (#124)


Natürlich... hier ein Beispiel:
https://www.kowi.rw.fau.de/lehrstuhl/lehrstuhlteam/
Das Breadcrumb zeigt regulär: "Startseite /Lehrstuhl /Lehrstuhlteam"

-> nun Klick auf eine Person, z.B. Prof. Holtz-Bacha --> Pfad springt zu "/Aktuelles/Person/..."
(https://www.kowi.rw.fau.de/aktuelles/person/christina-holtz-bacha/)
und das Breadcrumb zeigt: "Startseite /Kontakt /Prof. Dr. Christina Holtz-Bacha"

Schön wäre: https://www.kowi.rw.fau.de/**lehrstuhl/lehrstuhlteam/**christina-holtz-bacha/

**Comment by fapfa** [comment]
Natürlich exstiert die Seite nicht, das war ja auch der Wunsch!
Das war doch meine Frage: Es wäre schön, wenn man den Custom Post Type "Person" benutzerspezifisch verorten könnte. Es macht hier doch keinen Sinn, wenn "Person" ein Child von "Aktuelles" ist und das Breadcrumb nochmal ein anderes Parent ("Kontakt") anzeigt.
Und klickt man im Breadcrumb der Person-Seite auf "Kontakt", kommt man auf die nicht existente Seite https://www.kowi.rw.fau.de/person/

Nochmal: https://www.kowi.rw.fau.de/aktuelles/person/christina-holtz-bacha/
Bei dieser Seite zeigt das Breadcrumb entgegen der URL: Startseite **/Kontakt **/Prof. Dr. Christina Holtz-Bacha

**Comment by steffigebel** [comment]
Ok, jetzt weiß ich, was gemeint ist. Das ist tatsächlich etwas unschön. Können Sie ins Git bei „FAU-EINRICHTUNGEN“ einen Issue schreiben dafür? Das wäre super.
--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: fapfa <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/fau-person <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Dienstag, 5. April 2016 09:20
An: RRZE-Webteam/fau-person <fau-person@noreply.github.com<mailto:fau-person@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>
Betreff: Re: [RRZE-Webteam/fau-person] Individuellen Pfad für Mitarbeiter-Verzeichnis (#124)


Natürlich exstiert die Seite nicht, das war ja auch der Wunsch!
Das war doch meine Frage: Es wäre schön, wenn man den Custom Post Type "Person" benutzerspezifisch verorten könnte. Es macht hier doch keinen Sinn, wenn "Person" ein Child von "Aktuelles" ist und das Breadcrumb nochmal ein anderes Parent ("Kontakt") anzeigt.
Und klickt man im Breadcrumb der Person-Seite auf "Kontakt", kommt man auf die nicht existente Seite https://www.kowi.rw.fau.de/person/

Nochmal: https://www.kowi.rw.fau.de/aktuelles/person/christina-holtz-bacha/
Bei dieser Seite zeigt das Breadcrumb entgegen der URL: Startseite */Kontakt */Prof. Dr. Christina Holtz-Bacha

**Comment by xwolfde** [comment]
Nein, gehört schon hierhin, weil Sache des Plugins.


Ich kann es gleich sagen: Geht nicht so einfach. Ist aufwendig und hat mehr Nachteile als Vorteile.
Wir könnten dazu eine Option bereitstellen, die den Permalink für diesen Personentyp änderbar macht.
Aber der Supportaufwand und die Gefahr der irrtümlichen Nutzung ist viel zu hoch als das ich das momentan befürworten würde.

**Comment by fapfa** [comment]
Okay, es war einen Versuch wert ;-)

**Comment by endv02** [comment]
So, bin jetzt aber dennoch dahinter gekommen, warum das Ganze unter www.kowi.rw.fau.de/*AKTUELLES*/person... erscheint:
In den Einstellungen - Permalinks steht bei Ihnen Benutzerdefniert: /aktuelles/%postname%
Damit wandern alle Posttypes unterhalb von aktuelles. Das ist natürlich nicht sinnvoll, die Personen sollten generell natürlich unter www.kowi.rw.fau.de/person... erscheinen.

**Comment by fapfa** [comment]
Ja, das ist mir vorhin auch aufgefallen und da haben Sie natürlich recht.
Die eigentliche Anfrage löst das nur zum Teil... aber da es zu aufwändig ist, gebe ich leiber klein bei.
Trotzdem danke!

**Comment by xwolfde** [comment]
VORSICHT mit der Permalink-Einstellung!  Die ändert nämlich nicht nur die personen-Posttypes,sonern auch alle anderen. Nämlich auch die Links der Beiträge, der Glossare, der Akronyme, Events, etc.
Genau deswegen ist der Supportbedarf für eine Änderung an der STelle hoch, da dies gefährlich ist.

**Comment by fapfa** [comment]
Gilt der Hinweis mir? Danke, ich arbeite seit 2007 mit Wordpress und habe entsprechende Erfahrung (auch wenn ich die Permalink-Einstellung erst spät wieder eingefallen ist).
Die Verlinkung/Redirects funktionieren in meinem Fall glücklicherweise weiterhin. Google-Links werden problemlos weitergeleitet, der Link-Checker hat nichts gefunden. Und ich habe die Verlinkung auf interne Seiten bewusst nicht manuell, sondern über das Kontext-Menü (und somit die Seiten-ID) gemacht.

**Comment by xwolfde** [comment]
Nee, ging primär an Karin und Steffi :)
