### ISSUE TITLE
Sprachversion

### ISSUE THREAD

**Issue by pdees** [RRZE-Webteam/fau-person#128]
Die Sprachdatei funktioniert offensichtlich nur mit der Spracheinstellung "English (United States)", nicht mit "Englisch (UK)". Das gibt einen Konflikt mit dem CRIS-Plugin, wo die Spracheinstellung nur umgekehrt funktioniert (dort ist das Issue auch offen). Zumindest eine Angleichung wäre wünschenswert.

**Comment by xwolfde** [comment]
Bitte erstmal en-US auf en_GB kopieren (nicht verschieben)

**Comment by endv02** [comment]
en_GB ist ab Version 2.1 mit drin
