### ISSUE TITLE
Formatangaben ohne und mit Leerzeichen in Plugins

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#132]
Hallo,

mir ist aufgefallen, dass bei fau-person das Leerzeichen zwischen den Angaben bei show=" ", 
z. B. [kontakt id="11510" format="kompakt" show="raum, webseite"] zwingend notwendig ist. Lässt man es weg, zeigt es die Angaben nicht an. 

Leider ist es bei fau-events genau umgekehrt. Dort muss man die Kategorien ohne Leerzeichen eingeben, da sie sonst nicht angezeigt werden, z. B. 
[kalender kategorien=”Allgemein,Vortraege,Promotion,Fakultätssitzungen,schuelerveranstaltungen” abonnement_link=1]

Das ist ein bisschen verwirrend für den Benutzer. Kann man das bitte vereinheitlichen?

**Comment by endv02** [comment]
Stimmt, ist blöd... werden wir mal in uns gehen, danke für den Hinweis!

**Comment by endv02** [comment]
ist in Version 2.1.2 so gelöst, dass sowohl mit als auch ohne Leerzeichen eingegeben werden kann. Ich pack das Issue auch noch zu fau-events
