### ISSUE TITLE
format="kompakt" kein Zeilenumbruch

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#133]
Habe format="kompakt" gewählt, aber die Zeilen werden immer noch umgebrochen.

Siehe: 
[kontakt id="11510" format="kompakt" show="raum, webseite"]

https://www.nat.fau.de/fakultaet/referate/

**Comment by steffigebel** [comment]
Wieso "immer noch"? Hat jemand etwas anderes in Aussicht gestellt?

**Comment by cibsell** [comment]
Version 2.0.2: Format kompakt ergänzt

    Shortcode-Format kompakt angepasst: Darstellung wie Standardausgabe mit Rahmen, soll im Theme jedoch auf die volle Breite ergänzt werden. Default-Anzeigewerte: Bild, vollständiger Name, Position, Telefon, Mail, Adresse

**Comment by steffigebel** [comment]
Ich denke nicht, dass es auf "keinen" Zeilenumbruch hinausläuft. Genausp wie bei allen anderen Layouts der Kontakte ist hier noch Platz vorgehalten für die "3. Spalte". Aber Karin wird hierzu sicher was sagen.

**Comment by endv02** [comment]
kompakt wurde eingeführt um die gleiche Darstellung zu haben wie ohne Format-Angabe, allerdings sollte hierbei die dritte Spalte entfernt werden, die eh meist nicht genutzt wird, damit die Mailadressen nicht künstlich umbrechen. 
Welches Format wollten Sie denn eigentlich in der Darstellung haben?

**Comment by cibsell** [comment]
Es soll eben kein Zeilenumbruch künstlich erzeugt werden. Die dritte Spalte sollte entfernt werden.

**Comment by endv02** [comment]
Sorry, hatte ich vorhin übersehen, bei der URL wird noch umgebrochen, klar. Ja das sollte nicht mehr sein. Ich forsche nach.

**Comment by cibsell** [comment]
Position wird auch noch umgebrochen...

**Comment by endv02** [comment]
Hab nochmal geschaut, schreiben Sie es bitte beim Theme nochmal rein? Das schien noch nicht komplett gefixt gewesen zu sein.

**Comment by xwolfde** [comment]
Das Theme macht alles richtig. Das ist das Plugin, was hier falschen HTML Code liefert:
Es wird der falsche span verwendet



```
<div class="compactindex">
<div class="row">
<div class="span1 span-small" itemprop="image">
...
</div>
<div class="span3">
...
</div>
</div>
</div>
```

"span1" hat eine feste Breite, genauso wie "span3".
Wenn durch den Kompaktindex die 3 Spalte wegfällt darf daher die 2. Spalte nicht mehr "span3" haben, sondern sollte auf "span6" geändert werden.
Oder anders erklärt:
3 Spalter bei der Personen sieht so aus:

row
span1 span3 span3
/row

2 Spalter mit Image:

row
span1 span6
/row

1 Spalter ohne alles:

Kein Row drumherum, kein span.

Kein Image, aber dann 2 Spalten:

row
span4 span4
/row

bzw. 
span4 span3

**Comment by endv02** [comment]
Ab Version 2.1.1 gefixed.
