### ISSUE TITLE
Kontakt mit Bild in der Sidebar

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#134]
Wenn man in der Sidebar die Kontaktdaten mit Bild anzeigt und darunter noch Links hat, sieht das irgendwie leicht beknackt aus. Kann man da etwas mit Textumfluss oder Bild über den Daten machen?

Screenshot:

![bildschirmfoto 2016-04-12 um 17 20 42](https://cloud.githubusercontent.com/assets/11296947/14465472/635c9f1c-00d3-11e6-8ff4-08605677f16b.png)

**Comment by xwolfde** [comment]
Stimmt, aber einen Tod muss man sterben. Der Textfluss würde dort nicht festlegbar sein, da die Einrichtungsbeeichnung unterschiedlich lang sein kann.

Der Fehler liegt woanders, nämlich bei dem User: Die Sidebar DARF keine Linkwüste werden, so wie da schon gemacht.

**Comment by AstridSemm** [comment]
Hm. Karin meinte doch, dass das Bild in der Sidebar obendrüber kommt? Siehe hier: https://github.com/RRZE-Webteam/fau-person/issues/73
Und vonwegen Linkwüste: Die Jungs haben genau so viele Links gesetzt wie per default erlaubt. Ich sehe jetzt nicht, warum das eine Linkwüste ergäbe... ^^

**Comment by endv02** [comment]
Ich glaube auch dass die Sidebar zu schmal ist um das Bild noch nebendran zu setzen. Vermute aber dass da noch Murks in meinem Code drin ist, werde nochmal genauer nachschauen.

**Comment by endv02** [comment]
@AstridSemm: Wo ist denn der Screenshot her? Wenn ich das bei mir einbinde habe ich tatsächlich sowohl mit Shortcode als auch über Ansprechpartner-Auswahlliste immer das Bild oben drüber. Nur wenn ich im Content einen Shortcode mit format=sidebar einbaue sehe ich das Bild links davon.

**Comment by endv02** [comment]
So, taucht nur bei Portalseiten auf und ist damit wieder Sache des Themes, also hier zu
