### ISSUE TITLE
Adressdaten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#135]
Bei den Adressdaten einer ORG erscheinen die bei einer persoennausgabe noch nicht so ganz richtig formatiert. Dort wird nur die streetadress für Strasse und Ort verwendet,.

So sollte das aber bspw. aussehen:

```
<div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
    <span itemprop="streetAddress">3102 Highway 98</span>
    <span itemprop="addressLocality">Mexico Beach</span>,
    <span itemprop="addressRegion">FL</span>
  </div>
```

vgl http://schema.org/Place

**Comment by endv02** [comment]
Wo genau denn? Innerhalb der Personendaten oder beim Standort?

**Comment by xwolfde** [comment]
Überall wo man Adressdaten ausgibt.

**Comment by endv02** [comment]
Enthalten ab Version 2.1.5
