### ISSUE TITLE
Personendaten in der Sidebar immer noch nicht vorhanden

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#137]
Wenn man eine Website besucht (Stand heute), die noch nicht manuell mit den anzegeoptionen ausegfüllt und aktualisiert wurde, werden die Kontakte immer noch nicht vollständig in der Sidebar angezeigt. Sondern eben nur Vornamen, Nachname. Erst wenn man dann die Häckchen setzt. Das ist ungünstig, weil das die Kunden ja nicht wissen. @Karin: Weisst du,was ich meine? Ich erklärs dir gerne mündlich, wills hier nur schnell festhalten, sonst vergesse ich das wieder.

**Comment by endv02** [comment]
Hm... habe jetzt mal eine neue Instanz in meinem Testauftritt angelegt, da passt das standardmäßig und es wird automatisch alles angezeigt. Scheint also noch von der Zeit dazwischen zu sein... werde das jetzt manuell bei den Instanzen überprüfen und anpassen, dann sollte das nicht mehr auftreten. Danke für den Hinweis!

**Comment by endv02** [comment]
Alle CMS-Instanzen jetzt überprüft und ggf. eingestellt (sind übrigens inzwischen über 80, die das Personen-Plugin aktiviert haben...)

**Comment by steffigebel** [comment]
Is ja auch cool 👍🏼

Von meinem iPhone gesendet

Am 28.04.2016 um 12:03 schrieb endv02 <notifications@github.com<mailto:notifications@github.com>>:


Alle CMS-Instanzen jetzt überprüft und ggf. eingestellt (sind übrigens inzwischen über 80, die das Personen-Plugin aktiviert haben...)
