### ISSUE TITLE
Ausdruck

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#139]
Der Ausdruck eines Kontaktes sieht merkwürdig aus. Die Überschriften sind versetzt und überlagern den Text. Außerdem wird Platz zwischen dem Header (Logo) und dem Inhalt verschwendet (leerer weißer "Balken")
![screenshot-ausdruck-kontakt](https://cloud.githubusercontent.com/assets/8234890/15149078/73c6b47c-16c8-11e6-9e5b-cfb5355d0c4f.png)

**Comment by xwolfde** [comment]
Danke für den Hinweis. An den Ausdruck von Webseiten haben wir noch nie was geändert und immer noch das Original...
Da müssen wir rran; ggf. wäre das eine Sache die wir beauftragen müssen.
An der Stelle aber eine wichtige Rückfrage: hast du die URL mal? Das sieht auch ein bisschen verdächtig nach einer HTML-Table aus, die da verwendet wird wo sie ungültig ist...

**Comment by xwolfde** [comment]
Ich hab die Seite gefunden.
https://chemie-en.cms.rrze.uni-erlangen.de/steinrueck-group/

Die Fehler gehen darauf zurück, dass du bzw. jemand mit Adminzugang da grässliche Dinge im HTML-Code gemacht hat:
Inline-Styles, Tables, wo keine hingehören, semantische Fehler über und über....
Die Inline-Styles sind dann auch wahrscheinlich die Ursache, warum es es im Print Fehler gibt. Sowas zum Beispiel ist ein No-Go:
    `style="margin-top:-221pt"`

Und auch solch eine Überschrift ist absoluter Unfug:
```
<h2 style="margin-top:-35pt"><span>Univ.-Prof. Dr.</span> <span>Hans-Peter</span> <span>Steinrück</span><br>
</h2>
```
Was hast du dir dabei gedacht, also du die &lt;span&gt;s reingetan hast? Die machen da doch in dieser Form überhaupt keinen Sinn?!?!  Und das &lt;br&gt;??
Und das Inline-Style mit margin-top verschiebt die Überschrift dem entsprechend im print.


Dir ist bewusst, dass alle deine HTML-Codes nur als Admin funktionieren? Sobald ein Redakteur da ran geht, werden invalide HTML-Anweisungen und alle Inlinestyles korrigiert - d.h. weg gemacht.

**Comment by cibsell** [comment]
Hallo Wolfgang,

danke für den Hinweis. Bin davon ausgegangen, dass das Kontakte-Plugin verwendet wird (sieht auf den ersten Blick so aus). Ich spreche mit der Person. Allerdings: die Person ist bisher auch kein Admin, sondern Redakteur.

**Comment by xwolfde** [comment]
Das ist dann wirklich was wo wir nachprüfen müssen. Nicht das das Workflow-Plugin Editoren ungewollt zu viele Rechte gibt.

**Comment by cibsell** [comment]
Das Problem mit den Überschriften ist ja jetzt gelöst (Fehler durch Redakteur), aber ich möchte noch einmal auf das Problem hinweisen (nicht, dass es untergeht), dass etwa 1/3 einer Din A4-Seite durch weißen Leerraum verschwendet wird beim Ausdruck. Könnte man diesen zusammenkürzen?

**Comment by xwolfde** [comment]
Sollten wir angehen ja. Ich werde das mal als Punkt für die Themes aufnehmen, dass wir uns das en Detail anschauen und korrigieren.

**Comment by xwolfde** [comment]
https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/60 
Als issie bei dem Quelltheme eingetragen
