### ISSUE TITLE
Schema property name missing

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#141]
Bei der Anzeige der Personen wird zwar firstName und givenName angegeben, jedoch fehlt der required Property "name".

Bitte diesen -wenn es eine Überschrift vor den Namen gibt- dort einfügen (bei der Personenseite geschieht dies bereits), oder bei der Darstellung als Shortcode für Sidebars oder andere ohne Title bei den givenName ergänzen. Und zwar so:

`<span itemprop="givenName"><span itemprop="name">Smith</span></span>`

vgl. auch http://stackoverflow.com/questions/24336647/how-to-nest-microdata-using-schema-org-in-a-valid-way

Wichtig ist, das wir immer den Property "name" irgendwo haben.

**Comment by endv02** [comment]
Ist ab Version 2.1.5 mit drin
