### ISSUE TITLE
Redakteuren fehlt UnivIS-Suche

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#142]
Redakteuren fehlen die Rechte, um nach der UnivIS-ID zu suchen. Die Rechte brauchen sie aber, um die Lehrstuhlseiten mit den jeweiligen Arbeitskreisen aufzubauen. Sonst muss das der Admin machen, aber die Arbeitskreise sollen ihre Seiten selbst pflegen und entsprechend auch die Mitarbeiter-Kontakte eigenverantwortlich anlegen können.

**Comment by steffigebel** [comment]
Welche ID genau? Es gibt dafür mehrere Wege. Melde mich nach dem Mittag.

Von meinem iPhone gesendet

Am 07.06.2016 um 09:42 schrieb cibsell <notifications@github.com<mailto:notifications@github.com>>:


Redakteuren fehlen die Rechte, um nach der UnivIS-ID zu suchen. Die Rechte brauchen sie aber, um die Lehrstuhlseiten mit den jeweiligen Arbeitskreisen aufzubauen. Sonst muss das der Admin machen, aber die Arbeitskreise sollen ihre Seiten selbst pflegen und entsprechend auch die Mitarbeiter-Kontakte eigenverantwortlich anlegen können.

**Comment by cibsell** [comment]
Es fehlt komplett die Seite "Nach Univis-ID suchen". Es werden nur drei Seiten angezeigt: All contacts, Add new und Contact categories.

**Comment by endv02** [comment]
Das hatten wir doch schon mal in einem anderen Issue geklärt, dachte ich... Mittels cms-workflow-Plugin sollte die Seite auf jeden Fall sichtbar sein.

Am 07.06.2016 10:15 schrieb cibsell <notifications@github.com>:

Es fehlt komplett die Seite "Nach Univis-ID suchen". Es werden nur drei Seiten angezeigt: All contacts, Add new und Contact categories.

**Comment by cibsell** [comment]
Ist aber auch mit dem Plugin nicht sichtbar...

**Comment by endv02** [comment]
Ok, dann forsche ich genauer nach, danke für ein Hinweis. Meines Wissens nach ging das nämlich schon mal.

Am 07.06.2016 13:08 schrieb cibsell <notifications@github.com>:

Ist aber auch mit dem Plugin nicht sichtbar...

**Comment by cibsell** [comment]
Problem ist mehr oder weniger gelöst. Die Redakteure müssen in Workflow folgende zusätzliche Berechtigungen haben: 
Allow Post Types: Posts
Editors Capabilities: Edit Posts

Ist mir zwar unverständlich, da das eine mit dem anderen nichts zu tun haben sollte, aber ich akzeptiere das jetzt mal so. ;-)
