### ISSUE TITLE
FAU in voller Anzeige gewünscht

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#143]
Es kam der Wunsch, dass bei den Kontaktseiten in voller Ansicht bzw. bei format full / page der Universitätsname auch angezeigt wird. Argument: Externe kennen Univis nicht und schauen auf die jeweilige Webseite des Forschers. Wenn sie ihm einen Brief schreiben, dann fehlt die vollständige Adresse:

Friedrich-Alexander-Universität Erlangen-Nürnberg
Department xy
Lehrstuhl xy
Name
...

**Comment by endv02** [comment]
Könnte ich fest in den Code reinprogrammieren. Wegen der allgemeinen Gültigkeit des Plugins allerdings  nur bei einer fau.de-Domain.
@xwolfde Gegenmeinung aufgrund von Erfahrungswerten?

**Comment by xwolfde** [comment]
Und was passiert bei Kooperationen und anderen Einrichtungen, die nicht allein der FAU zugeordnet sind? Davon haben wir auch einige Dutzend... Das müsste dann berücksichtigt werden.

**Comment by endv02** [comment]
Ok, dann kann ich das nur bei den Optionen als anklickbar mit einbauen.

**Comment by xwolfde** [comment]
Standort-Posttype mit Abkürzung ergänzen.
Dann kann man das umsetzen.

**Comment by xwolfde** [comment]
#269

**Comment by xwolfde** [comment]
Wird im neuen FAUdir-Plugin neu angegangen. Hier keine Änderung mehr.
