### ISSUE TITLE
Anzeige der Adresse in richtiger Reihenfolge

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#144]
In der Sidebar wurde es ja bereits umgesetzt, aber für den Content-Bereich noch nicht. Es wird gewünscht die Adresse zwischen Abteilung und Telefonnummer zu setzen, wie bei einer Visitenkarte.

**Comment by endv02** [comment]
Reihenfolge wird ab Version 2.1.10 genauso übernommen wie bei der Sidebar. 
Standardausgabe:
![ohne-format](https://cloud.githubusercontent.com/assets/5851793/17617484/bb6c62b2-607a-11e6-993d-eec0baee51bf.png)
Standardausgabe (alle möglichen Ausgaben  mit show="..." angezeigt):
![ohne-format-alle-ausgaben](https://cloud.githubusercontent.com/assets/5851793/17617394/3554fd2e-607a-11e6-8b37-e1c1098ac34f.png)
format="kompakt":
![format-kompakt](https://cloud.githubusercontent.com/assets/5851793/17617507/d99d5b6a-607a-11e6-9a73-84f2b3267316.png)
format="kompakt" (alle möglichen Ausgaben mit show="..." angezeigt):
![format-kompakt-alle-ausgaben](https://cloud.githubusercontent.com/assets/5851793/17617413/56cdff46-607a-11e6-9669-252daa05293e.png)
