### ISSUE TITLE
Sortierung nach Vor- oder Nachname, nicht nach Titel des Kontakt-Eintrags

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-person#145]
z.b. bei Verwendung des Parameters "category" sollten die Kontakte nach Vor- oder Nachnamen sortiert werden und nicht über den Titel des Kontakt-Eintrags. 

Könnte ja entweder in den Kontakte-Anzeigeoptionen eingestellt werden damit es für den ganzen Auftritt einheitlich ist oder optional über einen Shortcode-Parameter.

**Comment by cibsell** [comment]
Habe das gleiche Problem. Bisher werden in der Kontakte-Datenbank die Titel "Vorname Nachname" eingegeben. Ein Kollege will aber die Ausgabe über Parameter category nach Nachname auf der Webseite sortiert haben. Nun hat er sich nicht anders zu helfen gewusst, als bei allen seinen Einträgen (Doktoranden etc., also eine relativ große Anzahl) den Titel in "Nachname, Vorname" zu ändern.

Das wäre an sich kein Problem, aber im Bearbeitungsmodus der Seiten werden in der Box Contact Information / Kontaktinformationen und in der Sidebar "Auswahl Ansprechpartner" die Kontakt-IDs nun völlig durcheinander angezeigt, weil sie nicht mehr einheitlich nach Vor- oder Nachname sortiert werden. So steht in der Auswahlliste nun z. B. 
- Heiko Weber
- Henkel, Christian
- Henning Gieseler

**Comment by endv02** [comment]
Puh, schwierige Sache. Also, mischen ist immer schlecht. So richtig schlecht. Auf ursprünglichen Wunsch habe ich das ganze ja umprogrammiert, dass es nach Nachname in der Kontaktinformationsbox sortiert wird, aber als "Vorname Nachname" dargestellt wird. Und zwischendrin sind dann noch die "Nicht-Personen" alphabetisch reinsortiert. Die Auswahlliste in der Metabox "Sidebar" kommt über das Theme, da ist es nach Vorname sortiert. Und dann noch die Sortierungswünsche innerhalb der Kategorie... 
Also generell erstmal: über den ganzen Webauftritt hinweg die Personen einheitlich eingeben! Wenn man nicht die Daten aus UnivIS holt und das Vor- und Nachnamefeld leer lässt, wird das Titelfeld 1:1 ausgegeben, also manchmal mit Nachname, Vorname und manchmal "Vorname Nachname". 
Und nur aus Sortiergründen zu entscheiden, in welcher Form der Name eingegeben wird, ist auch nicht zielführend.
Mein Vorschlag: Bitte auch weiterhin immer mit "Vorname Nachname" eingeben, ich überlege mir, ob und wie man die Kategorien sortieren kann.

**Comment by endv02** [comment]
Wird in Version 2.2.1 mit drin sein als zusätzlicher Parameter.

**Comment by endv02** [comment]
Ab der nächsten Version mit drin. Dann ist bei der Kategorie-Ansicht mit dem zusätzlichen Parameter sort="nachname" die Sortierung bei Personen nach Nachname (wenn nicht vorhanden, dann wird das letzte Wort des Titels als Nachname angenommen) bzw. bei Einrichtungen nach Bezeichnung (wenn nicht vorhanden nach Titel) vorgenommen.
