### ISSUE TITLE
.content-person: Linker Innenabstand zu gering (bei max-width: 767px)

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-person#149]
In der mobilen Ansicht erhält das eingebundenen Kontakt-Element zuwenig Innenabstand. Padding left & right wurde auf 0 gesetzt (.content-person) . Siehe Bild

Sollte zumindest wieder auf 10px gesetzt werden - oder nicht? 

![padding_left](https://cloud.githubusercontent.com/assets/6545158/17515259/983ef11e-5e37-11e6-87e0-265e137e2702.png)

**Comment by endv02** [comment]
Ich geb das mal ins Theme weiter...

**Comment by xwolfde** [comment]
In der nächsten version behoben
