### ISSUE TITLE
Weiße Seite nach Installation

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#15]
Habe das Plugin Vers. 1.0 versucht zu installieren und bekam nach der Installation eine leere, weiße Seite. Verwende zuzüglich das FAU-Theme und die darin aufgelisteten zusätzlichen Plugins.

**Comment by cibsell** [comment]
Selbes Problem mit dem anderen Branch.

**Comment by endv02** [comment]
Bitte jetzt nochmal probieren, eine funktionsfähige Version 1.0 sollte jetzt verfügbar sein, auch mit dem FAU-Theme. Feedback wird gerne entgegengenommen!
