### ISSUE TITLE
Bei Anzeige der Kurzbeschreibung via Shortcode werden Akkordeons nicht gerendert

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-person#150]
Mir ist aufgefallen, dass beim Einbinden eines Kontakts + Anzeige der Kurzbeschreibung via Shortcode, die darin enthaltenen Accordeons nicht gerendert werden und die Shortcodes als einfacher Text im Html stehen.
An dieser Stelle wäre es ja auch nicht erwünscht diese zu rendern, aber vielleicht kann man hier den Shortcode einfach rausfiltern bzw. ausblenden damit es zumindest nicht zu einer solchen Ausgabe kommt. (Siehe Bild)

(Ich habe nicht vor Accordeons in der Kurzbeschreibung zu verwenden und wahrscheinlich auch kaum ein anderer, aber... )

![accordeons_kurbeschreibung](https://cloud.githubusercontent.com/assets/6545158/17550382/fadf45d6-5ef4-11e6-9e15-2f5b179dd0f4.png)

**Comment by xwolfde** [comment]
Tut mir leid, aber das geht nicht.
Wir können keine Shortcodes mit Erstreckungstag (also mit mehrzeiligen Inhalten, die wiederum Shortcodes enthalten) durch ein Shortcode ausgeben und dann wieder neu interpretieren lassen.

Wenn ihnr sowas machen wollt, dann macht ihr einen Shortcode mit einen Teil der Personeninfos und danach den Shortcode mit den Accordioninfos auf der jeweiligen Seite.  Aber im Beschreibungsfeld geht das nicht.

**Comment by csw-** [comment]
Es ging mir nich darum das umzusetzen, sondern eher zu Verhindern das der Shortcode als Text interpretiert wird und so dann angezeigt wird. Aber es ist sicher auch ein Fall der höchst selten auftreten wird.
