### ISSUE TITLE
category: Bei leerer Kontakt-Kategorie wird der komplette Seiteninhalt (main) nicht ausgegeben

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-person#151]
Bei Verwendung des category-Parameters [persons category="..."] kommt es bei einer leeren Kontakt-Kategorie zu einem Fehler: Der gesamte Seiteninhalt (unter main) wird nicht ausgebenen. (Siehe Bild)

EDIT: Außerdem wird in dem Fall auch die Adminbar ausgeblendet...

![persons_category](https://cloud.githubusercontent.com/assets/6545158/17633318/f7f6e214-60cc-11e6-9bbf-c060048e2c42.png)

**Comment by endv02** [comment]
War ein Bug, ist in der nächsten Version korrigiert.
