### ISSUE TITLE
Listen-Ansicht und Attribute

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#152]
kontakt id="xxx" format="liste" hide="kurzbeschreibung" show="telefon"

hide funktioniert, aber show="" geht nicht, auch nicht mit einem anderen Attribut.

**Comment by endv02** [comment]
Das Format liste ist generell so erstellt, dass nur die Kurzbeschreibung hinzugefügt werden kann, alles andere eigentlich nicht. Welche Anzeigen wären denn noch nötig und in welcher Darstellung?

**Comment by cibsell** [comment]
So wie z. B. hier unter Kollegiale Departmentsleitung: https://www.biologie.nat.fau.de/department/organisation/ 

Das ist ein Univis-Import, nehme ich an, aber viele pflegen ihre Univis-Seiten nicht so gut wie die Biologie...

**Comment by endv02** [comment]
Also ist ausschließlich die Telefonnummer zusätzlich nötig? Oder kann es sein, dass jemand auch z.B. noch die Mailadresse oder so kommasepariert haben will?

**Comment by cibsell** [comment]
Also mir wurde jetzt nur die Bio-Seite mit der Telefonnummer genannt, dass das gut ist. Aber mit Email wäre es vielleicht auch nicht schlecht. Sollte halt nicht zu viel bei "Liste" stehen, sonst kann man ja einen anderen Parameter verwenden.

**Comment by endv02** [comment]
Beim Format liste kann ab Version 2.1.17 kommasepariert noch die Telefonnummer und/oder Mailadresse ergänzt werden über show="telefon, mail"
