### ISSUE TITLE
hide="bild" generiert Fehler in Accordion

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#153]
Hallo allerseits,

ich will auf einer Entwurfseite in einem Accordion einen Kontakt anzeigen lassen. Dafür verwende ich folgenden Shortcode: 

`[collapsibles]
[collapse title="Lehrstuhl für Anorganische und Metallorganische Chemie" color=""]
[kontakt id="xxx" format="kompakt" hide="bild, abteilung" show="raum, fax"]
[/collapse]

[collapse title="Lehrstuhl für Anorganische und Allgemeine Chemie" color=""]
[kontakt id="xxx"]
[/collapse]

[collapse title="Lehrstuhl für Bioanorganische Chemie" color=""]
[kontakt id="xxx"]
[/collapse]
[/collapsibles]`

Dabei scheint "bild" einen Fehler zu generieren, denn die Darstellung ist wie folgt:

![bild-fehlermeldung](https://cloud.githubusercontent.com/assets/8234890/17773127/0fe1b6b8-654d-11e6-9283-b87261b51683.jpg)

Lasse ich "bild" fort, dann wird das Accordion korrekt dargestellt. Der Kontakt wird in beiden Fällen aber korrekt dargestellt, es hat nur Auswirkungen auf das Accordion.

**Comment by endv02** [comment]
Sollte gelöst sein.
