### ISSUE TITLE
PHP7 Kompatibilität

### ISSUE THREAD

**Issue by alrb** [RRZE-Webteam/fau-person#154]
Das Plugin scheint noch nicht mit PHP7 kompatibel zu sein.
Wenn man es aktiviert erscheint folgender Eintrag im Apache-errorlog:
_PHP Fatal error:  Cannot use "self" when no class scope is active in /var/www/homepage/wp-content/plugins/fau-person-master/includes/cmb/init.php on line 1185_

**Comment by rvdforst** [comment]
Es tut uns leid, aber dieses Plugin ist noch nicht mit PHP7 kompatibel.
