### ISSUE TITLE
Show="sprechzeiten, raum" funktionieren nicht mehr

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#155]
Ticket: https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=530780

Beispiel: https://arbeitsmarkt.cms.rrze.uni-erlangen.de/lehrstuhl/prof-dr-claus-schnabel/ 

Sprechzeiten und Raum eingetragen, werden aber trotz Befehl nicht ausgegeben.

**Comment by xwolfde** [comment]
Hat der @rvdforst das nicht gestern gefixt? Fall schließen?

**Comment by rvdforst** [comment]
Der Wert "sprechzeiten" wird jetzt angezeigt. Aber das Shortcode hat weitere Probleme. Irgendwie die Werte "adresse" und "raum" sind voneinander abhängig (ich weiß nicht, was die Karin damit gemeint hat). Im Moment der Raum wird angezeigt, wenn der Wert "adresse" enthalten ist. Also Ich überarbeite gerade die entsprechenden Funktionen um die Fehler zu beseitigen.

**Comment by xwolfde** [comment]
Bitte achte darauf, im Dev Zeig zu überarbeiten . da hab ich gestern auche in Bugfix reingetan

**Comment by rvdforst** [comment]
Die Karin hat mich gebeten den Dev-Branch nicht weiter zu ändern. Der Kunde soll einfach die ganze Adresse anzeigen lassen, wenn er den Raum haben will. Also der Code bleibt unverändert bis die Karin wieder vom Urlaub zurück ist.

**Comment by xwolfde** [comment]
Ich arbeite die ganze Zeit im Dev-Zweig... Dafür ist der da.

**Comment by steffigebel** [comment]
Das bitte dann dem/den Kunden mitteilen.

Von meinem iPhone gesendet

Am 25.08.2016 um 09:30 schrieb rvdforst <notifications@github.com<mailto:notifications@github.com>>:


Die Karin hat mich gebeten den Dev-Branch nicht weiter zu ändern. Der Kunde soll einfach die ganze Adresse anzeigen lassen, wenn er den Raum haben will. Also der Code bleibt unverändert bis die Karin wieder vom Urlaub zurück ist.

**Comment by cibsell** [comment]
Bitte Raum und Adresse unabhängig voneinander anzeigbar machen / lassen. Insbesondere bei Lehrstuhlseiten oder Arbeitskreisen möchten die Nutzer bei einer Auflistung der Mitarbeiter zwar die Raumnummern, aber nicht jedes Mal die vollständige Adresse (die in 90% der Fälle die gleiche ist) anzeigen lassen.

**Comment by endv02** [comment]
Korrigiert in Version 2.1.16
