### ISSUE TITLE
Falsches h2-Heading bei Auflistung von mehreren Ansprechpartnern in der Sidebar

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-person#159]
Wenn ich mehrere Ansprechpartner (festgestellt bei zwei) für eine Seite einstelle, bekommt der zweite Ansprechpartner ein leeres h2-Heading. Das macht zwar optisch keinen Unterschied aber aus technischer Sicht wird die HTML-Outline dadurch (an dieser Stelle) fehlerhaft.

(Ja ich weiß, es ist etwas ironisch, dass gerade dieses Issue von mir kommt, aber es ist mir eben aufgefallen... :P )

![contact_headings](https://cloud.githubusercontent.com/assets/6545158/17960987/71106b08-6aa9-11e6-8c32-b51e7a0d71ca.png)

**Comment by xwolfde** [comment]
Bin schon dran, bzw. ist schon im test gefixt. Hast du ein Zugang zu mein Testserver? Wenn nicht, schick mal ne DM

**Comment by xwolfde** [comment]
fixed im dev
