### ISSUE TITLE
h3-Headings der Personennamen bei Einbindung im main-Content aufheben?

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-person#161]
Nochmal zu den Headings der Personen: Die Personennamen sind ja mit einem h3-Tag versehen, in der Sidebar ergibt es Sinn, da der Kontakt-Titel mit einem h2-Tag abgebildet wird.

Im normalen Seiteninhalt kollidiert der h3 aber mit der ggf. vorhandenen Content-Struktur. Dies ist der Fall wenn der Text noch mit h3 oder sogar h4-headings unterteilt wird. 

Um ein Beispiel zu zeigen: Wir haben mehrere Seiten auf denen bestimmte Gremien abgebildet werden. Wichtige Personen werden dabei mit einer eigenen Headline hervorgehoben. In der Outline steht dann allerdings der Kontakt im Moment entweder parallel oder sogar über der eigentlichen Überschrift.

Vielleicht hat ja jemand einen Vorschlag wie man das anders strukturieren könnte, oder ob man die Personeneinbindung anpasst, oder... 

![contact_headings2](https://cloud.githubusercontent.com/assets/6545158/17962133/ad9f390e-6aaf-11e6-980e-d302e3cc8395.png)

**Comment by xwolfde** [comment]
Da hast du recht.
ggfl. wäre es sinnvoll, ein Attribut einzubauen wie "headingstart" mit Default = 3 als Wert und gültige Werte aus 1-6. Die Überschrift wird dann mit dem Wert beginnen.

**Comment by xwolfde** [comment]
ref #204
