### ISSUE TITLE
Unterschiedliche Bildgrößen bei Ansprechpartner (Kontakt in Sidebar) einer Seite

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-person#162]
Die Möglichkeit, die Reihenfolge der Ansprechpartner wie sie in der Sidebar erscheinen, manuell anzupassen um z.B. Hierarchie, Zugehörigkeit oder Verantwortlichkeit abzubilden wäre ein nice-to-have..

Beispiel: Auf unseren Profilseiten (für Fachbereich, Forschung, Studium, International) stellen wir beispielsweise die zugehörigen Dekane (Forschungsdekan, etc..) sowie einen weiteren Ansprechpartner dar. Eine rein alphabetische Sortierung nach dem Nachnamen wäre für uns hier also suboptimal, vor allem wenn auch der UnivIS-Eintrag nicht ordentlich gepflegt ist und keine Positionsbeschreibung vorliegt. 

Vielleicht gibt es noch andere Anwendungsfälle bei den Kollegen? Gedanken, Meinungen dazu?

![contact_sidebar_order](https://cloud.githubusercontent.com/assets/6545158/17966818/f2b3f48a-6ac3-11e6-9d72-262c8ecba482.png)

**Comment by xwolfde** [comment]
Die Reihenfolge bei der Metabox zusätzlich über Pfeiltasten o.ä. aufzubauen oder änderbar zu machen wäre sehr aufwendig.  Und es würde die Bedienung gerade für unbedarftere Nutzer des Themes durch die steigende Komplexität erschweren.
Daher würde ich sagen, dass man in solchen Fällen lieber auf die Nutzung der Shortcodes verweist und nicht die Metabox im Backend bei der Seitenbearbeitung nutzt.

**Comment by csw-** [comment]
In Ordnung, da komme ich aber gleich noch zu einer anderen Beobachtung: Bei der Verwendung des Shortcodes mit format=sidebar werden die eingestellten Anzeigeoptionen derzeit ja nicht beachtet. [1]

Das wäre aber recht hilfreich um eine einheitliche Darstellung der Ansprechpartner zu erreichen, bei Verwendung der normalen Ansprechpartner-Auswahl via Menü und der Shortcodes (z.B. wenn eine andere Reihenfolge benötigt wird).
Zudem wird mit show=bild eine andere Bildgröße ausgegeben als bei format=sidebar. [2]

[1] 
![shortcode_sidebar](https://cloud.githubusercontent.com/assets/6545158/18026535/975afa06-6c4a-11e6-8156-999e64e43c16.png)
[2] 
![shortcode_sidebar2](https://cloud.githubusercontent.com/assets/6545158/18026544/e0c8c7fe-6c4a-11e6-825f-290fa669b72a.png)

**Comment by xwolfde** [comment]
im nächsten update behoben
