### ISSUE TITLE
format=page: Bild ohne Caption

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#163]
Personenbild hat keine Caption....
test:
http://test8.tindu.rrze.uni-erlangen.de/tests/shortcodes/accordion-und-personen/personenseite-im-seitenmodus/

Vorbild:
https://www.fau.de/universitaet/leitung-und-struktur/leitung/prof-dr-joachim-hornegger-praesident/

Ausserdem ist die Überschrift zu prüfen, ob sie für die Seite anpassbar ist. 

Ausserdem ist doe

**Comment by xwolfde** [comment]
Bild wird  ausserdem nicht im responsiblen Format ausgeliefert :(

**Comment by xwolfde** [comment]
Mgw. wird ein  hide="name"  benötigt, damit als erste Überschrift etwas anders als der Name angezeigt werden kann.

**Comment by endv02** [comment]
Name wird jetzt standardmäßig ausgeblendet (ist ja im Normalfall eh schon auf der Kontaktseite in der Überschrift), bei Verwendung vom Shortcode kann er mit show="name" angezeigt werden aber Version 2.1.16

**Comment by endv02** [comment]
Fehlendes Caption sollte mit Version 2.6.3 behoben sein
