### ISSUE TITLE
Format Page - Text nur auf der Kontaktseite

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#165]
Man kann ja im Kontakt einen Text zusätzlich eingeben, was praktisch ist für Lebensläufe und dergleichen. 
![bildschirmfoto 2016-09-01 um 09 09 57](https://cloud.githubusercontent.com/assets/11296947/18158486/ef0a0454-7023-11e6-9c2f-c1718713945d.png)

Der wird auf der Kontaktseite auch brav angezeigt:
![bildschirmfoto 2016-09-01 um 09 11 09](https://cloud.githubusercontent.com/assets/11296947/18158511/137b15e4-7024-11e6-8acd-ea6ec65b5ca4.png)

Wenn ich den Kontakt jetzt aber mit format="page" über Shortcode einbinde, fehlt dieser Text, egal ob er in einem Accordion steckt oder nicht.

URL zu der Seite, wo der Kontakt eingebunden werden soll: https://hli.cms.rrze.uni-erlangen.de/lehrstuhl/team/wissenschaftliche-mitarbeiter/

Was zur Hölle mache ich falsch? In der Beschreibung im Handbuch funktioniert's, siehe "Ausgabe wie auf der Kontakt-Einzelseite" hier: https://www.wordpress.rrze.fau.de/plugins/das-person-plugin/shortcode-uebersicht/

**Comment by xwolfde** [comment]
Also bei mir gehts
http://test8.tindu.rrze.uni-erlangen.de/tests/shortcodes/accordion-und-personen/personenseite-im-seitenmodus/

**Comment by AstridSemm** [comment]
Machst du spaßeshalber mal ne Überschrift drüber (h3)? Das Löschen hat da bei mir zwar auch nix geholfen, aber ich wüßte's halt gern genau...

**Comment by xwolfde** [comment]
hä?

**Comment by AstridSemm** [comment]
Ich verstehe halt nicht, warum das bei meinen Kirchenrechtlern nicht funzt. Es liegt mit ziemlicher Sicherheit nicht an der Überschrift, aber glauben ist was anderes als Wissen.

**Comment by xwolfde** [comment]
Es liegt wahrscheinlich daran, dass wir noch das Update einspielen müssen. An der Stelle gab es ein paar Fixes.

**Comment by AstridSemm** [comment]
Ist das Update eigentlich schon drin? Wenn ja: Es hat sich nichts geändert...

**Comment by xwolfde** [comment]
Nein, wir können derzeit keine Updates einspielen.

**Comment by endv02** [comment]
Nachdem ich den Kontakt nochmal neu angelegt habe, funktioniert der alte jetzt auch wieder... versteh einer die Welt... Ursache unklar, Fehler behoben...

**Comment by endv02** [comment]
Ha, doch noch eine Lösung gefunden! Der Kontakt wurde schon mal gelöscht und wieder neu angelegt, die ID war aber die des Kontaktes im Papierkorb. Der Content wurde korrekt gelöscht, die Plugin-Daten aber nicht, daher fiel das nicht gleich auf.
