### ISSUE TITLE
Kontakte in Menus einbindbar machen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#167]
Vgl:
https://github.com/RRZE-Webteam/FAU-Theme/issues/310 

Über Posttype Definition muss man showmenu = true setzen oder so.

**Comment by xwolfde** [comment]
Text von @pdees hierher kopiert, da Repo "FAU-Theme" geschlossen wird:

> 

Hallo,

Ich fände es gut, wenn in die Navigation auch direkt Kontakte eingebunden werden könnten und nicht nur Kontakt-Kategorien.

Hintergrund: Wir haben die für uns zuständige Teilbibliothek als Kontakt angelegt und würden diese gerne direkt aus der Navigation verlinken. Machen wir das über eine eigene Kontakt-Kategorie, heißt der Seitentiteil "Index", was irritierend sein könnte (auch wenn sich das Item in der Navigation natürlich anders benennen lässt). Und eine Seite zu bauen, die dann den Kontakt enthält, ist zwar möglich, aber irgendwie auch blöd.

P.S.: Ich habe es hier reingesetzt, weil ich das allgemeine FAU-Theme am naheliegendsten fand. Eigentlich betrifft es ja nicht das Theme direkt. Falls es die Möglichkeit doch gibt und ich sie nur übersehen habe, bin ich für einen Hinweis dankbar, ich habe länger gesucht, ob ich irgendwo noch etwas einblenden kann.

>

**Comment by endv02** [comment]
Ist drin ab Version 2.1.19
