### ISSUE TITLE
Notice: Undefined index: givenname ...

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/fau-person#168]
Notice: Undefined index: givenname in [...]/wp-content/plugins/fau-person/fau-person.php on line 232 
Master https://github.com/RRZE-Webteam/fau-person/commit/62825bc3ea68155c13db2ab58e4035270ee23107 mit WP 4.6.1

**Comment by endv02** [comment]
Wobei genau ist das aufgetreten?

**Comment by cassandre** [comment]
Seit ich die aktuelle Master-Version installiert habe, steht das bei mir oben über allen Seiten. (Bin im Debug-Modus, also WP_DEBUG und WP_DEBUG_DISPLAY sind true).

**Comment by endv02** [comment]
@cassandre: Kann das Problem nicht nachvollziehen, schließe daher das Issue. Sollte es weiterhin so sein, bitte nochmal melden.
