### ISSUE TITLE
Format-Klassen ausgeben

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/fau-person#169]
Ähnlich wie es die CSS-Klasse "compactindex" beim Parameter format="kompakt" gibt, würde ich mir das auch bei den anderen format-Darstellungen wünschen. Das umgebende div mit `<div class="person person-format-page">`, `<div class="person person-format-sidebar"` etc. 
Das hilft, die Ausgabe in anderen Themes anzupassen.

**Comment by endv02** [comment]
OK, baue ich ein.

**Comment by endv02** [comment]
ist drin ab Version 2.1.17:

- format="liste": div class="list"
- format="sidebar": div class="side"
- format="page": div class="page"
- format="kompakt": div class="compactindex"
