### ISSUE TITLE
Text-Feld wird doppelt ausgegeben

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#170]
Hallo,

das Text-Feld wird bei format="page" (und "full") zweimal ausgegeben.

Siehe: https://www.chemistry.nat.fau.eu/test-seite/

**Comment by AstridSemm** [comment]
Dazu noch zwei Probleme von der Site des Lehrstuhls für Kirchenrecht etc.:
1.) https://hli.cms.rrze.uni-erlangen.de/lehrstuhl/team/wissenschaftliche-mitarbeiter/
 -> Hier wird bei Frau Dr. Penßel der Inhalt des Textfelds gar nicht angezeigt, dafür bei Frau Haydn-Quindeau doppelt.
2.) Hier wird bei Herrn Körner der Text ebenfalls doppelt angezeigt.

**Comment by xwolfde** [comment]
Bugfix im Dev

**Comment by endv02** [comment]
Bugfix jetzt auch für Ausgaben einer Kategorie mit category= in Version 2.1.16
