### ISSUE TITLE
Überschreiben einzelner UnivIS-Daten ermöglichen

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-person#173]
Wie wäre es denn, wenn man einzelne UnivIS-Werte überschreiben könnte? Soll heißen die Werte die man in die verschiedenen Textfelder (wie etwa Abteilung, Name, etc..) einträgt werden bevorzugt und überschreiben die Default-Werte aus UnivIS.

Das wäre nützlich, um etwa falsche Daten (wie Übersetzung eines Lehrstuhlnamens) zu überschreiben und gleichzeitig etwa die Kontaktdaten immer aktuell aus UnivIS zu ziehen.

**Comment by endv02** [comment]
Das Problem an der Sache ist, dass mit dieser Möglichkeit keine Notwendigkeit mehr besteht, die Daten an der zentralen Stelle (im Moment eben noch UnivIS) aktuell zu halten, weil man dann bestehende "Fehler" ja ganz einfach "vertuschen" kann, ohne die Ursache zu beheben. Das trägt also nicht zu einer einheitlichen Datenpflege bei. Daher wurde das bewusst nicht ermöglicht.

Die erste Anlaufstelle bei fehlerhaften Ausgaben aus UnivIS wäre daher der UnivIS-Beauftragte der jeweiligen Einrichtung.
