### ISSUE TITLE
Zeilenumbruch bei Überlänge von Personeninformationen (z.B. E-Mail) - Icon und Information liegen nicht mehr gleichauf

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-person#175]
Gerade ist mir aufgefallen, dass bei Personeninformationen mit Überlänge, die Information auf eine zweite Zeile umbricht und das Icon somit alleine steht (siehe Anhang). Das betrifft jetzt nur die zweispaltige Desktop-Ansicht, auf der mobilen Ansicht ist durch das einspaltige Layout alles in Ordnung.

Das ist jetzt zwar nicht kritisch aber es sieht leider etwas ungut aus. Irgendwelche Ideen wie man das verbessern könnte? Könnte man der person-info-Klasse nicht etwas mehr Breite geben solange nur das einspaltige Layout verwendet wird (also kein Mehrlink oder Kurzbeschreibung eingeblendet wird) ?

![email](https://cloud.githubusercontent.com/assets/6545158/19019125/daf8d336-887a-11e6-92eb-cf2bedccca70.png)

**Comment by endv02** [comment]
Für die Fälle, bei denen keine dritte Spalte mit Mehrlink benötigt wird, kann der Shortcode mit format="kompakt" ergänzt werden. Dieses Format wurde unter anderem zur Lösung dieses Problems erstellt. Auf der Wiki-Seite ist von jedem Format auch ein Screenshot zu finden:
https://github.com/RRZE-Webteam/fau-person/wiki/Reihenfolge-der-Ausgabe
