### ISSUE TITLE
Telefonnummer für mobile User als entspr. tel-Link auszeichnen

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-person#176]
Wie wäre es wenn man die Telefonnummer über einen entsprechenden tel-Link als solche auszeichnet und anklickbar macht? Als weiterer kleiner Service für unsere mobilen User...

**Comment by xwolfde** [comment]
Wie sollen wir Mobile Devices erkennen? 
Das müsste via JS geschehen,welche die Bildschrimauflösung feststellt und dann nachträglich das HTML ändert. Serverseitig können wir mobile Devices nicht sicher feststellen

**Comment by csw-** [comment]
Das war ungünstig formuliert. Ich meinte generell die Telefonnummer zu verlinken.

**Comment by xwolfde** [comment]
Nee, ist schon klar. Nur ist dieser Link nur auf Smartphones sinnvoll, oder? Daher sollte der Link auch nur dann generiert werden, wenn ein Smartphone die Seite aufruft.

**Comment by csw-** [comment]
Hm ja, zumindest bei uns hier. Bei manchen Firmen hat es sich durchgesetzt Telefonate über den Rechner zu starten und man keinen Anschluss mehr am Platz hat. 
Aber ja, dann bräuchte es wohl eine JS-Lösung an dieser Stelle...
(Ich meine manche Mobile Browser erkennen Telefonnummern auch automatisch, allerdings habe ich darüber gerade keine genaueren Informationen)

**Comment by xwolfde** [comment]
in der nächsten version konfigurierbar drin
