### ISSUE TITLE
Überlänge von Personeninformationen in der Sidebar

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-person#177]
Nochmals ein Überlängenproblem. Bei einer Kollegin wurde eine etwas längere Tätigkeitsbeschreibung gewählt. Das führt in diesem Fall dazu, dass die Beschreibung unvollständig dargestellt wird (siehe Anhang)

Ich werde die Kollegen bei denen so etwas auftritt im ersten Schritt vorschlagen eine kürze Beschreibung zu wählen. Aber davon abgesehen: Wie wird das hier gehandhabt? Oder tritt der Fall einfach zu selten auf?

(Gibt es außerdem mittlerweile die Möglichkeit die Tätigkeit auszublenden?)

Die Tätigkeitsbeschreibung besteht aus 82 chars; betroffene Seite: https://www.wiso.rw.fau.de/international/internationales-profil/ 

![person-uberlange](https://cloud.githubusercontent.com/assets/6545158/19111306/3567e524-8aff-11e6-9973-ea70603eb33d.png)
![person-uberlange-2](https://cloud.githubusercontent.com/assets/6545158/19111308/385e3dc8-8aff-11e6-8d00-64755d06589f.png)

**Comment by endv02** [comment]
Ich hab das jetzt mal bei FAU-EInrichtungen eingetragen, das liegt vermutlich am Styling.

**Comment by endv02** [comment]
Hab mir die Seite mit dem Fehler jetzt nochmal angesehen: Sie haben über den Shortcode die Kontakte in der Sidebar eingegeben. Hierzu müssen Sie im Shortcode format="sidebar" verwenden, dann wird der Text auch richtig umgebrochen. Ich habe das auf Ihrer Seite noch nicht angepasst, weil dann auch das Bild angezeigt wird und ich weiß nicht, ob das erwünscht ist. 
Im Normalfall können auch alle Felder einzeln über show bzw. hide angezeigt werden, in dem man den Namen des Feldes verwendet (bei der Position z.B. hide="position"). Eine Übersicht darüber ist auf der Seite [https://www.wordpress.rrze.fau.de/files/2016/06/Zusammenfassung-Shortcode-kontakt.pdf](https://www.wordpress.rrze.fau.de/files/2016/06/Zusammenfassung-Shortcode-kontakt.pdf) zu finden

**Comment by csw-** [comment]
Alles klar, dann machen wir das so. Es gab da nur das Problem das man in Verbindung mit format nur bedingt show/hide auswählen konnte. Wenn das jetzt geht, dann setze ich das entsprechend um.
Sehen Sie hierzu bitte auch meinen Kommentar unter https://github.com/RRZE-Webteam/fau-person/issues/162#issuecomment-242907434
