### ISSUE TITLE
format=page zeigt Name nicht an

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#178]
Bei format="page" bzw. format="full" wird der Name der Person nicht mehr angezeigt. 

Siehe z. B.: https://www.chemistry.nat.fau.eu/burzlaff-group/

**Comment by xwolfde** [comment]
Das ist Absicht. 
Aus vielen Diskussionen wissen wir, dass  einige Leute im "Titel" des Personeneintrags etwas anders stehen haben als den richtigen Namen. Daher muss man auch die Möglichkeiten haben, eine eigene Überschrift zu setzen.
Die tut man dann eben vor dem Shortcode.

**Comment by xwolfde** [comment]
Siehe übrigens auch hier:
"
Name wird jetzt standardmäßig ausgeblendet (ist ja im Normalfall eh schon auf der Kontaktseite in der Überschrift), bei Verwendung vom Shortcode kann er mit show="name" angezeigt werden ab Version 2.1.16
"
https://github.com/RRZE-Webteam/fau-person/issues/163

**Comment by cibsell** [comment]
Danke für die Dokumentation.

**Comment by xwolfde** [comment]
@endv02 Christine hat recht. Wo ist eigentlich der Blogeintrag zum Update?  Hier sehe ich keinen https://blogs.fau.de/webworking/ ?

**Comment by endv02** [comment]
Wollte ich erst zusammen mit der nächsten Version reinstellen, wo mehr sichtbare Änderungen reinkommen. Dann krank, sorry...

**Comment by cibsell** [comment]
Der Name wird auf der Kontaktseite auch nicht mehr angezeigt, ist das wirklich so gewollt? Das bedeutet nämlich, dass wir bei ca. 450 angelegten Kontakten den Seitentitel in "Prof. Dr. ...", "Dr. ..." etc. ändern müssen. Ich dachte, es gibt dafür das Dropdown-Menü, das die Arbeit etwas erleichtern soll, weil der Titel eben bei der Ausgabe des Namens automatisch hinzugefügt wird? 

Zudem: Der Abstand zwischen Seitentitel und Kontaktdaten ist auch recht groß, das wirkt unübersichtlich, wenn bei den Konktaktdaten der Name (inkl. Präfix) nicht mehr dabei steht.

Und weiteres: Wenn die Kontakte nach Titeln sortiert werden (?), hat man dann x "Prof. Dr." und "Dr." etc. in der Sortierung stehen statt die Namen.

**Comment by xwolfde** [comment]
Der Einwand ist richtig und sollte diskutiuert werden.

Was allerdings auch blöd ausschaut ist (und semantisch nicht korrekt), wenn der Name verdoppelt wird.
Nämlich einmal in der Überschrift oben (farbiger Balken) und dann im Contentteil.

Vorbild bei der Gestaltung der Personenseiten sind die Personenseiten der FAU. Bspw:
https://www.fau.de/universitaet/leitung-und-struktur/leitung/prof-dr-joachim-hornegger-praesident/

Hier haben wir als erstes nach dem Seitentitel (im blau) nicht den Namen, sondern die Funktion.
Man kann da aber auch den Namen reintun.

Vgl. Beispielseiten
http://test8.tindu.rrze.uni-erlangen.de/person/wolfgang-wiese/
http://test8.tindu.rrze.uni-erlangen.de/person/karin-kimpan-rrze/

Aber hm... jetzt wundere ich mich etwas...  Was ist das denn für ne Seite überhaupt?
https://www.chemistry.nat.fau.eu/burzlaff-group/
Das ist ja gar keine Personenseite??! Das ist eine Seite mit einem Shortcode, oder?
Sorry, aber dazu hab ich doch oben gesagt: Titel manuell drüber setzen und Karin hat auch gesagt das Attribut setzen.

Wenn wir von Kontaktseiten reden, meinen wir die Seiten der Kontakte. Nicht manuell gemachte Seiten mit einem Shortcode. Bitte nicht verwirren :) 

Der Abstand der Überschriften bei der KOntakltseite ist voll in Ordnung. Siehe
http://test8.tindu.rrze.uni-erlangen.de/person/wolfgang-wiese/

**Comment by cibsell** [comment]
Stimmt, die Gruppenseite benutzt einen Shortcode. Aber z. B. hier: https://www.chemie.nat.fau.de/person/nicolai-burzlaff/ Da fehlt der Name auf der Kontaktseite. Er steht nur im Seitentitel und hier ohne Präfix. Auf Deiner Seite ist alles vorhanden, wo ist also der Fehler? Im Kontakt-Eingabeformular kann ich doch nicht mehr eintragen als bei Seitentitel und Name + Vorname, oder?

Bzw. siehe auch hier: https://www.chemie.nat.fau.de/person/stefanie-karosi/  Da geht der Name unter, weil die Funktion fett hervorgehoben wird. Der Seitentitel wird möglicherweise überlesen, weil man sich bei längerem Besuch der Seite sogleich auf den Contentbereich konzentriert und den "grünen Deko-Balken" ausblendet.

**Comment by endv02** [comment]
Wolfgangs Testinstanz hat wohl nicht die neueste Version des Personen-Plugins, deshalb ist der Name noch da. 

Aber ansonsten stimmt das, da ist wohl mehr Diskussionsbedarf als ich gedacht hätte. Für mich stand auf den Personenseiten eher einmal zu viel der Name da, wenn er schon in der Überschrift steht und dann darunter nochmal. Deswegen schien mir die Anpassung auch keine so gravierende Auswirkung zu haben, sorry. Gewünscht war das ganze ja aufgrund des Shortcodes in den Texten, wo oft eine andere Überschrift oder Überschriftengröße gewünscht war (z.B. in Accordions), dann der Name gleich darunter einfach als doppelt und störend empfunden wurde.

Die Überlegung wäre dann, den doppelten Namen defaultmäßig bei den Einzelkontaktseiten drin zu lassen? Nur zusätzlich anzeigen zu lassen, wenn tatsächlich ein Titel oder ein Suffix vorhanden sind und die Felder Vor- und Nachname gefüllt sind? Nur dann wird der Unterschied sichtbar, bei https://www.chemistry.nat.fau.eu/person/birgit-haltrich/ wäre z.B. einfach der gleiche Name gleich unter dem Seitentitel nochmal vorhanden, das ist doch auch eher unüblich, so wie wenn die h1- und die h2-Überschrift direkt untereinander absolut identisch wären...

Also, was nun?

**Comment by FlorianFiller** [comment]
Ich finde die "Doppelung" des Namens schöner und auch übersichtlicher - und die Titel würden sich automatisch aus UnivIS generieren.

Auf der FAU-Seite sind im Übrigen auch solche "Doppelungen" vorhanden, bspw.:
https://www.fau.de/universitaet/leitung-und-struktur/leitung/prof-dr-friedrich-paulsen/
M.E. (auch semantisch) problemlos.

**Comment by xwolfde** [comment]
Ah, das erklärt es.

Der Name macht ja nur dann eine Doppelung, wenn der Titel des Eintrags identisch ist mit Vorname+Nachname +Titel.
Es ist aber oft so, daß man genau das nicht hat, da man z.B. bei der Übersicht der Kontakte eine andere Sortierung oder andere Einordnung will.
Von daher ist der Name IMHO schon wichtig. Zudem sollten wir das Argument SEO auch betrachten: Es istw ichtig, dass man einen anderen Seitentitel geben kann als beim Content. 

tl;dr: Ich würde es wieder gern rein haben. Aber ggf. dann die Option mit hide="name"  oder so.
Wäre schön, wenn die Änderung vorher länger testbar gewesen wäre...

**Comment by endv02** [comment]
Ok, dann kommt es einfach wieder rein mit optional hide="name". Wie gesagt sah ich die Auswirkungen nicht als so gravierend an, dass eine längere Testzeit nötig wäre. Mit dem nächsten Update wieder drin.
