### ISSUE TITLE
Anzeige der neutralen Personenbilder

### ISSUE THREAD

**Issue by xy23vaja** [RRZE-Webteam/fau-person#179]
die automatische Anzeige der neutralen Personenbilder, wie im Benutzerhandbuch	
 beschrieben, wird leider noch nicht dargestellt. Einstellungen unter; Zusatzoptionen, Typ des Eintrags, Pulldown Menü = Person (allgemein, männlich, weiblich) usw. wird leider noch nicht dargestellt.

Auf dieser Seite wurde das Bild als Beitragsbild eingefügt, das funktioniert
https://www.wordpress.rrze.fau.de/person/martha-musterfrau/

**Comment by endv02** [comment]
Die neutralen Bilder werden immer nur bei Formaten angezeigt, bei denen auch eine Bildausgabe dabei ist. Übersicht über alle Ausgaben steht hier: https://www.wordpress.rrze.fau.de/files/2016/06/Zusammenfassung-Shortcode-kontakt.pdf
