### ISSUE TITLE
Weiße Seite nach Installation II

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#18]
Geht leider immer noch nicht.

**Comment by endv02** [comment]
Bitte beim FAU_Themes -> Theme Options -> Erweitert -> den Haken bei "Nutze alte Personen- und Adressverwaltung aus dem FAU-Plugin" entfernen, sonst wird der gleiche CPT zweimal geladen (ist auf jeden Fall in der letzten FAU_Theme Version möglich)

**Comment by cibsell** [comment]
Das habe ich nun gemacht, löst leider immer noch nicht das Problem.

**Comment by endv02** [comment]
Schlecht... Wann genau kommt die weiße Seite? Nach der Aktivierung oder wann anders? Funktioniert es evtl. mit einem anderen Theme? Mit deaktiviertem FAU-Plugin? Php-Version mindestens 5.3, WordPress mindestens 4.0.

**Comment by endv02** [comment]
Hab noch ein bisschen getestet und nachgeforscht, mit aktiviertem Debug-Modus habe ich auch eine Fehlermeldung bekommen. Liegt am gleichzeitig aktivierten FAU-Plugin, sind beide momentan noch nicht wirklich kompatibel, d.h. bitte versuchen, ob es ohne aktiviertes FAU-Plugin geht.

**Comment by cibsell** [comment]
Mit deaktiviertem FAU-Plugin funktioniert es. PHP-Version 5.5.36, Wordpress 4.1.1 de.

**Comment by endv02** [comment]
Na wenigstens etwas... Wir arbeiten noch an einer Lösung, dass es parallel zum FAU-Plugin läuft.

**Comment by endv02** [comment]
Haben jetzt beschlossen, den gleichzeitigen Einsatz von FAU-Plugin und fau-person zu umgehen. fau-person soll relativ zeitnah das FAU-Plugin ersetzen.
