### ISSUE TITLE
Geänderte Univis-Daten wann sichtbar?

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#180]
Ein Redakteur hat in Univis eine Raumangabe geändert und sich gewundert, dass die Aktualisierung im Plugin bei der Person nicht übernommen wurde. Wie lange dauert es, bis die Univis-Daten in Wordpress aktualisiert werden?

**Comment by xwolfde** [comment]
Ha! Mehrere Leute gleichzeitig mit denselben Fragen.

@AstridSemm Kannst du bitte in der Doku eine neue Seite anlegen, in der wir eine Übersicht aller möglichen Cache-Zeiten auflisten?
In Frage kommende Caches gibt es bei:
- RRZE Calendar
- UnivIS Plugin
- CRIS Plugin
- FAU Person bei UnivIS-Importen
- ggf. SuperCache Plugin


Cache-Zeiten am Besten über @rvdforst , @endv02  und @cassandre  erfragen oder dem Code entnehmen :P

**Comment by AstridSemm** [comment]
Ja, kann ich - auch wenn das natürlich von den Betreuern anderer Server abhängig ist und sich hier und da ändern kann. Kommt auf die ToDo-Liste.

**Comment by MaStFAU** [comment]
Hat es diese Info in irgendeine Dokumentation geschafft? Wie lange dauert es denn jetzt bis Daten z.B. aus UniVis in Wordpress ankommen?

**Comment by AstridSemm** [comment]
Nein, noch nicht, deswegen ist der issue ja noch offen.
Bei UnivIS dauert es üblicherweise maximal 24 - es sei denn der Browser des Anwenders cachet länger, dann muss man da etwas tun.

**Comment by MaStFAU** [comment]
Alles klar, danke für die Info
