### ISSUE TITLE
Verknüpfte Kontakte: Anzeige in der Sidebar glätten

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/fau-person#181]
Die verknüpften Kontakte in der Sidebar funktionieren nun (an Stelle des Shortcodes im Freitextfeld), aber die Anzeige sollte noch etwas opitimiert werden. Unten die Darstellung auf https://www.fau.de/patente-gruendung-wissenstransfer/service-fuer-unternehmen/werbung-und-recruiting/

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/19677648/8ff7dbca-9a9a-11e6-9648-d32d4a4232a5.PNG)

Das Häkchen ist zu nah am Kontakt, siehe im Vergleich https://www.fau.de/graduiertenzentrum/

Einen Vergleich aller möglichen Anzeigeoptionen habe ich noch nicht, vielleicht ist es ja nur das Häkchen :)

**Comment by endv02** [comment]
Also da passt insgesamt wohl noch was nicht, die Adresse müsste auf jeden Fall umgebrochen werden in der Sidebar. Ich werd das nochmal genau anschauen.

**Comment by xwolfde** [comment]
Interessante Verwendung dort.
Hier wird nicht der Kontakt Recruting ausgegeben, sondern die verknüpften Kontakte. 
Diese werden jetzt wiedere als SUbliste der Subliste des Pseodokontakts dargestellt.

Das ist für die Sidebar gar nicht so vorgesehen gewesen.
Die verknüpftzen Kontakte sind dazu gedacht als z:b. Sekretariat für Personen auf deren Personenprofilseite angezeigt zu werden. Nicht zur Anzeige in der Sidebar!

Was hier von der Webredaktion gewollt wird, ist es, wei Personen in der Sitebar unter einem Titel anzuzeigen.
Das ist über die herkömmlichen Wege (z.B. 2 Shortcodes für die beiden personen oder über die Auswahlfunktion) möglich und dann sieht es auch richtig aus.

Ich würde jetzt für diese unvorhergesehene und damit falsche Bedienung keinen Workaround bauen. jedenfalls nicht mit Prio.

**Comment by wrkb** [comment]
Ah oh, das ist aber schade, weil eine sehr schöne Funktion. Aber ja, es ist nicht oberste Prio.

Du würdest übrigens lachen, selbst mit dieser Variante erschlagen wir noch nicht alle Bedarfe hier, wenn ein Referatskontakt mit verschiedenen Personen besetzt werden soll auf einer Seite, aber auf einer anderen Seite ein anderer Kontaktmix, wobei dann andere Funktionen dran stehen sollen...

Wir arbeiten grade daran, hier auf Pragmatismus zu drängen, und sei es nur über einen zweiten UnivIS-Eintrag für Leute mit mehreren getrennten Aufgaben. Denn noch komplexer muss das Plugin nicht werden...

**Comment by endv02** [comment]
Meinst Du mit zweitem UnivIS-Eintrag, dass die Person in UnivIS komplett neu nochmal angelegt werden soll? Das ist aber genau das, was wir nicht wollen, weil dadurch die gleiche Person auch bei den Kontakten zweimal angelegt werden müsste!

**Comment by xwolfde** [comment]
Ich würde euch eher vorschlagen, bei Servicestellen in der Sidebar grundsätzlich KEINE echten Personen namentlich aufzuführen, sondern dort immer nur neutrale Pseudoeinträge gemäß Orgastruktur zu führen. Also z.B. Nennung der Referats X.
Die Personen kann man dann auf den jeweiligen Serviceinfoseiten im Contentbereich aufführen.

Der Vorteil: Bei Personalwechsel müsst ihr da nicht andauernd nachpflegen und die Sidebars bleiben also lange gleich.

**Comment by wrkb** [comment]
Es gibt ja Zweiteinträge in UnivIS, die auch über die Suche im Plugin im Backend angezeigt werden (richtig?) - z.B. Präsident. Aber ja, das wären Dubletten im Backend. Aber was macht man denn sonst, wenn jemand zum einen Referatsleiter und zum anderen Behindertenbeauftragter ist? Das lässt sich nur über Dubletten lösen oder - besser - über einen manuellen Kontakt mit verknüpftem Kontakt. Aber letzter ist bei uns nach diversen Wünschen nicht auf jeder Seite gleich.

Ich tendiere tatsächlich eher zu Wolfgangs Lösung - im Content sind wir flexibel genug, in der Sidebar nicht. Ist ja auch ein Lernzprozess grade.

**Comment by xwolfde** [comment]
Zweiteinträge für Personen im UnivIS sind definitiv falsch und würden auch bei anderen Systemen zu gravierenden Problemen führen...   In UnivIS muss man Personen, die bereits vorhanden sind, verknüpfen.
Dann stimmt nämlich auch die Personen-ID.
Wer da neu anlegt und Dupletten erzeugt, provoziert Probleme bei der korrekten Zuordnung von Lehrveranstaltungen, Publikationen, etc. Also ein richtiger Griff ins Klo :)   
Theoretisch müsste die UnivIS-Beauftragte für solche Fälle einen eigenen dornengespickten Knüppel als Lehrinstrument bekommen. >:)

**Comment by wrkb** [comment]
Ja, okay, ich brachte da tatsächlich etwas durcheinander. Dubletten sind nicht, was wir wollen. Man kann ja mehrere Funktionen/Zugehörigkeiten innerhalb seiner Organisation festlegen, aber ob sich das über die Schnittstelle ansprechen lässt, weiß ich nicht - es macht aber auch alles komplizierter...
![unbenannt](https://cloud.githubusercontent.com/assets/9445370/19727931/bc300012-9b91-11e6-8fd9-7a3a38b71b34.jpg)

**Comment by xwolfde** [comment]
Das wurde auch in der neuen Version gefixt
