### ISSUE TITLE
Kontaktübersicht: Kontakte sortieren

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#182]
Alle Kontakte haben ja in der Breadcrumb einen Link auf "Kontakt".
![bildschirmfoto 2016-12-01 um 16 15 29](https://cloud.githubusercontent.com/assets/11296947/20799085/6a3bf9fc-b7e1-11e6-9ef0-c70d6aef829d.png)

Dieser Link führt auf eine (inzwischen viel schönere) Übersicht über alle Kontakte, die aber in der Reihenfolge des Anlegens sortiert ist. Damit ist also der zuletzt angelegte Kontakt oben. Das finden nun doch einige Kunden sehr unpraktisch und möchten gern ihre Kontaktseiten sortieren können (zB ganz oben den Lehrstuhlinhaber, danach wissenschaftliches Personal, etc. etc.). 

Diese Sortierung sollte dann bald möglich gemacht werden, denn dem einen Kunden wurde das schon im August zugesagt (siehe auch OTRS).

**Comment by endv02** [comment]
Mit der Version 2.2.0 ist die Möglichkeit vorhanden, die Kontakt-Seite aus der Breadcrumb-Navigation durch eine eigenen Seite zu ersetzen. Hier kann man auch die Sortierung über Shortcode-Parameter beeinflussen. Die alphabetische Sortierung in Kategorienausgaben wird erst in der nächsten Version kommen.
