### ISSUE TITLE
Kontakte erscheinen, obwohl nur als Entwurf gespeichert (und mit Daten, die nicht in UnivIS stehen)

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/fau-person#184]
Wir haben sowohl auf fau.de als auch auf fau.eu eine Personenvisitenkarte einer Person angelegt, (Daten kommen aus UnivIS), aber unterschiedliche Telefonnummern auf den zwei Sites (Telefonnummer wurde kürzlich geändert). 
Auf fau.eu wird zudem der Kontakt angezeigt, obwohl er nur auf "Entwurf" steht?! (was eigentlich im Moment ganz gut ist, weil es keinen zweiten "Live"-Kontakt gibt.)

Hier die Screenshots der ganzen Einstellungen...

<img width="527" alt="kontakt als entwurf" src="https://cloud.githubusercontent.com/assets/9526974/21004015/9cae66fc-bd2e-11e6-8f45-aaa969399de5.png">
<img width="505" alt="kontakt eingefugt im backend" src="https://cloud.githubusercontent.com/assets/9526974/21004036/b03a5e38-bd2e-11e6-8fd7-366340a6870d.png">
<img width="738" alt="kontakt im frontend sichtbar" src="https://cloud.githubusercontent.com/assets/9526974/21004035/b03a6d60-bd2e-11e6-9937-60434a51ba97.png">
<img width="589" alt="univis-eintrag" src="https://cloud.githubusercontent.com/assets/9526974/21004080/e3f453dc-bd2e-11e6-97ed-c06ad2c00cb3.png">

**Comment by endv02** [comment]
Wahrscheinlich hat es durch den Cache etwas gedauert, bis beide Kontakte aktualisiert waren. Jetzt ist es aber ok. Zu dem anderen Problem gibt es schon ein Issue.
