### ISSUE TITLE
Definition Länge der Kurzbeschreibung/Zeichenanzahl

### ISSUE THREAD

**Issue by xy23vaja** [RRZE-Webteam/fau-person#185]
Meine Frage bezieht sich auf das zählen der Zeichen.
Wenn in der Kurzbeschreibung in Listenansicht (bis zu 400 Zeichen) steht, werden bei der Zählung die Leerzeichen mitgerechnet? 
Beispiel / FAU Person neue Einrichtung? / Kurzbeschreibung Listenansicht

**Comment by xy23vaja** [comment]
unter: Fau Person /neuer Standort ; Textfeld Auszug: gibt es (noch:) keine maximale Zeichenanzahl

**Comment by xwolfde** [comment]
Leerzeichen werden immer mitgezählt. Sind ja auch Zeichen.
