### ISSUE TITLE
Sprechzeiten: 12 AM und PM vertauscht, Angabe "Uhr" fehlt

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/fau-person#189]
Wähle ich korrekterweise bei der Eingabe von 12 Uhr mittags 12 PM aus, wird 24 Uhr ausgegeben. Workaround ist das - falsche - Angeben von 12 AM.

Bei der Ausgabe fehlt das Wort "Uhr", dafür ist ein Komma an der Stelle (siehe Screenshot).

Bei einem Update wäre eine Nachricht nett, da wir dann die Angaben wieder ins Lot bringen müssen (da manuell korrigiert).

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/23461059/83d0452e-fe88-11e6-8f3b-27c5534ba7d4.JPG)

**Comment by wrkb** [comment]
Link via PM im Chat @endv02

**Comment by endv02** [comment]
Das Uhr bleibt weg, das macht die internationale Ausgabe einfacher und ist in UnivIS auch nicht drin.

**Comment by endv02** [comment]
Und der Fehler mit AM - PM sollte auch schon korrigiert sein, also schließe ich das Issue.
