### ISSUE TITLE
Suche: Veröffentliche Personen durchsuchen und ausgeben (separate Gliederung in der Such-Ausgabe)

### ISSUE THREAD

**Issue by ghost** [RRZE-Webteam/fau-person#19]
...das hatte ich angelegt auf deinen Hinweis/Wunsch hin, Wolfgang :) Wir brauchen es nicht wirklich, es könnte aber hilfreich sein.
Du meintest, dass bei den Fakultäten alle angelegten und öffentlich sichtbaren Personenvisitenkarten auch in der Suche ausgegeben werden sollen. Das ist hiermit gemeint.

Da wir die Sucheregebnisse ja auch noch optisch trennen wollen in einem weiteren Schritt, wäre hier mein Vorschlag, auch die Personen noch in eine (derzeit vierte) Schublade (oder was auch immer) zu packen - also neben Seiten, Meldungen (Beiträgen), Veranstaltungen.

Für fau.de ist das alles nicht dringend, wir haben bislang keine Rückmeldung von irgendwen, dass er namentlich gefunden werden soll/muss. Sollte UnivIS aber irgendwann wirklich mal nichtöffentlich sein, könnte uns das natürlich helfen.
@wrcg

**Comment by xwolfde** [comment]
schon seit längerem umgesetzt
