### ISSUE TITLE
Sprechzeiten: Nach Vereinbarung

### ISSUE THREAD

**Issue by pdees** [RRZE-Webteam/fau-person#190]
In der neuen Verknüpfung zwischen den Sprechzeiten und Univis scheint es einen Bug zu geben: Wenn in Univis z.B. ein Raum, aber keine Zeit eingetragen ist, setzt Univis automatisch ein "Nach Vereinbarung". fau-person gibt aber nur das belegte Feld, ohne den Zusatz "Nach Vereinbarung" aus, in unserem Fall gefolgt von einem Komma. Siehe auch Screenshot im Anhang.

Außerdem wäre ein Abstand vor dem Block mit der Sprechstunde ganz hübsch.

![screenshot_bahadir](https://cloud.githubusercontent.com/assets/17905415/23616064/ca24ab42-0288-11e7-8890-e32ceff3f537.jpg)

**Comment by xwolfde** [comment]
fixed mit der nächsten Version
