### ISSUE TITLE
Sprechstunden: Sprachversion

### ISSUE THREAD

**Issue by pdees** [RRZE-Webteam/fau-person#191]
Für die Sprechstunden-Felder scheint es keine englische Sprachversion (en-UK) zu geben, diese sollte ergänzt werden.

![screenshot_schliack](https://cloud.githubusercontent.com/assets/17905415/23616776/24d8056e-028b-11e7-8718-96cfd5911d45.jpg)

**Comment by xwolfde** [comment]
In der nächsten Version
