### ISSUE TITLE
Änderungsvorschau bei Konakten funtioniert nicht

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/fau-person#192]
Bei Seiten und Beiträgen kann man sich die Änderungen anzeigen lassen, ohne das Objekt zu speichern. Das funktioniert bei Kontakten leider nicht. Änderungen werden erst nach der Aktualisierung sichtbar.

**Comment by endv02** [comment]
Wird aber der nächsten Version korrigiert sein.
