### ISSUE TITLE
Anzeige Kategorie mit Format Liste

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#193]
Beispielseite: https://www.alfirin.test.rrze.uni-erlangen.de/kontaktetest/

Mit dem shortcode "kontakt category="Testkategorie" format="liste" wird zwar die Liste ausgegeben, aber auch versucht, die Daten aus dem Accordion einer Kontaktseite auszugeben. Offensichtlich werden hier aber die shortcodes aus dem Freitextfeld, in das viele Leute ihren Lebenslauf schreiben, nicht interpretiert, was darin endet, dass der "Rohtext" ausgegeben wird. Das kann ja so auch nicht im Sinne des Erfinders sein.

**Comment by endv02** [comment]
Das Problem liegt hier woanders: das Format "Liste" verwendet den Excerpt, in diesem Fall den Inhalt des Kurzbeschreibungsfeldes. Wenn dieses leer ist, generiert es einfach einen Auszug aus dem Inhaltsbereich. Und der Auszug schmeißt automatisch alle Formatierungen weg. Wenn man also die Ausgabe von "Rohtext" vermeiden will, am besten sinnigen Text in das Feld Kurzbeschreibung eintragen.
