### ISSUE TITLE
Hinterlegung CRIS-ID / IDM-Key möglich (optional)?

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/fau-person#194]
Kann man bei den Kontaktdaten als interne Information die CRIS-ID der Person hinterlegen und zusätzlich die IDM-Kennung?

Das würde in der Zukunft das Matching von Personen erleichtern (siehe auch https://github.com/RRZE-Webteam/fau-cris/issues/85#issuecomment-299196291).

**Comment by endv02** [comment]
Ist zumindest in Zukunft mal angedacht. Aktuelle Priorität ist aber leider ganz weit unten.

**Comment by xwolfde** [comment]
CRIS-ID und somit Import der Daten hat eine hohe Bedeutung

**Comment by xwolfde** [comment]
Hier obsolet. Im neuen FAUdir Plugin wird das neu angegangen. Da dort eine Anbindung an DIP gemacht wird, wird es dort bessere Optionen geben.
