### ISSUE TITLE
Anzeigeoption für zweite Mailadresse

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/fau-person#195]
Anzeigemöglichkeit einer weiteren Mailadresse schaffen.
In UnivIS sind bei einigen Personen mehrere Mailadressen hinterlegt. Bis jetzt wird nur die erste Adresse übernommen. Gerade für die Anzeige von Abteilungs/Sammelmailadressen, die häufig als zweite Mailadresse in UnivIS stehen, ist dies sinnvoll.

**Comment by xwolfde** [comment]
Dies kann man über die Ansprechpartnerfunktionalität erledigen.

Dort kann und sollte man für Ansprechpartner-Sammeladressen einen eigenen Kontakt anlegen.
Dann kan man diesen mit dem Personenkontakt verknüpfen-.
