### ISSUE TITLE
Ausgabe der Sprechstunden korrigieren

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#196]
Bei der Ausgabe der Sprechstunden sind einige Kommas zuviel und einige Umbrüche zuwenig:
![bildschirmfoto 2017-05-17 um 12 26 45](https://cloud.githubusercontent.com/assets/11296947/26149885/5cbfdaa2-3afc-11e7-8975-69936c7d07bf.png)

Besser wäre:

Jede Woche Mo, Mi
09:00 - 13:00 (hier fehlt noch "Uhr", dazu gibt's aber schon einen issue)
Raum 3.105

**Comment by endv02** [comment]
Das Uhr wird es nicht geben, ist bei UnivIS selber auch nicht drin und würde zu Problemen bei anderen Sprachen führen. Die Umbrüche sind auch nicht machbar, da die Ausgaben zu beliebig variieren können und das so nie sicher ist, ob die Umbrüche dann doch zu einer schönen Darstellung führen. Aber das mit den Kommas wird korrigiert.
![person](https://cloud.githubusercontent.com/assets/5851793/26195989/cb5474c0-3bbd-11e7-83cd-301f85769acd.png)

**Comment by AstridSemm** [comment]
Na, immerhin: Ein Drittel. ;o)
Danke, Karin.
