### ISSUE TITLE
Bilder bei Kontakten sind unscharf

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/fau-person#199]
Auf der Seite https://www.fau.de/presseportal-der-fau/kontakt/ sind die Bilder bei den Personen z.T. unscharf sind? Auf den Detailseiten sind sie z.T. auch unscharf.
Auf der Seite https://www.fau.de/graduiertenzentrum/ueber-uns/ dagegen sind dagegen alle Bilder scharf.
Die Bilder auf der Presseseite sind neuer, waren aber auch schon mal deutlicher/schärfer.

**Comment by wrcg** [comment]
vielleicht hilft das?: 
https://die-netzialisten.de/wordpress/unscharfe-beitragsbilder-nachschaerfen

**Comment by endv02** [comment]
Gab keine Beschwerden mehr, daher schließe ich das Issue
