### ISSUE TITLE
Darstellungsprobleme mit format=page

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#200]
Im letzten Update des Plugins haben sich leider Fehler eingeschlichen.

 1.   Fehler bei der Darstellung von Kontakten mit dem Format "page" innerhalb von Accordions.
    Dieser Fehler macht sich dann bemerkbar, wenn der Shortcode [[kontakt]] mit dem Parameter format="page" innerhalb von Accordions verwendet wird.
    Das Accordion wird dabei vorzeitig nach dem Shortcode geschlossen, so dass darauf folgende Shortcodes des Kontakte-Plugins nicht korrekt dargestellt werden. Wir bitten bis zur Behebung des Fehlers (aber auch unabhängig davon) innerhalb von Accordions auf die Verwendung des Formats format="page" zu verzichten.
2.  Fehlerhafte Darstellung von Bildunterschriften.
    Ebenfalls bei der Verwendung von "format=page" kann es zu der falschen Anzeige von Bildunterschriften kommen. Dieses tritt unter folgenden Konstalltion ein:
        a) der Shortcode wird mit dem Parameter format="page" verwendet,
        b) als Artikelbild des Kontaktes ist ein Bild angegeben,
        c) als Artikelbild für die Seite, in dem der Shortcode angegeben, wird ein weiteres, aber  anderes Bild verwendet.

    In diesem Fall wird die Bildbeschreibung (bzw. die IPC-Info) des Bildes Artikelbildes der Seite angezeigt, jedoch das Bild zum Kontakt.

**Comment by endv02** [comment]
Gibt es ein Beispiel zu 1.?

**Comment by xwolfde** [comment]
Nur wenn du es nachbaust. Bei der Kundenwebsite wurde es ja weggemacht.

**Comment by endv02** [comment]
Ich kriege es eben nicht reproduziert: https://www.beta.wordpress.rrze.fau.de/plugins/accordion-und-personen/
Das Accoridion mit Personen format page

**Comment by endv02** [comment]
1. funktioniert bei mir
2. wird mit Version 2.6.3 behoben sein
