### ISSUE TITLE
Übersetzungsfeld für spezielle Tätigkeit (aus UnivIS) finden

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/fau-person#201]
das Feld „Spezielle Tätigkeit“ (nur auf Deutsch verfügbar) soll nicht mehr als Füller für das Attribut „position“ dienen, sondern dass position sich aus… irgendwas anderem speist, das muss angepasst werden.
 
Ich weiß nicht, ob jemand außerhalb der ZUV das Feld „Spezielle Tätigkeit“ für die Visitenkarten nutzt – das haben wir damals hier so gemacht. Falls nicht, entsteht nicht mal Schaden durch eine Umstellung.

**Comment by xwolfde** [comment]
erstmal nicht. ggf. in zusammenhand mit Overwrites für UnivIS-Werte
