### ISSUE TITLE
Kontakt ID wird doppelt dargestellt auf Übersichtsseite

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#202]
Auf der Übersichtsseite aller Kontakte wird beim NAT-Webauftritt die ID des Kontakts in der Spalte "Nr." doppelt dargestellt, z. B. : statt 187521 wird die Zahl doppelt geschrieben: 187521187521

**Comment by mduven** [comment]
Das ist mir bei mehreren unserer Seiten auch schon aufgefallen, z.B. https://www.wiso.rw.fau.de/ und https://www.wiso.rw.fau.eu/, https://www.rw.fau.de/

**Comment by endv02** [comment]
War wohl ein Konflikt mit einem anderen Plugin, scheint jetzt nicht mehr aufzutauchen.
