### ISSUE TITLE
Extra <span class="fullname"> um Vorname und Nachname

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#203]
Damit bei langen Namen die Zeilentrennung besser gesteuert werden kann, bitte noch eine gesonderte &lt;span&gt; einbauen um den Teil des Namens ohne Titel.

Aktuell ist so:
` <span itemprop="name"><span itemprop="honorificPrefix">Dr.</span> <span itemprop="givenName">Karin</span> <span itemprop="familyName">Musterfrau</span>, <span itemprop="honorificSuffix">MA</span></span>`

Bitte dann so:
` <span itemprop="name"><span itemprop="honorificPrefix">Dr.</span> <span class="fullname"><span itemprop="givenName">Karin</span> <span itemprop="familyName">Musterfrau</span></span>, <span itemprop="honorificSuffix">MA</span></span>`

**Comment by endv02** [comment]
Ist drin ab Version 2.5.0
