### ISSUE TITLE
Neues Attribut hstart

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#204]
Bitte im Shortcode ein Attribut hstart einfügen, welches als Wert eine Zahl 1 bis 5 annimmt.
Wenn keine Zahl angegeben wurde oder das Attribut nicht gesetzt wurde, ist die 3 Default.

Dies soll die Überschrift ansteuerbar machen, die bei der Ausgabe der Person als erste verwendete Überschrift (aktuell ist es die h3) verwendet wird.
Wenn hstart=2 soll es mit &lth2&gt; losgehen etc..

In dem Zuge bitte die aktuelle h3- Überschrift bei den weiteren Verknüpften Kontakten jeweils eine Stufe kleiner setzen als die erste Überschrift. Die ist dann also bei hstart=2   eine h3. Denn diese Überschrift ist schließlich hierarchisch "unter" der Hauptüberschrift.

**Comment by endv02** [comment]
aktuell haben wir folgende Situation:
- Standard-Format: Name mit <h3>
- Einzelkontaktseite (format page, nur wenn Namensanzeige gewünscht): Name mit <h2>
- Sidebar über Widget: wenn ein Widget-Titel vergeben ist, erscheint dieser mit <h2>
- Sidebar generell: Name mit <h3>
- verknüpfte Kontakte: Verknüpfungstext (z.B. Kontakt über) mit <h3>, die Namen werden über das Standard-Format ausgegeben, als auch wieder mit <h3>

**Comment by xwolfde** [comment]
Ja. die defaults können gern so bleiben (abwärtscompatibel), aber es sollte auch die möglichkeit geben, es gezielt anzugeben

**Comment by endv02** [comment]
Bei page auch eine Anpassung oder fest?

**Comment by xwolfde** [comment]
öhm... Überlass ich dein Gefühl und Erfahrung mit Kunden

**Comment by endv02** [comment]
Ist drin ab Version 2.5.0 für Standardformat, format="kompakt" und format="sidebar"
Bei verknüpften Kontakten ist die Überschrift "Kontakt über" (oder so) jetzt eine Überschriftengröße kleiner
