### ISSUE TITLE
Neues Attribut border

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#205]
Beim Shortcode bitte das Attribut border="true|false" ergänzen. Default ist true.

Dies setzt bei der Ausgabe des Personen-Contents (nicht bei Listen und kurzen Ausgaben, sondern bei der folgenden: 
`<div class="person content-person" itemscope itemtype="http://schema.org/Person">`

eine weitere CSS-Klasse, sofern das Attribut "false" gesetzt wurde:

`<div class="person content-person noborder" itemscope itemtype="http://schema.org/Person">`

**Comment by endv02** [comment]
gibt es "border" schon bei den Themes? Sonst würde ich rahmen nehmen, beim Konakt-Plugin ist viel deutsch zum einfacheren merken...

**Comment by xwolfde** [comment]
border gibt es bei diversen anderen shortcodes. Ist da gängiger als was deutsches.

Das Theme nicht ausschlaggebend.

**Comment by endv02** [comment]
Sorry, meinte natürlich Plugins und nicht Themes...
Beim Kontakt-Plugin gibt es eigentlich fast keine keine Parameter-Optionen mit ="0" oder ="1" mehr, sonst wird der Shortcode gleich so lang und unübersichtlich, hier wird alles über show und hide gelöst. In dem Sinne baue ich ein hide="rahmen" mit ein, kann aber gerne noch border="0" ergänzen, damit es auch funktioniert, wenn jemand das gewöhnt ist.

**Comment by xwolfde** [comment]
Auch gut.  Machen :)

**Comment by endv02** [comment]
Ist drin ab Version 2.5.0

**Comment by xwolfde** [comment]
Funktioniert nicht? Ich sehe es auch nicht im PHP Code.

**Comment by endv02** [comment]
Die Version 2.5.0 ist doch auch noch nicht online...?

**Comment by xwolfde** [comment]
deswegen hab ich es aus dem aktuellen dev gezogen. Dort steht, dass ich die v2.5.0 hab

**Comment by endv02** [comment]
Im dev-Branch setze ich die Versionsnummer nur einmal am Anfang hoch, aber nicht bei jeder Ergänzung. Sync findet erst heute Nachmittag statt, jetzt ist die Entwicklung noch am Rechner bei mir...
