### ISSUE TITLE
Reihenfolge Personen-Description und Connections bei Format Sidebar

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#206]
Bei der Anzeige der verknüpften Kontakte in der Page bzw. normalen Contentbereich ist es begründet, dass die Kontakte vor der Description kommen.

In der Sidebar ist das aber nicht ganz so optimal.
![fau-person-reihenfolge-desc-mit-connection](https://user-images.githubusercontent.com/1070669/31435224-2f91e894-ae7f-11e7-91fd-0fba29d4a228.jpg)

Vorschlag: Bei der Ausgabe des Shortcodes mit dem Format = sidebar werden angezeigte Kontakte erst nach der Description angezeigt.

**Comment by endv02** [comment]
Ist drin ab Version 2.5.0
