### ISSUE TITLE
Überschrift h3 statt h2 in Sidebar

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#208]
Ähm... jetzt ist in der Sidebar die Überschrift nicht mehr dieselbe wie vorher...

Das war jetzt mit der hstart-Sache nicht gewollt.

Bitte bei Nutzen der Anzeige in Sidebar wieder auf h2 als Default gehen.

**Comment by endv02** [comment]
Hast Du ein Beispiel? Vorher war bei der Sidebar der Name als h3 drin, nur der Widget-Titel als h2.

**Comment by endv02** [comment]
Hat sich erledigt, war ein anderer Fehler
