### ISSUE TITLE
Position strong?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#209]
Anfrage zur fetten Darstellung der Funktionen/Positionen einer Person:
![person-strong-position](https://user-images.githubusercontent.com/1070669/31939916-752c6a4a-b8bc-11e7-86d2-f4317c91963c.jpg)

War da schon immer ein strong drum oder ist das neu? Ist das da korrekt so?

**Comment by endv02** [comment]
Ja, war vorher schon immer so:
![test gender-und-diversity alles was sonst auf krach lief](https://user-images.githubusercontent.com/5851793/31942638-46db18da-b8c6-11e7-93b4-1653cef83ca4.png)
Aber vielleicht wirkte es da nicht so krass, weil die Schriftart kleiner war. 
Bei dieser Seite liegt es auch daran, dass der Job Title so lang ist, weil versucht wird, die englische und die deutsche Version auf einmal darzustellen.
