### ISSUE TITLE
CSS-Klassenname falsch?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#210]
Ich glaub hier ist der Classname falsch:
![person-default-thumb-class](https://user-images.githubusercontent.com/1070669/31943097-dee268b2-b8c7-11e7-9822-389fd008215e.jpg)

**Comment by endv02** [comment]
Nein, passt schon. 
person-thumb steht für das Bild, überall wo person-default- steht bedeutet das, dass es die Standardausgabe (ohne format="...") ist. person-default-thumb bedeutet, dass bei der Standardausgabe das Bild mit angezeigt wird. Würde das Bild hier nicht angezeigt werden, wäre die Klasse nur person-default.
Siehe auch: #207
