### ISSUE TITLE
Unterdrücken von UnivIS-Werten bei Sprechzeiten (wegen Mehrsprachigkeit)

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/fau-person#213]
Kundenwunsch der Anglistik:
    > Konkret geht es darum, dass wenn im UnivIS beim Personeneintrag Sprechzeiten
    > angegeben sind, diese wohl grundsätzlich bei den Kontaktinformationen mit
    > ausgegeben werden – auch, wenn für den Kontakt im Backend alternative
    > Informationen angegeben sind (die ja bei anderen Feldern dazu führen, dass die
    > aus dem UnivIS übernommenen Werte überschrieben werden). 
    > ... Wir haben für unsere Studierenden eine
    > Sprechstundenübersichtsseite angelegt, auf der die Kontaktinformationen inkl.
    > Sprechzeiten für sämtliche Dozent*innen ausgegeben werden. 
    > ... wird neben den Informationen aus dem entsprechenden
    > Kontakt zusätzlich ein deutscher Text ausgegeben, der aus dem UnivIS stammt
    > (siehe:
    > https://www.anglistik.phil.fau.de/information_for-students/office-hours/#letter-K).
    > Gibt es hier eine einfache Möglichkeit, die Angabe aus dem UnivIS zu unterdrücken?

**Comment by endv02** [comment]
Würde bei den Sprechzeiten Sinn machen, evtl. auch bei anderen Feldern, die keine Übersetzungsmöglichkeit von UnivIS her bieten.

**Comment by Albager** [comment]
...außerdem wäre es sinnvoll, wenn die Ausgabe des UnivIS-Eintrags "siehe persönliche Hompage ..." bei Sprechzeiten unterdrückt wird, sobald die Base-URL der persönlichen Homepage mit derjenigen der CMS-Instanz übereinstimmt, auf der der Kontakt angezeigt wird.

**Comment by xwolfde** [comment]
war bereits drin, so wie ich das sehe
