### ISSUE TITLE
Bildunterschriften bei Fotos durcheinander

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#214]
Ich habe da eine Portalseite, auf der ein Portalmenü zu sehen ist:

![bildschirmfoto 2017-11-08 um 13 56 27](https://user-images.githubusercontent.com/11296947/32550245-b0981f9e-c48c-11e7-8b47-b3b9e27f94b7.png)

Das Bild des Lehrstuhlinhabers hat in der Mediathek eine Bildunterschrift bekommen. Diese ist im Portalmenü aber nicht zu sehen. Wenn ich jetzt die Seite "Lehrstuhlinhaber" anklicke, wird mir die Information aus der Kontaktseite (mit format="page") angezeigt.

![bildschirmfoto 2017-11-08 um 13 58 25](https://user-images.githubusercontent.com/11296947/32550323-edbe46dc-c48c-11e7-9c3c-8836b0d34324.png)

Die Bildunterschrift, die hier zu sehen ist, gehört aber nicht zu dem angezeigten Bild, sondern zu dem aus dem Portalmenü. Das ist ungünstig, sorgt für Verwirrung und sollte geändert werden.

**Comment by xwolfde** [comment]
fixed ab V3
