### ISSUE TITLE
Zweitadresse von Hand einpflegen

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#216]
Kann man in den Kontakten eigentlich eine Zweitadresse von Hand einpflegen? Wenn nicht: Diese Möglichkeit sollte vorhanden sein, weil es ja doch einige Leute gibt, die nicht nur an der Uni Erlangen dozieren, sondern zusätzlich noch an einer anderen Uni.

**Comment by endv02** [comment]
Generell gibt es auch in UnivIS einen zweiten Adresseintrag - wenn dann sollte man vielleicht gleich damit verknüpfen.

**Comment by xwolfde** [comment]
Ansprechpartner.Kontakt nutzen
