### ISSUE TITLE
Rahmen um Visitenkarte überlappt mit Sidebar

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#218]
Der Rahmen um die Visitenkarte überlappt mal wieder mit der Sidebar. Möglicherweise Problem im Theme, dann bitte weitergeben. Zu sehen ist das auf https://sinologie.cms.rrze.uni-erlangen.de/kontakt/

![screenshot_sinologie](https://user-images.githubusercontent.com/11296947/33784261-6f66280e-dc60-11e7-9fc5-3fa83b1abc56.png)

**Comment by xwolfde** [comment]
Das hatten wir schon ausdiskutiert beim Theme. Das Problem ist nicht lösbar, es liegt hier auch eine fehlerhafte Nutzung vor: Kontakte links und rechts ist nicht.
Wenn das gewollt ist, dann muss links entweder ein anders Format verwendet werden oder rechts auf die Sideber verzichtet werden. Beides zusammen geht nicht.
