### ISSUE TITLE
Anzeige Kontakte Sidebar

### ISSUE THREAD

**Issue by mduven** [RRZE-Webteam/fau-person#219]
Hallo zusammen,
wurde vor längerem z.B. schon in [#162](https://github.com/RRZE-Webteam/fau-person/issues/162#issuecomment-242907434) und [#177](https://github.com/RRZE-Webteam/fau-person/issues/177) angeschnitten und bin aktuell wieder drauf gestoßen: Die Ausgabe von Kontakten per Shortdcode ohne format in der Sidebar liefert aktuell z.B. folgende Ausgaben:
![2017-12-13 16_37_49-nachhaltigkeit und verantwortung fachbereich wirtschaftswissenschaften](https://user-images.githubusercontent.com/28564104/33947186-0a7d6516-e024-11e7-9b96-5bcb84f9c93a.png)
![2017-12-13 16_38_01-fachbereichsprofil fachbereich wirtschaftswissenschaften](https://user-images.githubusercontent.com/28564104/33947195-0c2940ba-e024-11e7-8d48-5da5af485411.png)

Bei einer Ausgabe mit format="sidebar" lassen sich offensichtlich inzwischen die Parameter weiter einschränken, jedoch mit ähnlichem Effekt:
![2017-12-13 16_41_51-profpubl fachbereich wirtschaftswissenschaften](https://user-images.githubusercontent.com/28564104/33947518-daafde80-e024-11e7-8242-4f80956b4a93.png)

Gibt es für beiden Varianten (vor allem ohne Format) die Möglichkeit, den Text (also auch Namen) wieder unter dem Bild auszugeben?

**Comment by xwolfde** [comment]
Momentan nicht.

**Comment by xwolfde** [comment]
Teil des Themes, nicht des Plugins.
