### ISSUE TITLE
Personen erstellen und bearbeiten über Rest-API

### ISSUE THREAD

**Issue by RosesTheN00b** [RRZE-Webteam/fau-person#220]
Hey :-),

wenn wir unsere Personen automatisch aus Univis in FAU-Person importieren, müssen wir momentan manuell in die Datenbank eingreifen. Das ist nicht besonders schön.
Wäre cool, wenn wir für folgende Szenarios ein Rest-Interface o.ä. hätten:

* Person anlegen (neue Kategorien werden automatisch angelegt)
* Bereits erfasste Personen ausgeben ( inkl. Eigenschaften)
* Person ändern (neue Kategorien werden automatisch angelegt)
* Person löschen
* Kategorien löschen. Personen entsprechend aktualisieren oder Fehler ausgeben

Grüße
Sebastian

**Comment by Albager** [comment]
Ja, genau das das wäre wirklich toll und würde viel Fummelei ersparen!

**Comment by xwolfde** [comment]
Der Titel ist etwas irreführend. Es geht hier doch um einen automatischen Import aus UnivIS und dem regelmässigen Sync

**Comment by Albager** [comment]
Ich glaube, hier ging es eher um die Idee einer Rest-API, über die man den custom post type person / "Kontakte" in den CMS-Instanzen bequem bzw. batchmäßig bearbeiten kann. Zumindest hatte ich das damals so aufgefasst und solch ein Feature wäre nach wie vor nicht schlecht zu haben. Da haben sich bei uns gerade im Hinblick auf die englischsprachige Kind-Instanz noch keine wirklich guten Workflows etabliert und es herrscht noch oft Verwirrung. Da würde ich z. B. einen idealen use case für eine Rest-API o. ä. sehen, um einheitliche Kontakt-Kategorien usw. zu vergeben, ohne alle über die Backends machen zu müssen. Mit XML-Export-Import und XSLT ist das schon sehr aufwändig (vgl. https://github.com/Albager/cms-geo/tree/master/xslt).

**Comment by xwolfde** [comment]
Und wie soll da die Security aussehen, die verhindert, dass Dritte die API ausnutzen?

**Comment by Albager** [comment]
Ja, das ist eine gute Frage. Ich bin da auch kein Spezialist, aber könnte man es bei uns nicht evtl. mit dem SSO / Simple SAML lösen, wie etwa hier gezeigt? https://docs.alfresco.com/saml/tasks/restapi-auth.html dann könnte man wiederum an Wordpress zurückfragen, ob die Idm-Kennung Admin ist oder nicht (nur so als grobe Idee).

**Comment by xwolfde** [comment]
In dem Fall loggt man sich über das Backend ein und nutzt dann die WordPress-Import/Export. Das funktioniert doch bereits.

Obiges mit WP-Rest API und Auth ist aufwendig, Ich sehe jetzt den Bedarf nicht, den dieser Aufwand rechtfertigt?

**Comment by Albager** [comment]
Ja, ich glaube in dem Fall auch, dass der Bedarf einiger weniger den Aufwand nicht rechtfertigt, sowas zu implementieren. Das ändert nichts daran, dass es ein cooles Feature wäre 😄

**Comment by xwolfde** [comment]
Also wenn jemand ein Sub-Plugin erstellt und bereitstellt, würden wir das begrüßen. 

Aber -wie man auch am Alter des Tickets sieht und der langen Zeit in der das Plugin still stand- derzeit fehlt es uns hier an den Ressourcen, so daß wir uns auf das Notwendigste konzentrieren müssen. Sorry.
