### ISSUE TITLE
Links zu zugeordneten Kontakten in verknüpften Kontakten

### ISSUE THREAD

**Issue by rvdforst** [RRZE-Webteam/fau-person#223]
Es sollten Links zu den Seiten von zugeordneten Kontakten erzeugt werden.

<img width="703" alt="bildschirmfoto 2018-02-12 um 17 59 49" src="https://user-images.githubusercontent.com/299916/36159676-9537430c-10df-11e8-9f59-a41ed55a1282.png">
<img width="694" alt="bildschirmfoto 2018-02-12 um 18 00 52" src="https://user-images.githubusercontent.com/299916/36159686-9abdad02-10df-11e8-9ca4-3721a458f8ae.png">

**Comment by endv02** [comment]
Ist in Version 2.6.3 dabei
