### ISSUE TITLE
Sprechzeiten: "Uhr" fehlt, Komma stört, Hinzufügen holpert

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/fau-person#227]
Die Sprechzeiten an den Visitenkarten werden merkwürdig dargestellt:

<img width="570" alt="unbenannt" src="https://user-images.githubusercontent.com/9445370/37528396-d270cfaa-2934-11e8-9818-68053d8e61d3.PNG">

Das Wort Uhr fehlt (oder ein h), die Zeiten stehen ohne jede Einheit da.

Hinter der letzten Uhrzeite steht irritierenderweise ein Komma.

Fügt man eine weitere Sprechzeit hinzu mit Tag und Turnus, so werden Tag und Turnus nicht gespeichert, nur die Sprechzeiten selbst. Man muss nach dem Aktualisieren des Kontakts dann noch einmal Tag und Turnus anhaken und noch einmal aktualisieren. (Im Screenshot fehlen die Details für den zweiten Eintrag noch)

**Comment by xwolfde** [comment]
Duplicate issue. Siehe dazu hier https://github.com/RRZE-Webteam/fau-person/issues/196
