### ISSUE TITLE
Listenansicht mit Kurzbeschreibung wird in mobiler Ansicht zerhauen

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/fau-person#228]
Im CSS scheint die mobile Ansicht für die Listendarstellung bei Kontaktübersichten für Kontakte mit Einträgen im Feld "Kurzbeschreibung" vergessen worden zu sein. In der mobilen Ansicht wird ein komischer Zeilenumbruch der Kurzbeschreibung gemacht, dazwischen landen das Foto und der Kontaktdatenblock.  Da es gewünscht wurde, für AG-Mitarbeiter, Studienberater etc. eine solche Funktionsbezeichnung in den Listenansichten zu haben, wäre es toll, wenn die Darstellung in der mobilen Ansicht wie vorgeschlagen funktionieren würde:

![kurzbeschreibung_mobileansichtsosollteessein](https://user-images.githubusercontent.com/11389126/37557286-83da4640-2a02-11e8-946e-4694041e3f0f.png)
_siehe https://geographie.cms.rrze.uni-erlangen.de/forschung/ag-moelg/#collapse_0_
Das verwendete Format des `[kontakt]`-Shortcodes im content-Bereich der Seite:
`[kontakt category="agmoelg" hide="telefon, organisation, adresse, position, abteilung" show="bild, kurzbeschreibung, email" sort="nachname"]`

**Comment by xwolfde** [comment]
Das erste ja, das ist ne offene Baustelle. Beantwporte da aber mal selbst die Frage: Wie soll es denn da aussehen, wenn die Schrift größer ist oder der Platz nicht ausreicht dafür, rechts neben dem Bild was zu stellen? Die Sidebar gibt es nämlich in zwei Breiten (auf Portal und Startseiten haben wir da 100px mehr, auf Sidebars in Pages sind die kleiner).

Also: Was soll passieren wenn der Platz nicht reicht? Genau das ist nämlich das zugrunde liegende Problem. Gewünscht war nämlich in solchen Fällen das Bild VOR den Text zu haben - und daher gibt sich dann die Reihenfolge.


Das zweite verstehe ich nicht, denn da gibt es doch ganz viele solche Fields... mach das doch lieber in einem eigenen Issue.

**Comment by xwolfde** [comment]
Moment, zwischenfrage: Ist der obige Code im Content oder Sidebar?

**Comment by Albager** [comment]
Es geht hier nur um den Content der entsprechenden Seiten.

**Comment by Albager** [comment]
@xwolfde : Welches Feld außer "verknüpfte Kontakte" wird denn noch als Listenelement unterhalb des Kontaktdatenblock ausgegeben? Ich habe z. B. versucht, die Sprechzeitenfelder dafür zweckzuentfremden, aber die erscheinen ja nur ganz normal...

**Comment by Albager** [comment]
#229

**Comment by endv02** [comment]
Ich schließe das hier mal, ist Sache des Themes.
