### ISSUE TITLE
Entfernung des Personenindex entfernt auch die Suche in Personen Custom Post Type

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#231]
Wenn in den EInstellung die Erstellung des Personenindex unterdrückt wird, wird auch bei der Suche nicht mehr in den Custom Post Type person gesucht.

**Comment by Albager** [comment]
siehe auch [Issue #234](https://github.com/RRZE-Webteam/fau-person/issues/234)

**Comment by xwolfde** [comment]
fixed
