### ISSUE TITLE
hä? Sortierfehler bei sort="nachname"

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/fau-person#232]
Kontakte, die ein **Ä** im Nachnamen haben, werden in `[kontakt]`-Shortcodes mit Parameter `sort="nachname"` falsch einsortiert. Siehe https://geographie.cms.rrze.uni-erlangen.de/personen/

![ha](https://user-images.githubusercontent.com/11389126/37848562-d9dfc85e-2ed4-11e8-8bb0-4a9d0a048664.PNG)
![image](https://user-images.githubusercontent.com/11389126/37881928-8ce21946-309e-11e8-8742-2b80488c7dd8.png)

Ob das Problem auch mit anderen Umlauten auftritt, habe ich noch nicht ausprobiert. Zumindest mit **Ö** funktioniert die Sortierung korrekt...

Die Kontaktdaten der Beispiele kommen aus UnivIS. Aber auch wenn ich die UnivIS-Verknüpfung entferne und im Namensfeld die Nachnamen eintrage, ändert sich nichts an der falschen Einsortierung.

In der [fau-person.php](https://github.com/RRZE-Webteam/fau-person/blob/ab2a7810db890bd60c243c111709e0dd8ec3af49/fau-person.php#L1105) sieht die sort-Funktion aber eigentlich OK aus... Hmmmm.. Vielleicht hat es ja damit was zu tun? https://stackoverflow.com/questions/10649473/sort-an-array-with-special-characters-in-php

**Comment by xwolfde** [comment]
sollte im nächsten update behoben sein

**Comment by Albager** [comment]
So ganz richtig funktioniert die Sortierung bei **Ä** (zweite Stelle im Nachnamen) leider immer noch nicht :confused:
![image](https://user-images.githubusercontent.com/11389126/79504530-5373b200-8033-11ea-8479-941280aeb70d.png)
-> Bäu... muss vor Bur...
Allerdings funktioniert es wohl richtig, wenn **Ä** an dritter Stelle im Nachnamen steht:
![image](https://user-images.githubusercontent.com/11389126/79504660-8158f680-8033-11ea-8d03-89028485079b.png)

vgl. https://www.geographie.nat.fau.de/institut/personen/

**Comment by xwolfde** [comment]
Das Update ist auch noch nicht raus.

**Comment by Albager** [comment]
Achso OK, dann bleibt es spannend :-)

**Comment by xwolfde** [comment]
Zwei Lösungen, die sofort funktionieren:
1. Sortierfeld benutzen (wurde extra für Leute mit Sonderzeichen im Namen - es gibt übrigens auch Leute aus China- gemacht)
2.Info zur Namensänderung; Beantragung auf https://erlangen.de/service/3754

**Comment by xwolfde** [comment]
Wenn in dem Feld nichts steht, fällt er dann zurück auf den titel bzw auf den Namen.
Ist ne Weile her, wo ich das machte, daher wieß ich es nicht mehr genau. Teste es einfach mal aus.

**Comment by Albager** [comment]
M. E. ist das nach wie vor ein ungelöster Issue, der m. E. einfach behebbar wäre. Vor allem an Leute ohne technischen Hintergrund kann man die fehlerhafte Sortierung (ich meine der Fehler besteht, seit es das Theme gibt bzw. seit wir es nutzen - also seit etwas mehr als vier Jahren) schwer vermitteln...
