### ISSUE TITLE
Direkte Übernahme der Daten aus Univis in die Visitenkarte eines Kontakts (alternativ unterschiedliche Mailadressenanzeige)

### ISSUE THREAD

**Issue by Tilltheman** [RRZE-Webteam/fau-person#233]
Hallo zusammen,
ich fände es sehr nützlich eine Option zu haben, mit der ich nicht nur die Daten die in Univis hinterlegt sind anzuzeigen, sondern diese auch direkt in die einzelnen Felder des Kontakts übernehmen zu können. Wenn ich also einen neuen Kontakt anlegen möchte, und die Univis-Daten hole (welche dann ja auch unter den Feldern stehen), dass diese dann auch direkt in den Datenfeldern der Visitenkarte stehen. Konkret suche ich nach einer Möglichkeit, alle Daten aus Univis zu übernehmen, um dann eventuell ein Datenfeld zu ändern. Das gäbe mir z.B. die Option, eine alternative E-Mail-Adresse zur im Univis hinterlegten Adresse einzutragen, ohne alle Daten per Copy & Paste in die Felder einzutragen nur um dann die E-Mail-Adresse zu ändern. Alternativ wäre eine Überschreibung/Freie Auswahl der E-Mail-Adresse nützlich, da es sogar schon innerhalb eines Webauftritts sein kann, dass ein Mitarbeiter mit verschiedenen E-Mail-Adressen genannt werden möchte (z.B. studienfachberatung-<Fach>@fau.de auf der Kontaktseite des Studienfachberaters und eventuellen anderen E-Mail-Adressen einer anderen Position oder eben die persönliche E-Mail-Adresse).
Vielen Dank und viele Grüße

**Comment by mduven** [comment]
fände ich auch sehr nützlich..

**Comment by Albager** [comment]
Oder man schafft in UnivIS die Möglichkeit, mehrere Mailadressen (und sonstige Zusatzinfos) einzutragen und gleichzeitig die Möglichkeit, dass die Leute das in UnivIS auch selber bearbeiten können. M. E. macht es wenig Sinn, solche (durchaus wichtigen) Informationen lückenhaft an verschiedenen Orten vorzuhalten.

**Comment by endv02** [comment]
Generell wurde sich bewusst dagegen entschieden, nur einzelne Feldinhalte aus UnivIS zu übernehmen (oder das mittels Kopierfunktion zu erleichtern), damit falsche Daten auch in der Quelle UnivIS verbessert werden. 
Zur Verwendung mehrerer Mailadressen einer Person gibt es einen Beschluss, dass die fau.de-Adresse als eindeutige, alleinige Dienstadresse verwendet werden soll (siehe auch #237).
Das Problem mit den Funktionsadressen würde ich über verknüpfte Kontakte lösen: für die Funktion einen Kontakt anlegen, diesem die Funktionsmailadresse zuweisen, und dann einen Kontakt in den anderen verknüpfen.
