### ISSUE TITLE
Falsche Weiterleitung bei Klick auf Breadcrumbnavigation "Kontakt"

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/fau-person#234]
Wenn man in der Breadcrumbnavigation einer Kontaktseite auf "Kontakt" klickt, landet man auf der Seite https://www.geographie.nat.fau.de/international/personalmobilitaet/ und nicht beim Kontaktindex (das selbe passiert beim Aufruf von https://www.geographie.nat.fau.de/person) - Warum das so ist, erschließt sich mir nicht. Handelt es sich um einen Bug? (siehe auch [Issue #231](https://github.com/RRZE-Webteam/fau-person/issues/231))

![kontaktendpoint](https://user-images.githubusercontent.com/11389126/39255910-e6e92cd2-48ad-11e8-905a-1cf3ca59c67e.png)

**Comment by endv02** [comment]
Danke für den Hinweis, das Problem taucht nur auf, wenn man eine andere Kontaktübersichtseite als die Standardseite wählt (entsprechender Haken bei den Anzeigeoptionen ist draußen). Dann wird nach einer Seite mit Slug "person" gesucht, daher der Treffer bei "personalmobilität". Lösung ist in Arbeit.
