### ISSUE TITLE
Unterdrückung der persönlichen Website aus UnivIS

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/fau-person#235]
Wenn ein Kontakt mit einer UnivIS-ID verknüpft ist und wenn im UnivIS-Eintrag im Feld "Website" eine URL eingetragen ist, die identisch mit der URL der Kontaktseite in der CMS-Instanz ist, sollte die Ausgabe dieses Feldes auf Kontaktseiten im Person-Plugin unterdrückt werden, da es ein selbstreferenzieller Link ist.

![fauperson_linkpersonenseiteunivis](https://user-images.githubusercontent.com/11389126/40585673-26571a60-61b7-11e8-9cee-ed6af8e2a6db.png)

**Comment by xwolfde** [comment]
Problem:
Bei dem Ausdruck und noch viel wichtiger, bei den Schema-Angaben für SEO, fehlt die URL aber dann....

**Comment by Albager** [comment]
Ok, das mit dem Schema für SEO ergibt Sinn. Daran habe ich gar nicht gedacht. Ich finde es sieht nur so "doppelt-gemoppelt" aus, wenn in dem info-Feld die URL der Personenseite Steht, auf der man sich sowieso ja schon befindet.

**Comment by xwolfde** [comment]
Sehe ich genauso. Aber andererseits sind wir eine MInderheit: Die meisten User nutzen inzwischen Browser, die keine Adresszeile mehr anzeigen.
