### ISSUE TITLE
Anregung: Telefon-Links bei Kontakten

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/fau-person#236]
Es wäre sehr praktisch, wenn Telefonnummern auf Kontaktseiten sowie in Kontakt-Shortcodes automatisch als Links generiert würden. Das würde usern das markieren/kopieren/einfügen der Telefonnummern sparen, besonders wenn das CMS-Angebot mit einem mobilen Gerät genutzt wird.

Telefon:  `<a href="tel:+4991318528326">+49 9131 85-28326</a>`

![image](https://user-images.githubusercontent.com/11389126/40282534-25d9c6c8-5c71-11e8-971e-66e1439e0985.png)

Für Faxnummern könnte man es ggf. ähnlich machen.

**Comment by xwolfde** [comment]
In der nächsten Version drin
