### ISSUE TITLE
Mehrere E-Mailadressen aus UnivIS

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#237]
Eine Kundin hat in UnivIS zwei Mailadressen angegeben (ihre eigene und die des Instiuts, für das sie arbeitet). Nun werden zwar beide Adressen angezeigt, klickt man sie aber an, wird eine Mailvorlage für beide Adressen erzeugt. Nachdem ich nun nicht weiß, wie was in UnivIS eingetragen wird, frage ich hier, ob es eine Methode gibt, Mailadressen so einzutragen, dass zwar mehrere Mailadressen im Kontakt angezeigt wird, bei Klick auf den Mailto-Link aber nur eine Vorlage für diejenige Adresse erzeugt wird, die man ausgewählt hat, für alle weiteren nicht. Gibt es?

**Comment by xwolfde** [comment]
Man kann im UnivIS zwei Kontaktadressen eintragen. Wenn man es richtig macht..
Aber wenn Leute es falsch machen und in dem Eingabefeld wo sie eine Mailadresse eingeben sollen, zwei eingeben, ist es halt falsch.

Grundsätzlich macht es an der FAU auch keinen Sinn: Die Die Uni hat über UL Beschluss festgelegt, daß jeder nur eine eindeutige Mailadresse hat, egal an welchen Institut er oder sie arbeitet. Die Eingabe von Privatadressen im Univis oder anderer nicht konformer Adressen ist auch nicht erwünscht. 
 Es gibt daher für uns keinen Anlass, mehr als eine Mailadresse zu beachten.

**Comment by endv02** [comment]
Wenn eine Person dennoch eine zweite Mailadresse benötigt (aus obigen Gründen nur sinnvoll bei einer Funktionsmailadresse), lässt sich das am besten über verknüpfte Kontakte lösen.
