### ISSUE TITLE
Breadcrumb in den Kontaktseiten enthält ein / zuviel

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#238]
Bin gerade bei der Kundschaft; dort haben wir einen Kontakt aufgerufen und dort in der Breadcrumb auf "Contact" geklickt (Seite ist auf Englisch). Da kommt man auf die 404er Fehlerseite, weil im tatsächlichen Link (bla.fak.fau.de/person) ein / zuviel ist. Ich gehe davon aus, dass das aus dem Plugin kommt, deshalb hier. Link: https://www.i3upgrade.eu/person/jurgen-karl/

**Comment by michaeldorner** [comment]
Hinzukommt, dass in der Breadcrumb (im Englischen) "Contact" statt einfach der Slug verwendet wird.  Ließe sich das nicht ändern?

**Comment by endv02** [comment]
Im Deutschen steht in der Breadcrumb sich Kontakt und nicht Person, oder ist was anderes gemeint?

**Comment by endv02** [comment]
Fehler ist in der nächsten Version des Themes behoben.
