### ISSUE TITLE
URL wird nicht überschrieben

### ISSUE THREAD

**Issue by michaeldorner** [RRZE-Webteam/fau-person#239]
Obwohl ich die _Website_ unter _Social Media_ für einen Kontakt überschrieben habe, wird diese Änderung nicht übernommen.

**Comment by endv02** [comment]
Daten eines Kontaktes, die in UnivIS hinterlegt sind, können über das Plugin nicht überschrieben werden. Diese müssen dann in UnivIS geändert werden. 
Grund: Scheinbar sind die Daten in UnivIS ja falsch, sonst müssten sie ja nicht überschrieben werden. Dann macht es auch Sinn, diese an allen Stellen zu korrigieren, an denen sie im Netz zu finden sind - also auch in UnivIS. Das kann der UnivIS-Beauftragte des Lehrstuhls anpassen.
