### ISSUE TITLE
Barrierefreiheit

### ISSUE THREAD

**Issue by zfldev** [RRZE-Webteam/fau-person#24]
Die Symbole sollten unbedingt um aria-label=" " und title=" " ergänzt werden. Blinde Menschen „sehen“ nicht anhand des Inhalst ob es sich um eine Handynummer, Telefonummer oder Faxnummer handelt.

**Comment by xwolfde** [comment]
Vorsichtig!

aria-label="" erasetzt den Text wenn man es falsch macht. Es iwierkt dan als Replacement.
Es solltze keinesfalls und nie eingesetzt werden, wenn der relevante Texte sichtbar ist.
vgl: http://www.w3.org/TR/wai-aria/states_and_properties#aria-label 

title="" ist browserabhängig nicht immer korrekt interpretiert. Zudem ist der Title aus Sicht der Barrierefreiheit (bei Links) dann falsch, wenn der Titel und er Erstreckungstext identisch sind.

Eine Diskussion hierzu siehe auch: http://www.nczonline.net/blog/2013/04/01/making-accessible-icon-buttons/

Einige Dokus empfehlen, die Symbolgrafiken (aus Awesome Fonts via content) eingefügt via "content" zu setzen. vgl: http://www.barrierefreies-webdesign.de/knowhow/symbole/generierte-inhalte-mit-content.html 
Dies wäre in diesem Fall aber ganz falsch, da eben Awesome das Content belegt.

In diesem Fall der Personenanzeige sollte bei Beibehaltung der jetzigen CSS-Iconfonts der Code wie folgt aussehen (inkl. Schema Properties):

<div class="person content-person" itemscope itemtype="http://schema.org/Person">

<h3><span itemprop="jobTitle">Dr.</span> <span itemprop="givenName">Reiner</span> <span itemprop="familyName">Ohnebild</span> Dipl. Brffr.</h3>
<ul class="person-info">
<li class="person-info person-info-position" ><span class="screen-reader-text">Position </span><span itemprop="jobTitle">Büroleiter</span></li>
<li class="person-info person-info-institution"><span class="screen-reader-text">Organisation </span><span  itemprop="worksFor">Poststelle</span></li>
<li class="person-info person-info-phone"><span class="screen-reader-text">Telefonnummer </span><span itemprop="telephone">09131/85-62541</span></li>
<li class="person-info person-info-fax"><span class="screen-reader-text">Faxnummer </span><span  itemprop="faxNumber">09131/85-62541</span></li>
<li class="person-info person-info-email"><span class="screen-reader-text">E-Mail </span><a itemprop="email" href="mailto:ro@fau.de">ro@fau.de</a></li>
<li class="person-info person-info-www"><span class="screen-reader-text">Webseite </span><a itemprop="url" href="http://fau.de" rel="external nofollow" title="" class="ext-link ext-icon-19">http://fau.de</a></li>

...

</ul>
</div>

**Comment by xwolfde** [comment]
umgesetzt
