### ISSUE TITLE
PHP 7 Issues to check

### ISSUE THREAD

**Issue by jbhs** [RRZE-Webteam/fau-person#240]
FILE: /wp-content/plugins/fau-person-master/includes/univis/iCalcreator.class.php

FOUND 0 ERRORS AND 8 WARNINGS AFFECTING 8 LINES

   90 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
 2106 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
 6438 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
 6585 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
 6724 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
 6834 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
 6916 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
 6999 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.

FILE: /wp-content/plugins/fau-person-master/includes/univis/mitarbeiter-einzeln.php

FOUND 1 ERROR AFFECTING 1 LINE
 16 | ERROR | Function split() is deprecated since PHP 5.3 and removed since PHP 7.0; Use preg_split instead

FILE: /wp-content/plugins/fau-person-master/includes/univis/SG-iCalendar/helpers/SG_iCal_Parser.php

FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE

 47 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4

**Comment by endv02** [comment]
Danke für den Hinweis! Da die Kalenderfunktionalität eh vom Personenplugin nicht unterstützt wird, wird das in der nächsten Version entfernt.
