### ISSUE TITLE
Sprechzeiten: Bemerkungsfeld und Terminanzeige

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#241]
Die Terminauswahl bei den Sprechzeiten muss flexibler sein, aber dabei unbedingt die Validität der Eingaben wahren.

Aktguell kann bei der Zeiteingabe jeder String angenommen werden und Leute geben da auch mal so "Uhr" ein oder "PM", wenn sie meinen das sei korrekt. Hier muss man das mit der Eingabe besser man und validieren, da bei der Ausgabe nicht nur Optische Ausgabe vorhanden ist, sondern auch strukturierte Daten für Suchmaschinen. Und die wollen valide Daten und kein Traumstring.

Um aber den Wünschen nach zusätzlichen Eingaben entgegen zu kommen, könnte ein optionales Bemerkungsfeld ergänzt werden, welches abhängig ist.

Also am Beispiel:

https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketAttachment;Subaction=HTMLView;ArticleID=1970235;FileID=2

> "Hier steht nun fälschlicherweise:
>  
> Mo, Di, Mi, Do, Fr. 
> 08:30 – 12:00 Uhr
> 14:00 – 16:00 Uhr (nur während der Vorlesungszeit)
>  
> Jedoch haben wir nur Mittwochs während der Vorlesungszeit von 14-16 Uhr geöffnet und nicht jeden Tag. Bitte den Fehler schnellstmöglich berichtigen, da schon Studierende bei uns waren und dann entweder vor Zi. 0.034 vor verschlossener Türe stehen oder bei mir im Büro auftauchen.
> Richtig wäre:
>  
> Mo, Di, Mi, Do, Fr. 
> 08:30 – 12:00 Uhr
> Mi, 14:00 – 16:00 Uhr (nur während der Vorlesungszeit)
>  
> "

Andererseits: Wenn der Aufwand zu groß ist und/oder die Komplexität für den Eingebenden zu groß wird, dann lassen wir das lieber sein und ergänzen ein schlichtes (WYSIWYG?)Textfeld zur freien EIngabe des Termins, welche dann auch keine strukturierten Daten enthält.

**Comment by endv02** [comment]
Das obige Problem ist ein Problem der Eingabe. Für den Nachmittagstermin am Mittwoch muss man einfach eine weitere Sprechzeit einfügen, dann steht vorne auch der Mittwoch dran.
