### ISSUE TITLE
Verlinkung zu Homepage statt zu Kontaktseite?

### ISSUE THREAD

**Issue by nneuss** [RRZE-Webteam/fau-person#242]
Hallo,
wenn ich auf einer Seite das fau-person-Plugin wie folgt verwende
[kontakt id="3216" format="page"]
enthält der HTML-Text anklickbaren Namen, der zu einer separaten Kontaktseite verlinkt.  Ich würde da aber gerne zur Homepage dieserPerson verlinken.  Geht das?

**Comment by endv02** [comment]
Ohne Beispiel kann ich das Problem leider nur mutmaßen und folgende Infos geben:
- Im HTML-Text eines Kontaktes können ganz normal Links eingebaut werden
- Im HTML-Text eines Kontaktes kann auch ein anderer Kontakt über Shortcode mit [kontakt id="xxx"] eingebunden werden
- Wenn Kontakte irgendwo über Shortcode mit [kontakt id="xxx"] eingebunden werden, wird bei jedem Format (außer format="page") mit einem Link versehen. Der Link geht standardmäßig auf die Kontaktseite, kann aber im Kontakt auch auf eine andere Seite geführt werden (im Block "Social Media" bei "Name und Mehr-Link verlinken auf Seite..."
Bitte nochmal melden, wenn das Problem hiermit nicht gelöst werden konnte.

**Comment by nneuss** [comment]
Danke schön, das Problem ist dadurch gelöst.
