### ISSUE TITLE
Sprechzeiten: Radiobuttons können nicht deaktiviert werden

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#243]
Wenn man bei den Sprechzeiten einen der Radiobuttons anklickt (täglich - wöchentlich - alle 2 Wochen), kann man das nur deaktivieren, indem man eine zweite Sprechzeit anlegt und die erste löscht. Das ist ein wenig umständlich und auch nicht offensichtlich genug. Es sollte eine Möglichkeit geben, die Radiobuttons sämtlich zu deaktivieren.

**Comment by xwolfde** [comment]
fixed
