### ISSUE TITLE
"Funktionen" aus UnivIS auslesen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/fau-person#244]
es wäre schön, wenn man neben der Position einer Person auch noch deren Funktionen aus UnivIS mit Hilfe des Plugins auslesen kann

**Comment by xwolfde** [comment]
Ggf. Umstellung auf neuer JSON-API von UnivIS notwendig

**Comment by xwolfde** [comment]
Leider in der aktuellen Form nicht möglich, da man hierzu bei UnivIS andere Datentabellen abfragen müsste: Die Funktion hängt an dem Eintrag der Einrichtung und nicht der Person. Der Eintrag in den EInrichtungen zeigt auf die Person. Aber aus der Person gibt es keinen nutzbaren Rückpointer auf die Einrichtung.
Man müsste daher theoretisch zu jeder Person die Einrichtung suchen& angeben, aus der die Funktion genommen werden soll. 
Der Aufwand ist da auch für den Nutzer (er muss dazu erst die UnivIS Nummer der jeweiligen EInrichtung und/oder dessen Unterorg suchen) höher als wenn er das einfach in dem Texteingabefeld ergänzt.
