### ISSUE TITLE
Metabox mit Kontaktanzeige

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#250]
Die Metabox mit der Kontaktanzeige sorgt (insbes. bei großen Zahlen an Kontakteinträgen) für ein großes Ladevolumen im Backend.
Viele Kunden nutzen das Teil nicht mehr. 
Der erste Ansatz war daher, die Metabox zu entfernen.

Gleichwohl  hab ich jetzt auf die Ankündigung hin, erste  Rückmeldungen, dass es doch nicht gebraucht wird.

Vorschlag: Optional: Das Teil ist per Default aus; Aber man kann es in den Settings einschalten. Wobei das Einschalten dann trotzdem auch sagen kann wo (Page oder Post-Editor, aber nicht bei anderen Editoren).

**Comment by xwolfde** [comment]
Posts und Pages unterscheidbar machen

**Comment by xwolfde** [comment]
Option in Settings dazu.

**Comment by xwolfde** [comment]
fixed. Inkl. CopyToClipboard für den SHortcode

**Comment by cibsell** [comment]
Meinst Du damit die Box?

![grafik](https://user-images.githubusercontent.com/8234890/81070736-f5284980-8ee3-11ea-8f6e-594740e977e6.png)


Bitte nicht löschen, ich benutze die ständig!!

**Comment by xwolfde** [comment]
Ja. die Box ist nicht weg, sondern besser geworden:
![grafik](https://user-images.githubusercontent.com/1070669/81081569-96fa6700-8ee1-11ea-9c32-db24a1908f34.png)

Der lokale Siteadmin **kann** die Box aber in den Settings abschalten.

**Comment by cibsell** [comment]
Perfekt, danke. :)

**Comment by wrcg** [comment]
> Ja. die Box ist nicht weg, sondern besser geworden:
> ![grafik](https://user-images.githubusercontent.com/1070669/81081569-96fa6700-8ee1-11ea-9c32-db24a1908f34.png)
> 
> Der lokale Siteadmin **kann** die Box aber in den Settings abschalten.

bei mir erscheint auf Beta der Absatz mit dem Shortcode nicht :-(
![image](https://user-images.githubusercontent.com/9526974/81140906-43ccf680-8f6b-11ea-846d-9bebc4c8efee.png)
