### ISSUE TITLE
Buttons im Person-Plugin (Kundenwunsch)

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/fau-person#254]
Kundenwunsch:

- Die Möglichkeit einen Button im Person-Plugin zu erstellen

**Comment by xwolfde** [comment]
= Ausführen von Shortcodes im Beschreibungsfeld.

**Comment by xwolfde** [comment]
#264

**Comment by xwolfde** [comment]
In den Kurzbeschreibungen ist kein HTML möglich. Wohl aber im Content.
Lösung ist daher entweder dies mit format="page" zu machen oder das Shortcode-Element unabhängig vom Kontakt-Shortcode zu plazieren.
