### ISSUE TITLE
Personenanzeige in Sidebar

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#26]
Hallo,

wenn ich bei Personen eine Person anlege und unter "Eigenschaften" die Postadresse angebe, dann erscheint diese Adresse in der Sidebar ohne Zeilenumbruch, siehe Screenshot. Gebe ich br ein, wird der Code in Text umgewandelt und kein Zeilenumbruch gemacht. 

![adresse-anzeige](https://cloud.githubusercontent.com/assets/8234890/7086666/fc900eac-df83-11e4-88bb-2fe0d543f767.png)

**Comment by endv02** [comment]
Bei welchem Theme? fau-person ist ein eigenständiges Plugin, unabhängig davon können im FAU-Theme auch noch die Personen eingebunden werden (aktuell auch noch im Philfak-Theme). Ich pack das mal zum FAU-Theme rüber.

**Comment by xwolfde** [comment]
In Philfaktheme bereits repariert...
