### ISSUE TITLE
Kontakt Editor: Sichtbare Boxen für Benutzer konfigurieren

### ISSUE THREAD

**Issue by Blubbaa** [RRZE-Webteam/fau-person#262]
Wir haben am Lehrstuhl > 70 Mitarbeiter, weshalb jeder selbst für seine eigene Kontaktseite zuständig ist. Die Berechtigungen nur seine eigene Seite bearbeiten zu dürfen, haben wir mit dem Workflow Plugin und Autorenrechten gelöst.

Allerdings können die Mitarbeiter bei sich selbst noch zu viele Felder bearbeiten, auf die sie keinen Einfluss haben sollten, z.B. die Kontakt Kategorie oder die Univis Felder. Im WP Editor können bereits über "Ansicht anpassen" die sichtbaren Editor-Boxen konfiguriert werden, allerdings gilt das nur für den eigenen User. Am besten wäre es diese für Benutzergruppen (Autoren, Redakteure...) allgemein konfigurierbar zu machen.

Ob das besser hier oder im [CMS-Workflow](https://github.com/RRZE-Webteam/cms-workflow) aufgehoben ist, kann ich nicht beurteilen.

**Comment by xwolfde** [comment]
Guter Punkt, nehmen wir auf.
Wobei ich aber der EInfachheit halber erstmal auf Benutzerrollen abzielen würde und nicht auf individuelle Zuordnungen.


Wir werden in Kürze eine neue Version releasen, in der einige neue Felder hinzukommen.
Ich würde das gern erst abwarten und dann noch mal besprechen, welche Felder für welche Rollen schützenswert wäre. Wäre das in Ordnung?

**Comment by Blubbaa** [comment]
Alles klar, das klingt gut.

**Comment by xwolfde** [comment]
Im Rahmen der Umstellung auf FAUdir wird dies neu entwickelt und neu gedacht werden.
Mit FAUdir werden die Mitarbeitenden die Möglichkeit haben, ihre eigenen Daten im IdM Portal zu pflegen und brauchen dazu dann auch nicht mehr im WordPress arbeiten. Daher entfällt dann auch die Notwendigkeit, ein Rollenkonzept zu erarbeiten.
