### ISSUE TITLE
Abwärtskompatibilität

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#27]
Bei vorherigen Nutzung der Theme-"Personenverwaltung" werden die Daten nicht übernommen bei Wechsel auf das Plugin. Lediglich Slugname und Artikelbild. ggf. abwärtscomptabilität einbauen, damit Datenbankgefrickel nicht notwendig ist.
(Das können wir zwar selber für eigenen Installationen machen, aber andere nicht)

**Comment by endv02** [comment]
Wird nicht umgesetzt, da ganzes Plugin umstrukturiert und für uns beginnend neu eingesetzt wird.
