### ISSUE TITLE
löst redundate Sortierkriterien in RRZE-FAQ aus

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/fau-person#273]
Bitte in fau-person.php in public function person_restrict_manage_posts() (Zeile 873) prüfen, dass post_type nicht 'faq'  ist ( if( $post_type !== 'faq' ){...} ) wegen https://github.com/RRZE-Webteam/rrze-faq/issues/38

**Comment by xwolfde** [comment]
fixed im dev
