### ISSUE TITLE
Gleicher Shortcode, andere Ausgabe

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#282]
Hallo allerseits,

ich habe den gleichen Shortcode verwendet, aber die Ausgabe ist unterschiedlich. Woran kann das liegen? Das ist nur bei der Ausgabe bei Fr. Pischetsrieder so, alle anderen sind zweispaltig. Ist der Name des Lehrstuhls / Webseite zu lang?

`[collapse title="PD Dr. Christian Papp"]
[kontakt id="4904" show="webseite, bild, raum, adresse, kurzbeschreibung"]
[/collapse]

[collapse title="Prof. Dr. Monika Pischetsrieder"]
[kontakt id="5002" show="webseite, bild, raum, adresse, kurzbeschreibung"]
[/collapse]`

![grafik](https://user-images.githubusercontent.com/8234890/81070189-2fddb200-8ee3-11ea-9d3a-c54fd31c9f87.png)

**Comment by xwolfde** [comment]
Es kann sein, dass er wegen dem Wort "Henriette-Schidt-Burkhard-Lehrstuhl" einerseits und dem Wort "Nahrungsmittelzusammensetzung" umbricht.
Es sind also sowohl in der einen spalte als auch in der anderen spalte zwei Begriffe vorhanden, von denen ein normaler Browser sicher kein Wortschatzeintrag hat und von denen er nicht weiß, wo er sie umbrechen kann.

Aber möchtest du das vielleicht nicht mit dem neuen Plugin auf unserem Beta-Portal testen? Vielleicht ist das ein Bug, der bereits behoben wurde.

**Comment by cibsell** [comment]
Ich würde gerne testen, kann aber im Beta-Portal nur gucken, nix testen... Schaltest Du mich bitte frei?

**Comment by xwolfde** [comment]
mail mit login müsste gekommen sein

**Comment by xwolfde** [comment]
nähere absprache gern via mattermost . Da ist auch cathrin, die ebenfalls gerade testet

**Comment by cibsell** [comment]
Ich habe es jetzt getestet. Es ist... verschlimmbessert, würde ich mal sagen.

Siehe hier: https://www.beta.wordpress.rrze.fau.de/arbeitskreise/ 

Zwar bricht es im Format "kompakt" korrekt um, allerdings ist das Foto jetzt unschön an den Fuß gerutscht. Außerdem wird der HTML-Code nicht mehr angezeigt. 

![grafik](https://user-images.githubusercontent.com/8234890/81157594-6b31bc80-8f87-11ea-84a9-cec22cd117e7.png)
![grafik](https://user-images.githubusercontent.com/8234890/81157875-b77cfc80-8f87-11ea-8b8c-6fa3ea900d75.png)

**Comment by xwolfde** [comment]
Bist du sicher, dass in der Kurzbeschreibung HTML erlaubt war?

Die ist jetzt nicht gerade Kurz bei dir. :)

**Comment by cibsell** [comment]
Ja, bisher war HTML erlaubt, siehe: 

`[kontakt id="861" show="webseite, bild, raum, adresse, kurzbeschreibung"]`

![grafik](https://user-images.githubusercontent.com/8234890/81159988-d9777e80-8f89-11ea-92fc-d6ca46da9ac7.png)

**Comment by cibsell** [comment]
Ich weiß, dass die "Kurz"beschreibung nicht so kurz ist, wie ich sie gerne hätte. ;)

**Comment by xwolfde** [comment]
ok... dann muss ich das ja wieder erlauben ... kommt.

**Comment by xwolfde** [comment]
drin.
und auch das andere sollte gefixt sein.
auf beta gibt es gleich ein update
