### ISSUE TITLE
Social Media Buttons

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#287]
Gibt es die Möglichkeit Buttons für Forschungsdatenbanken einzufügen, z. B. FAU-intern CRIS bzw.:

- Researcher ID
- Scopus
- Google Scholar
- ORCID
- ResearchGate

Das würde unseren Wissenschaftlern mehr bringen als die Buttons für Youtube oder Instagram und dieser Wunsch wird öfters an mich herangetragen.

**Comment by xwolfde** [comment]
so etwas wie badgets...  finde ich charmant die idee.

**Comment by xwolfde** [comment]
Einsatzbeispiel
![grafik](https://user-images.githubusercontent.com/1070669/81187525-b3f76e80-8fa3-11ea-8f14-9d49099b007b.png)

**Comment by xwolfde** [comment]
@cassandre bevor ich hier was mache, was bereits woanders abgedeckt ist: Gibt es diese Daten (also deren Präsenzen auf den Forschungsportalen) pro Wissenschaftler bereits im CRIS?

**Comment by xwolfde** [comment]
In der nächsten Version enthalten
