### ISSUE TITLE
Sprechzeiten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#29]
Bitte Sprechzeiten nicht als Freitext, sondern optional zusätzlich parametrisiert machen mit Eingabefelder für Zeiten.
Von bis, Wochentags, etc pp.

**Comment by endv02** [comment]
Bleibt aktuell erst mal bei Textarea, wird später ausgebaut (auch zwecks UnivIS-Import nötig)

**Comment by endv02** [comment]
In UnivIS sind folgende Optionen einstellbar:
![2016-04-18 11_21_01-personeneintrag editieren](https://cloud.githubusercontent.com/assets/5851793/14819279/a680cd06-0bc1-11e6-98bd-dd91674aca4b.png)
![2016-04-18 11_21_29-mozilla firefox](https://cloud.githubusercontent.com/assets/5851793/14819281/a69a283c-0bc1-11e6-93dd-1552f1fc5ee2.png)

**Comment by endv02** [comment]
Verknüpft mit #127

**Comment by csw-** [comment]
@endv02 Können derzeit Sprechzeiten aus UnivIS eingebunden werden? Mit show="sprechzeiten" scheint dies gerade nicht zu funktionieren.

**Comment by endv02** [comment]
@csw Nein, aktuell noch nicht. Mit show="sprechzeiten" wird der Text im Feld Sprechzeiten ausgegeben. Der Import der Einträge aus UnivIS steht ganz oben auf der ToDo-Liste mit der Ausgabe der englischen Bezeichnungen.

**Comment by endv02** [comment]
Ist in Version 2.3.0 drin
