### ISSUE TITLE
Bilder im Card-Format "card-large" zu klein

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/fau-person#293]
Beim Card-Format `class="card-large"` wird ein zu kleines Bildformat verwendet: Längere Seite 300px -> kürzere Seite meist so um die 200px.
Der Ausschnitt ist aber 280px groß, entsprechend werden die Bilder hochskaliert. (Keine Ahnung, warum der Browser nicht automatisch das nächst größere aus dem srcset verwendet).

**Comment by xwolfde** [comment]
Erstmal wontfix - muss auf später verschoben werden. Problem ist hier, dass wir andere Bildformate als max. festlegen als es die flexbox gibt.
Hier müsste ggf. eine Anpassung über Media Query für große Screens dazu kommen. Das erscheint mir aber momentan alles noch etwas unklar. 
Ich würde daher lieber erstmal abwarten, ob das überhaupt tatsächlich so verwendet wird oder nicht ohnehin hier nochmal grundlegend neu gedacht werden muss.
