### ISSUE TITLE
Synchronisierung mit externen Daten

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/fau-person#3]
Nur bei Eingabe einer neuen Person oder Bearbeitung Möglichkeit geben, Daten zu synchronisieren:
- Checkbox "Daten aus UnivIS/CRIS/IdM holen?"
- Abfrage: nur nicht gefüllte Daten synchronisieren oder wenn Inhalte nicht identisch abfragen, ob mit externen Daten überschrieben werden soll
- aus UnivIS:
  Personendaten
  Einrichtung?
- aus CRIS:
  Publikationen
- aus IdM:
  kommt auf Schnittstelle an

**Comment by endv02** [comment]
UnivIS-Einbindung funktioniert ab Version 1.1.0

**Comment by xwolfde** [comment]
Rest zurückgestellt
