### ISSUE TITLE
Personenlisten über Shortcodes

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#30]
ich hätte noch gern die Möglichkeit via Shortcodes Personenlisten zu definieren.

[person list="id1,id2,..."]
 würde eine Liste der Personen mit den Ids id1, id2, usw zeigen. (In der Reihenfolge wie die Ids im Parameter angegeben sind).

Die Liste hätte ein Standardformat (das wir noch definieren müssen). Ggf, erstmal ne einfache Liste (&lt;ul&gt;), die nur den Titel der Personen angibt und auf die Personenseite verlinkt.

[person list="id1,id2,..." showattr="telefon, title, name, thumb" ]
Zeigt die Liste der Personen  zusammen mit den Feld-Attributen aus showattr. Es können dort alle möglichen Feldnamen angegeben werden.

**Comment by xwolfde** [comment]
Verknüpfung zu #60

**Comment by endv02** [comment]
Geht nicht über list, sondern über id="id1, id2, ..."
