### ISSUE TITLE
Automatischer Bild Ausschnitt von Kontaktbildern

### ISSUE THREAD

**Issue by Blubbaa** [RRZE-Webteam/fau-person#300]
Mit der neuen Version 3.0 scheinen die Kontaktbilder nicht mehr automatisch gecropped zu werden. Soweit ich das nachvollziehen konnte, sollten sie das ja nach wie vor:
```
/* Thumb for person-type; small for sidebar - Name: person-thumb */
		'default_person_thumb_width'	=> 120,
		'default_person_thumb_height'	=> 160,
		'default_person_thumb_crop'	=> true,
```

In den Einstellungen habe ich nur die Größenauswahl für `format="page"` und die Einstellung der Breite (80px) gefunden.

Die Kontaktliste wird beispielsweise mit
`[kontakt category="postdocs" sort="nachname" show="bild" hide="adresse,organisation,abteilung,ansprechpartner,border"]` erzeugt.

Habeich noch etwas vergessen / übersehen (z.B. richtige css Klasse setzen), was seit v3 neu ist?

**Comment by xwolfde** [comment]
Ja, das Problem ist, dass die bisherigen gecroppten Bilder bei der responsiblen Darstellung schlecht aussah. 
Die Thumb-Sizes wurden aus selben Grund erhöht (vorher war das Thumb nur 60px breit) und es dem Browser via CSS überlassen es entsprechend der Auflösung anzupassen.
Die Auswahlliste: 
![grafik](https://user-images.githubusercontent.com/1070669/83732293-5bb39b00-a63b-11ea-949a-3e3c2373cd8f.png)
entspricht nicht den Defaults im Code.

tl;dr. Ich schau da nochmal rein, ob man da was machen.

**Comment by Blubbaa** [comment]
Okay. Wir sehen bei uns halt das Problem, dass bei ~70 Mitarbeitern alle Nutzer ihre Kontaktbilder selbst hochladen und da natürlich ein Sammelsurium an Bild Formaten rauskommt. Wenn die Bilder nicht automatisch auf das richtige Verhältnis zugeschnitten werden, sieht die Übersichtsseite auch nach Kraut und Rüben aus.

**Comment by xwolfde** [comment]
Ich schau, dass ich schnell eine Option dazu einbau, die wie bei den Personen-Seiten wirkt, wo man ja auch zentral das Format vorbestimmen kann.
Hier müsste dann eben das cropped Format noch als overwrite rein.

Können wir zu Rückfragen/Tests uns im Mattermost absprechen?

**Comment by Blubbaa** [comment]
Ja gerne, wo finde ich denn die Server Daten?

**Comment by xwolfde** [comment]
Ok. Also, es ist so:

Hintergrund:

Das Defaultformat wurde mit der neuen Version vom winzigen 60Pixel Bild zu dem Format 120 Pixelx160 Pixel Breite erhöht.

Wenn Bilder hochgeladen werden im WordPress, wird dieses automatisch Versionen der Bilddateien in den dann aktuell durch Themes und Plugins verwendeten Formaten erstellen.
Man erkennt diese Bilder in der URL auch daran, dass diese im Dateinamen eine Ergänzung bekommen mit der AUflösung.
Also wenn das Original so heißt:   "Bild.jpg"
Dann wird von WordPress z.B. auch "Bild-60x80.jpg" angelegt, wenn ein Plugin dieses Bildformat definierte.

Wenn nun irgendwann dasselbe Bild mit einer anderen Auflösung verwendet werden soll, weil ein Plugin das Format änderte oder ein neues Plugin hinzukommt, welches neue Bildformate hat, dann existieren diese Dateien mit den Formaten natürlich nicht. Denn diese werden ja beim Upload des Bildes erzeugt.
Was tut WordPress in dem Fall?
Es springt zu dem Original zurück und wird dieses in der &lz;img src=""&gt; verwenden.

Das Originalbild ist aber dann natürlich auch nicht gecroppt, sondern in der Dimension, die es eben beim Upload hatte.


Was also jetzt tun?
Wir haben das Plugin "Regenerate Thumbnails".
Dieses kann aktiviert werden und dann unter Werkzeuge -&gt; Vorschaubilder regenerieren 
aufgerufen werden.
Dieses Plugin geht durch alle Bilddateien durch und regeneriert alle vom Originalbild abgeleiteten Bildformate. 
Bildformate, die nicht mehr gebraucht werden, können dabei gleich  gelöscht werden.




@ej64ojyw das solltest du auch wissen, falls Fragen von anderen kommen. Ggf. auch in die FAQ aufnehmen.

**Comment by xwolfde** [comment]
@Blubbaa invite sollte via Mail gekommen sein

**Comment by xwolfde** [comment]
Problem nun auch ohne Regenerate behoben für alle Browser neuerer Generation
