### ISSUE TITLE
format="sidebar" und die show= hide= attribute

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/fau-person#302]
Anscheinend funktioniert das attribut show="bild" mit format="sidebar" nicht korrekt, wenn
in den Einstellungen vorher nicht die Parameter angehakt werden.

http://go.fau.de/9o2ib

**Comment by xwolfde** [comment]
ok, default value zur ANzeige war wohl im rahmen von debugging auf false.

Wird in der nächsten Version gefixt sein.
