### ISSUE TITLE
Funktion fau_person_page funktioniert nicht mehr

### ISSUE THREAD

**Issue by matzex** [RRZE-Webteam/fau-person#303]
Hallo, 
seit den letzten großen Commits letzte Woche funktioniert die Plugin-Version aus Git bei uns leider nicht mehr. Es werden die Personeninformationen und insbesondere Bilder nicht mehr korrekt geladen. Folgenden Fehler finde ich in den Webserver Logs. Es scheint ein Problem zu geben die Funktion fau_person_page() mit der aktuellen Pluginversion zu laden. Dieselbe Wordpress-Installation läuft mit einem alten Stands dieses Plugins einwandfrei.
Leider kann ich in den Commit-Messages von letzter Woche nicht nachvollziehen was genau geändert wurde, da nahezu alle Dateien des Plugins geändert oder neu gepushed wurden.

`[proxy_fcgi:error] Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function   fau_person_page() in /var/www/web/wp-content/themes/FAU-WI2-c/single-person.php:28\nStack trace:\n#0 /var/www/web/wp-includes/template-loader.php(106): include()\n#1 /var/www/wen/wp-blog-header.php    (19): require_once('/var/www/web...')\n#2 /var/www/web/index.php(17): require('/var/www/web...')\n#3 {main}\n  thrown in /var/www/web/wp-content/themes/FAU-WI2-c/single-person.php on line 28',`

Beste Grüße
Matthias Hille

**Comment by xwolfde** [comment]
Ihr benutzt da offenbar auch eine veraltete Theme-Version bzw. einen selbst betriebenen Clon davon.

Entweder aktualisiert ihr euer Theme auch oder ihr geht halt zurück bei FAU Person auf die alte Version.
