### ISSUE TITLE
Parameteraufruf mit Attribute verallgemeinern

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#31]
Statt Parameter "showfax, showtelefon, showtitle" usw lieber einen allgemeineren Ansatz fahren:

[person .. showattr="fax, telefon, .." ]

Wobei alle möglichen Attribute, die man auch im Backend eingibt, dort zur Ausgabe angegeben werden können.

Ansosnten zusätzlich STandardsets an Ausgabeformate definieren mit "format".

[person .. format="sidebar" ]
Anzeige für die Sidebar  mit den dort wichtigsten Infos

[person .. format="namenliste" ]
Einfache Namensliste, Nur Namen mit Verlinkung auf Personenseite , (ggf. mit zusätzlichen Parameter sort="ASC|DESC|Random")

[person .. format="table"]
Personen (einzeln oder Liste) in Tabellenformat ausgebebn. Vergleichbar hier: https://www.fau.de/universitaet/leitung-und-struktur/leitung/

[person .. format="kurzinfo" ]
Anzeige der Kurzinfo einer Personen, vergleichbar hier
https://www.fau.de/universitaet/leitung-und-struktur/leitung/prof-dr-joachim-hornegger-praesident/
allerdings ohne Lebenslauf und weitere vollständige Felder. Satttdessen ein Textfeld mit einer Kurzinfo einführen und dann darstellen,

**Comment by xwolfde** [comment]
Bei der Perosnenseite (der Custom Post Type) Seite sollen in geeigneter Form alle Infos angezeigt werden. Auch hier vergleichbar mit der Seite 
https://www.fau.de/universitaet/leitung-und-struktur/leitung/prof-dr-joachim-hornegger-praesident/

Ggf. diese Seite als Shortcode auch verfügbar machen:
[person id="" format="full"]

**Comment by xwolfde** [comment]
Issue ist mit #5 verknüpft

**Comment by endv02** [comment]
Verknüpft mit #60

**Comment by endv02** [comment]
inzwischen umgesetzte Anzeigeformate:
- ohne Angabe: wichtigste Infos zur Person werden in einem Kasten angezeigt
- name: nur Name mit Prä- und Suffix, verlinkt auf Kontakt-Seite, in Fließtext
- page: vollständige Kontaktausgabe mit allen Infos (alternativ auch full)
- sidebar: siehe oben
- liste: siehe oben namensliste

Für die Darstellung table sollte noch ein zusätzliches hr zwischen den Kontakten bei der Standarddarstelltung ohne Format eingefügt werden

**Comment by endv02** [comment]
bei den Attributen wird statt showattr der Parameter show bzw. hide verwendet und die entsprechenden Feldnamen angegeben (telefon, titel, suffix, position, mail, abteilung, website, adresse, raum, bild, mehrlink, sprechzeiten)
