### ISSUE TITLE
Wunsch: Raum-Nummer bei format=sidebar

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/fau-person#313]
Wunsch: Raum-Nummer bei format=sidebar als möglichkeit bei der shortcode-einbindung. 
(In den sidebar-Einstellungen ist die Raum-Nummer zur Zeit nicht mit drin.)

Betroffenes Ticket: http://go.fau.de/9o3tk

**Comment by xwolfde** [comment]
bin dran

**Comment by xwolfde** [comment]
in der nächsten Version drin.


Zusätzlich auch: 
titel, familyName, givenName, name, suffix
