### ISSUE TITLE
Das Sortierkriterium funktioniert mit sort="name" noch nicht korrekt.

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/fau-person#317]
Das Sortierkriterium funktioniert mit sort="name" noch nicht korrekt.
Die Pseudonyme werden noch nicht richtig berücksichtigt beim sortieren nach Nachnamen mit sort="name"

Das Sortieren nach Nachnamen scheint auch nicht korrekt zu funktionieren, wenn die Kontakte als Kategorie ausgegeben werden.

![grafik](https://user-images.githubusercontent.com/58593037/84754025-0fb01100-afc0-11ea-9a0d-0a3acb72d80d.png)

**Comment by ej64ojyw** [comment]
Aus Helpdesk: ( http://go.fau.de/9qm6q ) - Das Sortieren nach Nachnamen scheint nicht korrekt zu funktionieren, wenn die Kontakte als Kategorie ausgegeben werden.

**Comment by Albager** [comment]
Das Problem ist heute morgen bei uns auch aufgefallen. Dieser bug sollte dringend behoben werden!
![image](https://user-images.githubusercontent.com/11389126/112115259-45ba9b00-8bb9-11eb-98c2-ebba8f0cfb89.png)


verwendeter Shortcode: `[kontakt category="personen" format="sidebar" show="raum" sort="name"]` (parameter "nachname" gibt es ja scheinbar nicht mehr, deshalb auf sort="name" geändert, wie hier beschrieben: https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/fau-person/#collapse_1)

**Comment by xwolfde** [comment]
Wird in der nächsten Version (heute abend) korrigiert sein.
Zur Vermeidung von Missverständnissen wird das Feld in der ANzeige im Backend umbenannt in "Sortierfeld". Ausserdem wird die korrekte Nutzung angegeben:
![grafik](https://user-images.githubusercontent.com/1070669/112614992-d8f20b80-8e19-11eb-8c51-a858598bed6a.png)

**Comment by Albager** [comment]
Die Sortierung nach Nachnamen (egal ob `sort="name"` oder `sort="nachname"` vgl. https://github.com/RRZE-Webteam/fau-person/issues/358) funktioniert aber leider immer noch nicht, **wenn die Kontakte als Kategorie ausgegeben werden**. Plugin-Version ist 3.2.0 - Oder mache ich was falsch?

**Comment by xwolfde** [comment]
Die neue Version ist auch noch nicht ausgerollt

**Comment by Albager** [comment]
Achso, Entschuldigung! Das habe ich falsch verstanden. Dann also erstmal abwarten und Kaffee trinken ☕ 😎

**Comment by xwolfde** [comment]
Gut Kaffee getrunken! 3.4.0 ist ausgerollt. ;)
