### ISSUE TITLE
Ausgabe der Position Univis-Beauftragter bei 

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/fau-person#319]
die Position „Univis-Beauftragter" wird auf Webseiten in der Kontakt-karte mit ausgegeben. 
(War anscheinend vorher nicht so)

![grafik](https://user-images.githubusercontent.com/58593037/85394912-9e3c0980-b54f-11ea-8796-be6dbe17bc80.png)
Ticket mit Bsp: http://go.fau.de/9o6-9

**Comment by xwolfde** [comment]
Ich sehe kein Fehler.
Im UnivIS ist im Textfeld mit der Tätigkeit Beides eingegeben.
http://univis.uni-erlangen.de/prg?search=persons&firstname=Jonas&name=Dovern&show=xml#osds


Wenn man das nicht will, muss man den Wert halt überschreiben und richtig eintragen (im UnivIS werden diese Tätigkeiten als Funktionen eingetragen)
