### ISSUE TITLE
Kotankte für Sidebar fehlen

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/fau-person#320]
Im Auswahldropdown Menü einer Seite für die Sidebar fehlt ein Großteil der Kontakte. Es werden ca. 20 Kontakte angezeigt, der Rest aber nicht (siehe Screenshot). Das betrifft sowohl fau.de als auch fau.eu.

![Screenshot_Kontakte](https://user-images.githubusercontent.com/53909165/85848653-ce7ee480-b7a9-11ea-9906-1248d39e3894.jpg)

**Comment by AndiWebred** [comment]
![Bild eingefügt am 2020-6-9 10-53](https://user-images.githubusercontent.com/53909165/85848838-261d5000-b7aa-11ea-8071-6d92ca6de074.png)

**Comment by xwolfde** [comment]
fixed
