### ISSUE TITLE
Benutzerdef. Univis-akad. Titel übernehmen | Bzw. Dr. phil. habil. als akad. Titel möglich machen

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/fau-person#321]
„Dr. phil. habil.“. Diesen dem Namen vorangestellten Titel gibt es in dieser Form aber weder im Auswahlmenü in UnivIS noch im Kontakt-Plugin in WordPress (vermutlich, weil er sehr selten zur Anwendung kommt). 

In UnivIS hat man jedoch die Möglichkeit – und das wurde auch getan – anstelle der vorgegebenen Werte aus der Dropdown-Liste einen benutzerdefinierten Wert einzugeben. Das funktioniert für den Personeneintrag in UnivIS auch prima, leider wird dieser Wert nicht von WordPress übernommen, obwohl im Back-End der in UnivIS eingestellte Wert korrekt angezeigt wird.

(Screenshot s. Ticket)
http://go.fau.de/9o5o0

**Comment by xwolfde** [comment]
Sollte jetzt übernommen werden, wenn man im Kontaktplugin einstellt, dass kein Titel ausgewählt wird. Dann wird der von UnivIS genommen.
