### ISSUE TITLE
UnivIS Wert lässt sich nicht überschreiben

### ISSUE THREAD

**Issue by cisfazzo** [RRZE-Webteam/fau-person#327]
Ich habe z.B. bei https://www.cme.studium.fau.de/person/heinrich-lollmann/ die Webseite mit https://lms.tf.fau.eu überschrieben, trotzdem wird im Frontend weiterhin der UnivIs Wert mit https://lms.tf.fau.de angezeigt. Cache habe ich gelöscht und Seite komplett neu geladen.

**Comment by xwolfde** [comment]
sollte im nächsten Update behoben sein
