### ISSUE TITLE
Institution/Abteilung?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#33]
Was trag ich da ein?
"RRZE" oder Abteilungsname?

GGf. aufteilen in zwei Felder?
* "Organisation (Lehrstuhl/Einrichtung)"
* Abteilung oder Arbeitsgruppe

Zukümnftig werden wir für UnivIS oder FAU.ORG-Anbindung bei der Orga auch eine Orga-ID brauchen.

**Comment by endv02** [comment]
In Version 2.0 geteilt: Organisation, Abteilung
