### ISSUE TITLE
WordPress 5.5,  jQuery Update von Methoden nötig

### ISSUE THREAD

**Issue by jbhs** [RRZE-Webteam/fau-person#331]
Die live()-Methode wurde in jQuery Version 1.7 abgeschafft und in Version 1.9 entfernt. Verwenden Sie stattdessen die on()-Methode. How to update: https://stackoverflow.com/questions/14354040/jquery-1-9-live-is-not-a-function#14354091

Fehler in diesem Plugin:
`fau-person/js/fau-person-admin.js: jQuery.fn.live() is deprecated` sollte in in on() geändert werden, bis dahin hilft:

https://de.wordpress.org/plugins/enable-jquery-migrate-helper/

**Comment by xwolfde** [comment]
Wurde im August bereits gefixt:
https://github.com/RRZE-Webteam/fau-person/commit/3fc01f3c205443e72abf7e541b23f73f76b9a635
