### ISSUE TITLE
Alternative Kontakt-Übersichtsseite wird nicht angezeigt

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/fau-person#332]
Alternative, eigene Kontakt-Übersichtsseite funktioniert nicht mehr (früher ging das, jetzt war der Haken an der entsprechenden Stelle bei den Einstellungen wieder drin, aber auch nach Entfernen wurde die Seite Arbeitsgruppe (hat den Slug person) nicht angezeigt: https://www.chemiedidaktik.phil.fau.de/
Zur Überbrückung gibt es jetzt zwei Seiten "Arbeitsgruppe" (einmal Slug person, einmal Slug arbeitsgruppe), die mit Slug arbeitsgruppe wurde im Menü verknüpft (sollte aber wieder rückgängig gemacht werden können).

**Comment by xwolfde** [comment]
Äh.. ich verstehe den Issue nicht.

Bitte nochmal für Dumme (mich).

Kann man das nicht mit Shortcode + Kategorie lösen?

**Comment by thelazt** [comment]
Ich kann diesen Fehler bestätigen: Wenn in den Plugineinstellungen unter **Erweiterte Einstellungen** die Option **Kontakt-Übersichtsseite** ("Zeige die Standard-Übersichtsseite aller Kontakte an. Bevor diese Option deaktiviert wird, muss eine eigene Seite mit der Titelform (slug) "person" direkt unterhalb der Hauptebene angelegt werden.") deaktiviert wird, wird dennoch nicht die zuvor selbst erstellte Kontaktübersichtsseite mit dem slug *person* angezeigt, sondern weiterhin automatisch das Archiv.

Ein Teilproblem dürfte der Zugriff auf die Optionen in der Datei `include/Taxonomy/Kontakt.php` sein, die Option ist bei unserer Instanz nicht über den Key 'has_archive_page' sondern `constants_has_archive_page` zugreifbar, entsprechend müsste es dann in der Funktion `set()`

```PHP
        $has_archive_page  = true;
        if (isset($this->settings->options) && isset($this->settings->options['constants_has_archive_page'])) {
            $has_archive_page = boolval($this->settings->options['constants_has_archive_page']);
        }
```
heißen.

Nach dieser Änderung (und einem Deaktivieren/Aktivieren des Plugins) wird unsere händisch erstellte Personenseite korrekt unter dem gewünschten slug dargestellt, so wie es die Beschreibung der Config-Option erwarten lässt.

**Comment by thenickless** [comment]
Seit 3.7.1 kann wahlweise keine, die automatisch generierte oder eine selbst erstelle Page als Übersichtsseite gewählt werden. Doku wird in kürze aktualisiert.

https://github.com/RRZE-Webteam/fau-person/commit/2853b22742151d5a971323d40e5f71f74a73a585
