### ISSUE TITLE
Bildformat-Einstellung wird ignoriert

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/fau-person#334]
Die Einstellung "Bildformat Kontaktseite" in den Plugin-Einstellung wird sowohl im Shortcode als auch auf der Kontaktseite ignoriert. Das Bild wird bis 430px breit.
Bsp: https://www.ees.tf.fau.de/person/prof-dr-ing-matthias-luther/

**Comment by xwolfde** [comment]
im test nicht mehr nachstellbar
