### ISSUE TITLE
Wunsch für weitere Social-Media Icons

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/fau-person#335]
Die folgenden Social-Media Icons/Buttons für die Kontaktausgabe wurden über Helpdesk von Kunden gewünscht:

- Google Scholar
- Researchgate
- ORCID

Weitere Informationen von Kundenseite sind im Helpdesk-Fall zu finden:
http://go.fau.de/9p3gj

**Comment by xwolfde** [comment]
Bereits auch in #287 angefragt.

Problem ist, dass unsere Symbolbibliothek die Icons dieser Plattformen nicht anbietet. Deswegen ist keine schnelle Lösung einschiebbar.

**Comment by xwolfde** [comment]
In der nächsten Version enthalten
