### ISSUE TITLE
Wunsch: Optionale zweite Mailadresse über UnivIS

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/fau-person#337]
Es besteht der Wunsch für eine optionale Ausgabe einer privaten E-Mail-Adresse über UnivIS. 

Für alle Details s. Helpdesk Ticket http://go.fau.de/9p5rk

**Comment by xwolfde** [comment]
Das kann man über Einrichtungs-Kontakteinträge lösen, die unpersönlich sind und denen man dann persönliche Kontakte als Ansprechpartner zuordnet.
