### ISSUE TITLE
Auswahl Standort Telefonanschluss hat keine Wirkung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#34]
Macht irgendwie keinen Unterschied aus, was ich eingebe und was dann unten passiert.

**Comment by xwolfde** [comment]
ggf auch mit #101 verknüoft

**Comment by endv02** [comment]
In Version 2.0 enthalten, jetzt kann auch nur die Durchwahl angegeben werden oder die komplette Nummer ohne Vorwahl (wie 85-27808)
