### ISSUE TITLE
Vorschlag Backend Navigation für Personen-Reiter: Weiter unten bei Formulare einfügen

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#35]
Wäre evtl etwas intuitiver als zwischen Beiträge und Seiten.

**Comment by xwolfde** [comment]
Aus der WP-Doku:

menu_position
    (integer) (optional) The position in the menu order the post type should appear. show_in_menu must be true.

        Default: null - defaults to below Comments 

        5 - below Posts
        10 - below Media
        15 - below Links
        20 - below Pages
        25 - below comments
        60 - below first separator
        65 - below Plugins
        70 - below Users
        75 - below Tools
        80 - below Settings
        100 - below second separator



Also würde sich eine Zahl > 20 ermpfehlen.

**Comment by endv02** [comment]
Ist in Version 1.0.7 direkt unterhalb von Seiten (=20), da Kommentare meist nicht genutzt werden.
