### ISSUE TITLE
Card-Ausgabe missachtet Ausrichtung

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/fau-person#352]
http://go.fau.de/9qd9y
Fall auf Helpdesk:

Fehlerhafte Ausgabe der Kontakt-Karten.
(Konnte den Fehler nicht nachstellen mit dem FAU Theme.)

Update: Fehler tritt wohl mit dem FAU Event-Theme auf. s. Helpdesk Notiz

[kontakt category="Ansprechpartner:innen" format="card" hide="socialmedia, titel“]

**Comment by xwolfde** [comment]
Liegt am Events Theme. Dort wird die Darstellung der Cards nicht richig umgesetzt und durch floats und ein margin-left verfälscht.
