### ISSUE TITLE
FAU-Vorwahl 81146- als weiteren Standard zu 85- ergänzen 

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/fau-person#353]
In der Personalabteilung (P1 und P6) gibt es Telefonanschlüsse mit der FAU-Vorwahl 81146:
https://www.verwaltung.zuv.fau.de/personalhandbuch/#collapse_0

Diese werden bisher noch nicht als offizielle FAU-Anschlüsse vom UnivIS-Plugin erkannt.

**Comment by xwolfde** [comment]
Und was bedeutet dies? Was soll erreicht werden? 
Standardgemäß soll doch eh die internationale Form ausgegeben werden...

**Comment by AndiWebred** [comment]
ganz einfach: es gibt die fau-vorwahl 85-xyz und es gibt eben auch die vorwahl 81146-xyz. die wird von der personalabteilung der zuv verwendet. ich glaube das hat was damit zu tun, dass anschlüsse ans klinikum gingen wegen corona. aber egal:

bei den telefonnummern mit 85-xyz sieht die darstellung ja so aus: +49 9131 85-26635
bei den telefonnummern mit 81146-xyz sieht die darstellung so aus: +49 9131 8114627
es fehlt also das - für den anschluss.

als ich das ticket geschrieben habe, war die darstellung der 81146-nummer wohl sehr seltsam, eben weil sie nicht als offzielle fau-vorwahl gezählt hat. zumindest kann ich das jetzt unserer e-mail-korrespondez (Ticket#2020052642002824) entnehmen.
