### ISSUE TITLE
Automatisch generierte Kontaktseiten: Mobiltelefon wird nicht angezeigt

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/fau-person#354]
Bei automatisch generierten Kontaktseiten, die sich aus UnivIS generieren, wird das Mobiltelefonfeld nicht angezeigt.
Beispiel:
https://www.verwaltung.zuv.fau.de/kontakt-personalabteilung/univisid/41961751/

**Comment by xwolfde** [comment]
im nächsten update drin
