### ISSUE TITLE
Bitte Hilfen für die Erstellung und Funktionsweise des Shortcodes für Personen ins Formular integrieren

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#36]
Die Person wird richtig angezeigt via Shortcode, allerdings wird die Fehlermeldung mitgeschickt, siehe Screenshot, was daran liegt, dass sich der Name geändert hat, aber nicht der "Slug". Wichtig hier wäre, dass ein Beispiel für Redakteure angeboten wird, wie der Shortcode zu benutzen ist. Am allerbesten wäre, wenn wir es über die ID empfehlen, daher sollte diese für das Erzeugen des Shortcodes im Formular angezeigt werden, z. B. Für den Shortcode benötigen Sie die ID der Person-Seite, der dann wie folgt aussieht: [person id="236"] oder [person slug="gebel-steffi"] Achtung: Beides ändert sich nicht, auch wenn der Titel verändert wird!!!! Slug kann allerdings manuell geändert werden. 

Hinweis. Shortcode sollte auch mit der ID funktionieren. Das wäre toll ;-) 

![bildschirmfoto 2015-04-13 um 12 59 20](https://cloud.githubusercontent.com/assets/11868989/7114422/6c695a02-e1dd-11e4-91c0-3848f4bca314.png)

**Comment by xwolfde** [comment]
Verknüpfung mit #60

**Comment by endv02** [comment]
Hilfen sind zu finden in der Kontext-Hilfelasche, im WP-Handbuch und im GitHub-Readme, ausschließlich Erwähnung der ID. Daher wird der Issue jetzt auch geschlossen.
