### ISSUE TITLE
Kommasetzung hinter Uhrzeiten 

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/fau-person#375]
http://go.fau.de/9q2ez

bei der Eingabe der Beratungszeiten ist aufgefallen, dass hinter der zweiten Uhrzeit automatisch ein Komma gesetzt wird:
 
Täglich Di, Mi, Do, 09:30 - 12:00, (siehe unten)
 
Kann man das irgendwie wegbekommen?

**Comment by xwolfde** [comment]
wird durch faudir obsolet
