### ISSUE TITLE
Bug with Git Updater Plugin

### ISSUE THREAD

**Issue by georg-schwarz** [RRZE-Webteam/fau-person#376]
I am using the [Git Updater plugin](https://git-updater.com/) to automatically update the FAU-Person plugin. The updater shows me that a new version is available - so far so good.

When I click on "update", the plugin is installed. After installation it shows the same message as before: new version available.

Any idea what the problem might be?

**Comment by xwolfde** [comment]
sorry for the long delay. The development for this plugin has stopped. we didnt saw any problemes her, but we are also not using the original github updater... Maybe the github updater mixed the update of a dev-branch with the main-branch.
