### ISSUE TITLE
Warnmeldung bei Aufruf Personenseite

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#38]
Notice: Trying to get property of non-object in /srv/www/vhosts/wordpress.webhummel.rrze.uni-erlangen.de/websource/wp-includes/post-template.php on line 264

**Comment by endv02** [comment]
Wo genau tritt das auf?

**Comment by endv02** [comment]
war bei index-Seite des posttypes, nicht bei aktuellem dev-Branch aufgetreten
