### ISSUE TITLE
Ausgabe der wöchentlichen Sprechstunde (Wording)

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/fau-person#380]
Es kam der Wunsch auf, ob man nicht auch nur die Tage ausgeben kann.

Mo, Di, Fr anstatt

Jede Woche Mo, Di, Fr da man als Nutzer davon ausgeht, dass die Tage sowieso jede Woche verfügbar sind.

Aus ( http://go.fau.de/9r1w4 )

**Comment by lukasniebler** [comment]
Wunsch von Kollegenseite zur Darstellung.
Priorität: Kann länger warten 🐌

Aus Helpdesk 🎫 http://go.fau.de/9r66a
Betrifft RRZE-Ausgabe

# Wortlaut:
zu viele Kommas und etwas größer: das täglich ist Quatsch und falsch, da weder Samstag noch Sonntag noch Montag Support angeboten wird.

![image](https://user-images.githubusercontent.com/58593037/149489520-8f906152-2174-4dc4-9d8e-a9bf6bf8b538.png)

**Comment by lukasniebler** [comment]
http://go.fau.de/9s63l

**Comment by thenickless** [comment]
"täglich ist Quatsch" ist ein Eingabefehler. Sinnvoll ist "wöchentlich" zu wählen, anstelle von "täglich".

**Comment by thenickless** [comment]
Closed, da gewünschte Ausgabe einstellbar ist.
