### ISSUE TITLE
Personeninfo (Text)

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#39]
Für eine Person sollten wir anstelle Freitextfeld folgendes haben:

* Normaler Personentext (über content normal eingebbar mit WYSIWYG-Editor; 'supports'            => array( 'title', 'thumbnail' )  wird zu 'supports'            => array( 'title','editor', 'thumbnail' ),, ) 

* Kurzbeschreibung (Für Übersichtsseiten etc): Textfeld ohne HTML aber mit Absätzen, mit wpautop() um Absätze ergänzt. Bis zu 400 Zeichen.
* Draft (Für Sidbars und Personenlisten): Textfeld ohne HTML, bis zu 160 Zeichen. Wird als ein Absatz formatiert (also Paragraph drumherum).

Übergangsweise kann der Content neu hinzu kommen, das jetzige Freifeld wird zur Kurzbeschreibung.

**Comment by endv02** [comment]
Evtl. Kurzbeschreibung in Excerpt packen.

**Comment by endv02** [comment]
Dann Freitext in Draft umwandeln.

**Comment by endv02** [comment]
WYSIWYG-Editor in Version 1.0.7 dabei, Freitext in Kurzbeschreibung umbenannt.

**Comment by endv02** [comment]
In Version 1.0.9: Excerpt als Kurzbeschreibung für Listenansichten; ehemals Freitext bzw. Kurzbeschreibung in Kurzauszug (für Sidebar-Ansicht) umbenannt

**Comment by endv02** [comment]
In Version 1.0.10 enthalten
