### ISSUE TITLE
worksFor funktioniert in Format Liste nicht

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/fau-person#391]
Wenn man versucht mit dem Shortcode

[kontakt category=mitglied sort=name format=table show="worksFor,department"
hide="url,telefon"]

die Kontakte inkl. Affiliation darzustellen, wird worksFor nicht mit ausgegeben.

🦥 http://go.fau.de/9sbjl

**Comment by m-w** [comment]
`department` auch nicht. Es kann auch sein, dass `show` insgesamt nicht funktioniert.
