### ISSUE TITLE
"Kopieren"-Link auf Inhaltsseiten für Kontakte funktioniert nicht

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/fau-person#399]
Getestet in Safari.
<img width="495" alt="Bildschirmfoto 2022-05-30 um 07 50 17" src="https://user-images.githubusercontent.com/58593037/170925513-8fdc8a89-b257-48b7-8a82-e57d9c48cac3.png">

Wenn ich auf "Kopieren" klicke wird der Shortcode bei mir nicht in der Zwischenablage abgelegt.

**Comment by thenickless** [comment]
@lukasniebler  Kannst du bitte kurz nochmal testen? Der Bug scheint behoben zu sein - auf meinen Browsern (auch Safari) funktioniert das Kopieren.

**Comment by lukasniebler** [comment]
auf https://www.wordpress.rrze.fau.de/wp-admin/post.php?post=2555&action=edit funktioniert es bei mir nicht.

Kopieren ist zwar blau und unterstrichen, aber beim klicken passiert bei mir nix.

**Comment by thenickless** [comment]
hab's jetzt auch dort getestet. Der Shortcode wird nach Klick in die Zwischenablage gespeichert. Bei dir nicht?

**Comment by lukasniebler** [comment]
Bei mir nicht in Safari

**Comment by thenickless** [comment]
Konnte den Fehler mit Safari reproduzieren. Ist RRZE-Siteimprove deaktiviert, funktioniert das Kopieren.

Hab ein Issue beim RRZE-Siteimprove angelegt: https://github.com/RRZE-Webteam/rrze-siteimprove/issues/5

**Comment by lukasniebler** [comment]
Thx
(Diese Siteimprove-Geschichte hängt vielleicht auch mit dem Consent-Banner zusammen.
Mir ist schon länger aufgefallen, dass die Konsole lauter Fehlermeldungen zu Siteimprove ausspuckt 🤔 Nur als Zusatz am Rande)

<img width="1134" alt="Bildschirmfoto 2022-09-23 um 13 36 34" src="https://user-images.githubusercontent.com/58593037/191952137-3aa0b7f3-f0f0-455c-ab5b-e29ffc812f7c.png">

**Comment by lukasniebler** [comment]
Noch als Ergänzung. Wenn nur ein Kontakt verfügbar ist / auf der Seite existiert, dann kann man die Kontakt-Id / Shortcode auch nicht über die Metabox kopieren.

**Comment by xwolfde** [comment]
wird mit FAUdir Plugin entfallen.
