### ISSUE TITLE
Zusätzliches Personenbild

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#40]
Optionales Personenbild neben Thumbnail einführen, welches man auf Personenseiten anstelle des Thumbnails verwenden kann, wenn es vorhanden ist.

**Comment by csw-** [comment]
Ich arbeite gerade daran unseren Forschungsbericht als eigenes Web-"Portal" innerhalb unseres Wiso-Auftritts umzusetzen. Für die Darstellung der Professoren spielen die Personenseiten dabei eine sehr große Rolle. 
Ein Optionales Personenbild wäre also von unserer Seite auch sehr wünschenswert - am besten begleitend mit einer 300x200-Darstellung des Bildes; damit man an das Layout der Präsidenten-Seite herankommt: [https://www.fau.de/universitaet/leitung-und-struktur/leitung/prof-dr-joachim-hornegger-praesident/](https://www.fau.de/universitaet/leitung-und-struktur/leitung/prof-dr-joachim-hornegger-praesident/ )

**Comment by xwolfde** [comment]
In der nächsten Version kann man angeben, dass auf der format="page" ein anderes Bildformat festgelegt wird
