### ISSUE TITLE
📇 Kontaktbilder in der Sidebar erscheinen unscharf

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/fau-person#400]
In der Sidebar erscheinen Kontaktbilder nicht in der optimalen Größe.

Wenn man z.B. ein Bild 600 x 800 px für eine Kontaktkarte hinterlegt, wählt der Browser gelegentlich eine Auflösung von 120 x 160 px und skaliert es auf 150 x 200 px.

Nähere Informationen im zugehörigen Helpdesk-Fall: 🎫 http://go.fau.de/9sxlh

**Comment by lukasniebler** [comment]
🎫 http://go.fau.de/9twzm (Als Erinnerung an mich selbst)

**Comment by lukasniebler** [comment]
@xwolfde Falls du irgendwann mal Zeit hast. Das Problem mit den unscharfen Bildern ist weiterhin ein Mysterium.
Mir ist auch nicht klar... Weshalb die Ansprechpartner nach Upload unscharf erscheinen.

Dateiformat und Co. wurde da in der Vergangenheit auch schon abgeklappert. Vielleicht hast du noch eine Idee. Mit @thenickless  hab ich auch schon drüber geschrieben. Allerdings wird das Problem wohl auch im neuen Plugin fortbestehen, weil es eben noch nicht klar ist, wieso die Bilder überhaupt unscharf ausgespuckt werden.

**Comment by xwolfde** [comment]
hier kein update mehr. 
Bei FAUdir dann alles frisch.
