### ISSUE TITLE
Sprechstundenauswahl - Keine Ausgabe der Tage, wenn keine Wiederholung gewählt wird.

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/fau-person#404]
Es ist schon öfters vorgekommen, dass Kunden vergessen unter Wiederholung "wöchentlich" anzukreuzen.

Vielleicht sollte man das einfach als Defaultwert setzen, dann werden die Tage auch ausgegeben, wenn kein Wert für die Wiederholung gewählt wurde.

🎫 http://go.fau.de/9s63l

**Comment by xwolfde** [comment]
wird im neuen faudir-plugin komplett neu gemacht. hier nichts mehr.
