### ISSUE TITLE
Sprechstundenbuchung (RSVP) - Ein Feld für Telefonnummern ☎️

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/fau-person#406]
Vermutlich hast du das sowieso schon auf dem Schirm.

Ein Formularfeld für Telefonnummern wurde von Kundenseite gewünscht,
damit die Buchenden angerufen werden können.

Ich füge es trotzdem mal als Issue hier ein, dann informier ich Sie im Helpdesk, wenn die erste Version mit der Funktion in ferner Zukunft veröffentlicht wird:

🎫 http://go.fau.de/9s8tn

**Comment by xwolfde** [comment]
aus faudir wird es telefonnummern und sprechzeiten geben.
hier in idesem plugin erfolgt aber nichts mehr. im neuen faudir-plugin wird das dann umgesetzt.
