### ISSUE TITLE
Archiv deaktivieren

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/fau-person#407]
Im Code wird explizit eine Archive Page für Person aktiviert. (constants_has_archive_page)

Kundenwunsch ist, keine anzuzeigen.

@xwolfde Kann ich eine Option für WebAdmins einbauen, sie zu deaktivieren oder gibt es einen Grund, warum immer eine Archive Page vorhanden sein muss? Default wäre "zeige Archive".

Ticket: https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentZoom&TicketID=1018185
Beispiel: https://www.empkins.de/person/

**Comment by xwolfde** [comment]
Dazu gab es in der Vergangenheit schon häufiger Diskussionen (siehe auch geschloseene Issues dazu).... So richtig fest ist meine Meinung dazu aber auch nicht.

Ein Test kann ja nicht schaden.

**Comment by thenickless** [comment]
Das Ticket wurde offenbar nicht geschlossen, denn das Archive kann bereits deaktiviert werden:

Checkbox "Kontakt-Übersichtsseite" auf wp-admin/options-general.php?page=fau-person&current-tab=fau-person-constants
