### ISSUE TITLE
Hinweis für die Angabe von Telefax-Nummern

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#41]
Hier könnte ähnlich wie bei der Angabe von Telefonnummern ein Hinweis enthalten sein, in welcher Form man das angeben soll. 

Hinweis für EU-weite Angabe: +49 etc...

**Comment by endv02** [comment]
Ab Version 1.0.9 enthalten

**Comment by cibsell** [comment]
Bei Telefax & Mobiltelefon ist kein Bindestrich, bei Telefonnummer wird im Hinweis ein Bindestrich gesetzt. Absicht?

Telefon 	
Bitte geben Sie uni-interne Nummern für Erlangen in der internationalen Form +49 9131 85-22222 und für Nürnberg in der internationalen Form +49 911 5302-555 an.

Telefax & Mobiltelefon
Bitte geben Sie die Nummer in der internationalen Form +49 9131 1111111 an.

**Comment by endv02** [comment]
Ja, schon Absicht. Oft sind die Telefax-Nummern auch externe Nummern, die Mobiltelefonnummern sowieso. Die Bindestriche sollen nur die Durchwahlen angeben. Evtl. kann ich den Hinweistext ja noch dahingehend anpassen, dass bei uni-internen Nummern die Version mit Bindestrich verwendet werden soll, ansonsten die internationale Form.

**Comment by endv02** [comment]
Ist in Version 1.2.2 abgeändert.
