### ISSUE TITLE
Publons Icon ist invertiert

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/fau-person#419]
https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom&TicketID=1040221

**Comment by thenickless** [comment]
Wolfgang, kannst du das bitte fixen? Ich habe es erfolglos versucht

**Comment by xwolfde** [comment]
Ja, muss aber noch warten.

Für hier, damit wir den Fall schonmal schliessen können (Kunde wurd ej ainformiert, dass es dauert):
<img width="312" alt="grafik" src="https://user-images.githubusercontent.com/1070669/208869649-14111299-5d49-4d11-bdaa-c1bd96657fca.png">


Es geht darum, dass das Publons Icon erneuert werden muss.

**Comment by xwolfde** [comment]
EIgentlich sind alle Icons nochmal zu prüfen. Das Publons Icon sieht auch inzwischen ganz anders aus als bei der letzten version wo die Icons dazu kamen. 
https://icon-sets.iconify.design/simple-icons/publons/

Wird aber noch dauern, wegen anderen Prios.

**Comment by cibsell** [comment]
Publons gibt es nicht mehr, das ist jetzt Researcher ID bzw. Web of Science. Die Maske nimmt aber z. B. nicht http://www.researcherid.com/rid/O-7967-2016 , sondern nur https://www.webofscience.com/wos/author/record/O-7967-2016 . Das Icon ist jetzt auch ein anderes, könntet ihr das bitte bei Gelegenheit korrigieren? Danke!

**Comment by xwolfde** [comment]
wird im neuen faudir-Plugin eh neu gemacht
