### ISSUE TITLE
Hinweis für die Kontaktmöglichkeit in den sozialen Medien

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#42]
Üblicherweise kommen hier die Usernamen bzw die Links zum jeweiligen User:
Normalerweise werden hier keine Mailadressen oder Websites angegeben. Eigene Websites der Person, die wichtig sein könnten, sollte man von Social Media trennen, da dies u. U. verwirrend sein kann.  

Twitter: @Name
Facebook: facebook.com/Name
Pinterest: Pinterest.com/Name
g+: +Name
Xing: www.xing.com/profile/Vorname_Name

Man könnte die o.G. Daten auch im Frontend durch Symbole der Netzwerke anzeigen. Siehe Screenshot: 
![bildschirmfoto 2015-04-13 um 15 11 17](https://cloud.githubusercontent.com/assets/11868989/7116133/63ab44d6-e1ef-11e4-8325-873e15ea4727.png)

**Comment by endv02** [comment]
Wenn dann Theme-Sache.
