### ISSUE TITLE
Name erscheint nicht in der Beitragsvorschau

### ISSUE THREAD

**Issue by hawxkeye** [RRZE-Webteam/fau-person#423]
Wird das [kontakt] Feld verwendet und nur der Name angezeigt, so fehlt dieser Text komplett in der Vorschau. Mit Vorschau ist hier der Anfangstextausschnitt gemeint, der zusammen mit dem Beitragsbild gezeigt wird. Im Beitrag selber ist der Text aus dem [kontakt] Feld aber richtig und vollständig angezeigt.

**Comment by thenickless** [comment]
Ich verstehe "Mit Vorschau ist hier der Anfangstextausschnitt gemeint, der zusammen mit dem Beitragsbild gezeigt wird." leider nicht. Bitte um Screenshot

**Comment by hawxkeye** [comment]
![Screenshot from 2022-10-17 15-21-40](https://user-images.githubusercontent.com/105441160/196701384-6f824f35-fda5-461b-8f29-8a3fb4a70311.png)
![Screenshot from 2022-10-17 15-21-25](https://user-images.githubusercontent.com/105441160/196701393-be83af2d-49e0-445b-aa48-716bdcd93ac4.png)

Ja es wurde der shortcode [kontakt id="123456789" format="name" show="" hide="suffix"] verwendet, tritt aber auch ohne hide Argument auf

**Comment by xwolfde** [comment]
Das ist eine Sache des Themes. In dem Theme (und auch bei anderen Default-Themes wird der Textauszug bei einer Blogroll aus einem Excerpt-Text gebildert, der keinerlei HTML und keine interaktiven Bestandteile und also auch keine Shortcodes anzeigt. 
Wenn kein Excerpt angegeben ist zu einem Beitrag., wird der Textauszug automatsich dem Text gebildet, wobei jegliches HTML und Shortcodes herausgefiltert werden.

Lösung daher: Im Beitrag das Excert Feld manuell ausfüllen mit dem geeigneten Text.
