### ISSUE TITLE
Ladezeit der Kontakte

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/fau-person#424]
aktuell dauert es sehr lange, bis die Liste der Kontakte geöffnet werden. z.T. öffnet sich die Liste auch gar nicht (länger als 15 Minuten).

**Comment by thenickless** [comment]
Falls die Ladezeit "nur" im eingeloggten Zustand so lange ist, ist das Problem zwar bekannt, kann aber derzeit leider nicht gelöst werden. Abhilfe wird das neue Plugin RRZE-Contact schaffen, bei dem unter anderem lediglich ein Shortcode genutzt wird, um eine Auflistung aller Einträge in Akkordeons zu ermöglichen. 

Sollte die Ladezeit aber auch für nicht-eingeloggte Besucher so lange sein, bitte ich um den Link zur betreffenden Website, um die Ursache herausfinden zu können.

**Comment by wrcg** [comment]
sorry, falsch ausgedrückt: Ich kann im Backend die Kontakte nicht bearbeiten, weil die Backend-Seite ewig braucht...

**Comment by thenickless** [comment]
Ja, das liegt daran, dass im eingeloggten Zustand der Cache umgangen wird. Ich kann mir das anschauen, brauche dazu aber den Zugriff zum Admin. Falls die Website bei uns gehostet ist, gerne über das Helpdesk mitteilen.

**Comment by thenickless** [comment]
Cache in 3.8.2 gefixt
