### ISSUE TITLE
mehrere Telefonnummern im Feld 

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/fau-person#425]
wir haben einen Kontakt, der mehrere Telefonnummern anzeigt. Diese wurden im Backend mit Komma getrennt eingetragen, im Frontend wird das Komma entfernt. Gibt es eine Möglichkeit, das schöner darzustellen?

![image](https://user-images.githubusercontent.com/9526974/198251417-55bbb4c5-bfc0-42e9-8816-470a6744fd1c.png)
![image](https://user-images.githubusercontent.com/9526974/198251453-738fab7b-bcc6-45ae-b9e1-6c62366f3e97.png)

**Comment by thenickless** [comment]
Derzeit entwickeln wir unter Hochdruck das Plugin RRZE-Contact, das FAU-Person ablösen wird.
Die genannte Anforderung, mehrere Telefonnummern bzw mehrere Adress-Blöcke (enthält Anschriften, aber auch eMail-Adressen und Telefonnummern) nutzen zu können, ist bereits dort umgesetzt: https://github.com/RRZE-Webteam/rrze-contact/issues/6

Die Eingabe von kommagetrennten Telefonnummern ist im FAU-Person nicht möglich, da die Nummern auch deshalb normiert werden, damit ein Klick möglich ist. ("tel:...")
