### ISSUE TITLE
Hilfe für Person anlegen noch nicht ausgefüllt

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#43]
Daran sollten wir denken. 

Hier könnte man auch was zu Kategorien zufügen und was das ggf bedeutet und welche Auswirkungen Kategorien haben. GGf wichtig für die automat. Erstellung von Organigrammen und natürlich für SEO.

**Comment by endv02** [comment]
Muss noch ergänzt werden.
