### ISSUE TITLE
Kontakte in der Sidebar aktualisieren nicht sofort

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/fau-person#432]
Die Ansprechpartner in der Sidebar aktualisieren sich nicht, wenn man eine Änderung im Kontakteintrag vorgenommen hat.

Nachstellen:
1. Kontakt anlegen
2. Kontakt auf z.B. Startseite als Ansprechpartner einbinden
3. Kontakt aktualisieren (z.B. Position)
4. Startseite aufrufen : Kontakt ist immer noch identisch
5. Cache löschen über linke Shift-Taste für einzelne Seite hilft nicht. Auch nicht der Cache löschen Button in der Admin-Leiste

Kunden fragen in individuellen Sprechstunden häufiger nach.

Anscheinend ähnliches Problem, nachdem eine Kontaktübersicht angelegt wurde und dem Kontakt die Kategorie entzogen wird, kann es passieren, dass der Kontakt auch stehen bleibt und nicht aus der Kontaktübersicht verschwindet (obwohl die Kontakt-Kategorie vom Kontakt entfernt wurde).

**Comment by thenickless** [comment]
Shortcode zeigt nun aktuelle Daten an, wenn ein Kontakt upgedated wurde.

Sidebar noch nicht.

-> debugge

**Comment by thenickless** [comment]
fixed. Lag an Cache. Es gibt einfach zu viele Caches :-D
