### ISSUE TITLE
Plugin gibt auch auf Uni-Netz eingeschränkte Personen aus

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/fau-person#436]
in UnivIS gesetzt:
- pub_visible

Ticket: https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom&TicketID=1076278

Lsg: CnP von https://github.com/RRZE-Webteam/rrze-univis/commit/87b2a639d2981c9d1dafadc1348ce2ac298c9d2b

**Comment by xwolfde** [comment]
Gewolltes Feature.
Es gibt Leute die sich auf ihrer Seite interne Leute darstellen wollen und diese Seite dazu unter eigenen Zugriffschutz setzten.
Bspw Webseiten die als Intranet fungieren.
