### ISSUE TITLE
in UnivIS gelöscht, wird dennoch durch Plugin angezeigt

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/fau-person#437]
Bug or feature?

Denn das könnte auch logisch sein, weil Daten im Plugin angereichert werden.
-> Testen

Falls aufwandsarm, Checkbox "in UnivIS gelöscht -> löschen"
Ansonsten: feature nur in rrze-contacts einbauen

Ticket: https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom&TicketID=1076278

**Comment by xwolfde** [comment]
Gewolltes Feature.
Es gibt Leute die sich auf ihrer Seite interne Leute darstellen wollen und diese Seite dazu unter eigenen Zugriffschutz setzten.
Bspw Webseiten die als Intranet fungieren.

**Comment by thenickless** [comment]
Alles klar. Ich antworte dem Kunden entsprechend
