### ISSUE TITLE
Publikationen

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#44]
Hier könnte für die Autoren ein Hinweis zugefügt werden für die gewollte Darstellung von Publikationen für die jew. Fakultät. Da gibt es mehrere Möglichkeiten, sollte aber einheitlich gemacht werden. Vielleicht so: Bitte machen Sie Angaben zu Publikationen nach der Form xxxxx.

**Comment by endv02** [comment]
Geht über das CRIS-Plugin

**Comment by siccegge** [comment]
Ha waere halt Perfekt wenn das FAU-person da den inhalt von dem CRIS shorttag mit ausgibt

Meine "wunschvorstellung" waere, dass sowas schon autogeneriert wird fuer alle (wissenschaftlichen) mitarbeiter:

https://lgdv.cms.rrze.uni-erlangen.de/person/franziska-kranz/

**Comment by cassandre** [comment]
Das ist derzeit leider nicht automatisiert möglich, da man die Publikationen einer Person nur mit deren CRIS-ID abfragen kann, die aber an dieser Stelle nicht vorliegt und auch nicht per Schnittstelle aus CRIS abgefragt werden kann.
Eine Lösung über eine zentrale, systemübergreifende Personen-ID ist in Planung, kann aber noch etwas dauern.

**Comment by siccegge** [comment]
Ah das wundert mich nachdem die CRIS publikationsliste ja problemlos auf ddie FAU-Person eintraege verweisen kann

**Comment by cassandre** [comment]
Naja, "problemlos" ist relativ: Es wird gesucht, ob eine Person dieses Namens (=Titel des Eintrags) im FAU-Person-Plugin angelegt ist. Wenn ja, wird diese verlinkt. Scheitert spätestens, wenn zwei Personen des selben Namens in einer Organisationseinheit beschäftigt sind. Besser geht's halt im Moment nicht.

**Comment by xwolfde** [comment]
#194

**Comment by xwolfde** [comment]
Zurückgestellt bis CRIS Plugin Neubau fertig

**Comment by xwolfde** [comment]
hier kein einbau mehr, da ein neues plugin erzeugt wird.
