### ISSUE TITLE
Inhalte der Shortcodes werden nicht aktualisiert.

### ISSUE THREAD

**Issue by frankbauer** [RRZE-Webteam/fau-person#445]
Wir verwenden auf unserer [Übersichtsseite](https://www.lgdv.tf.fau.de/staff/) den Shortcode:
`[kontakt category="wima" show="raum,bild" hide="position,abteilung,organisation,adresse" sort="nachname"]` 

Wenn wir einen (aus dem UnivIS importierten) Kontakt ändern (z.B. die Kategorie), löschen oder hinzufügen, dann wird die Liste angezeigte Liste nicht aktualisiert. Erst wenn wir den Shortcode auf der Übersichtsseite anpassen (z.B. die Reihenfolge im hide-Attribut) wird der Seiteninhalt mit den angepassten Kontakten angezeigt.

Wir haben schon versucht den Cache für die Seite (und die Kontakte zu deaktivieren), hat leider auch nichts gebracht.

**Comment by xwolfde** [comment]
Es gibt einen internen Plugineigenen Cache, der leider zu groß ist (1 Tag).

Da dieses Plugin nicht weiterentwickelt wird, sondern durch ein neues FAUdirPlugin ersetzt werden soll, werden wir das bei dem neuen Plugin besser machen.
