### ISSUE TITLE
CMB2-Library veraltet

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/fau-person#446]
`Deprecated: Optional parameter $type declared before required parameter $field_id is implicitly treated as a required parameter in wp-content/plugins/fau-person/vendor/cmb2/includes/rest-api/CMB2_REST.php on line 764`

CMB2 könnte mal ein Update vertragen, die installierte Version wirft ab PHP 8.1 den o.g. Fehler
Installiert: 2.7.0
Aktuell: 2.10.0

**Comment by xwolfde** [comment]
Wir konzentrieren uns auf das neue Plugin und entwicelt dies alte Plugin nicht wieter. Daher sollte sich das Problem dann erledigen.
