### ISSUE TITLE
Titel/Präfix erweitern

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#45]
Es gibt auch noch mehrere Titel, z. B. Master, Magister, Bachelor of Arts/Science/Law etc. pp.

**Comment by endv02** [comment]
Sollten laut Wolfgang erst mal raus bleiben bzw. händisch als Suffix eingegeben werden, können wir aber gerne nochmal besprechen.

**Comment by cibsell** [comment]
Man schreibt aber in der Regel "Herr Dipl.-Pol. Max Mustermann" und nicht "Frau Maxime Mustermann Dipl.-Pol.". Eine händische Präfix-Eingabe wäre wünschenswert.
