### ISSUE TITLE
Shortcode format page gibt Collapsibles die bestimmte Tabellen / Shortcodes enthalten nicht aus

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/fau-person#453]
Bsp.:
https://www.spaed.phil.fau.de/person/berit-breins/
https://www.spaed.phil.fau.de/lehrstuhl/team/mitarbeitende/berit-breins/

<img width="965" alt="Bildschirmfoto 2024-04-11 um 07 55 00" src="https://github.com/RRZE-Webteam/fau-person/assets/58593037/33d1a0da-f5f1-46f3-a3c4-3f272dc28155">

http://go.fau.de/9wv4j

**Comment by xwolfde** [comment]
Werden wir mit dem neuen Plugin alles neu machen. Aber das bisherige würde ich jetzt erstmal nicht weiter verfolgen wollen.
