### ISSUE TITLE
Kontakt über / Vorzimmer

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#46]
Wir brauchen bei einigen Personen Extra-Felder für den Kontakt. Nämlich dann, wenn diese Personen bspw. ein Sprechzimmer oder eine Anmedlung haben und darüber gegangen werden soll.

Diese Daten können dann alleine als Kontakt angegeben sien, wie hier:
https://www.fau.de/universitaet/leitung-und-struktur/leitung/prof-dr-joachim-hornegger-praesident/

oder zusätzlich, wie hier:
https://www.fau.de/universitaet/leitung-und-struktur/leitung/prof-dr-antje-kley/

**Comment by endv02** [comment]
Alternativ auch als Ansprechpartner zu verwenden, mit weiterem Feld Ansprechpartner UID bzw. Relay Owner ergänzen (für Funktionsmailadressen)

**Comment by endv02** [comment]
In Version 2.0 enthalten
