### ISSUE TITLE
Zwei untereinander geschriebene Shortcodes [person id=""] gibt einen Fehler aus

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#50]
Eintrag auf der Seite https://phil.cms.rrze.uni-erlangen.de/wp-admin/post.php?post=41&action=edit&message=1 

[person id="565" showlink="1" showaddress="1"]
[person id="566" showlink="1" showaddress="1"]

gibt aus: Siehe Screenshot
![bildschirmfoto 2015-04-24 um 13 44 21](https://cloud.githubusercontent.com/assets/11868989/7318058/0a318c48-ea88-11e4-896c-56e9a6265a00.png)

**Comment by endv02** [comment]
Problem liegt an der Person mit der id=566, sonst geht alles

**Comment by endv02** [comment]
Titel in id=566 enthält Umlaut -> Fehler erscheint

**Comment by endv02** [comment]
Gelöst in Version 1.0.7
