### ISSUE TITLE
MCE-Toollinks

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#54]
Bitte folgende Anweisungen die bisher im Theme ist übernehmen zur Unterstützung des MCE Editors:
<pre>
(function() {

    tinymce.PluginManager.add('faurteshortcodes', function( editor )
    {
		
editor.addMenuItem('shortcode_person', {
			text: 'Person einfügen',
			context: 'tools',
			onclick: function() {
				editor.insertContent('[person id="" showlink="0" extended="0"]');
			}
		});
		
		editor.addMenuItem('shortcode_persons', {
			text: 'Personengalerie einfügen',
			context: 'tools',
			onclick: function() {
				editor.insertContent('[persons category="" showlink="0" extended="0"]');
			}
		});
		    });
})();
</pre>

**Comment by xwolfde** [comment]
zum vergleich kann man sich das bei RRZE-Downloads abschauen

**Comment by endv02** [comment]
Ist drin ab Version 1.2.2
