### ISSUE TITLE
Innerhalb eines Shortcodes mehrere Personen verknüpfen

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#56]
Es wäre eine Überlegung, das Plugin so auszubauen, dass man innerhalb des ID-Slug mehrere IDs einbinden kann und man als Ergebnis das hat, wie wenn man die einzelnen Shortcodes aneinanderreiht/untereinander schreibt. z. B. [person id="11307,11308,11309,11310"]

**Comment by endv02** [comment]
Siehe auch #30
