### ISSUE TITLE
Komische Ausgabe bei mehr IDs

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#59]
http://test5.wordpress.webhummel.rrze.uni-erlangen.de/startseite/lehre/schuelerinnen/
Beim Einbinden mehrerer IDs macht das Ding komische Dinge mit dem Fließtext. http://test5.wordpress.webhummel.rrze.uni-erlangen.de/startseite/lehre/schuelerinnen/

Ich denke, das Format der Ausgaben müsste noch angepasst werden an die alte Ausgabe. Ist etwas zu klein. Zwischen den Einträgen (Personen, mehrere IDs) müsste ein Absatz sein. Die Aufzählungszeichen fehlen (bei einem Absatz müssten die aber nicht sein). Ebenfalls sollte ein Absatz vor und nach dem Shortcode gemacht werden.
![bildschirmfoto 2015-05-12 um 09 45 05](https://cloud.githubusercontent.com/assets/11868989/7582203/9f8f93d2-f88b-11e4-9cbb-71d87afcbb07.png)

Test ergab, dass es an mehr als 1 ID liegt.

**Comment by endv02** [comment]
Sollte jetzt besser sein
