### ISSUE TITLE
Shortcode-Parameter (Übersicht / Wunsch / Todo)

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#60]
(Wie besprochen) hier eine Übersicht, welche Arten von Shortcodes sinnvoll sein könnten:

[[kontakt id="123"]]
   zeigt Kontakt mit id="123" an; Format: Default.

[[kontakt slug="Servicetheke"]]
   zeigt Kontakt mit slug="Servicetheke" an; Format: Default.

[[kontakt id="123" format="sidebar"]]
   zeigt Infos der Kontakt Id =123 im kleinen Format der Sidebar an.

Formate:
- name
  Ausgabe des Fullnames (Fullname= "$Titel $Vorname $Nachname [, $Zusatztitel]") bei Kontakten  
  mit Verlinkung  auf Custom Post Type Seite oder definierter Kontaktseite.
- sidebar
  Ausgabe der Elemente für eine Sidebar. Beispiel: https://www.fau.de/studium/im-studium/beratungsangebote/studieren-mit-behinderung-oder-chronischer-erkrankung/
- listentry
  Einfache Ausgabe als Listenelement, wie hier:
  https://www.fau.de/universitaet/leitung-und-struktur/gremien-und-beauftragte/kommissionen/
  Titel Nachname, Vorname, Nachtitel, Telefon, E-Mail; Der Name ist verlinkt mit Custom Post Type Seite oder definierter Kontaktseite
- index (= default)
  Ausgabe wie hier: https://www.fau.de/universitaet/leitung-und-struktur/leitung/ 
  (Thumbnail, Fullname, Position, Telefon, E-Mail, Link zur Custom Post Type Seite oder definierter   Kontaktseite)
- page
  Ausgabe wie auf Custom Post Type Seiten, bzw wie hier: 
  https://www.fau.de/universitaet/leitung-und-struktur/leitung/prof-dr-joachim-hornegger-praesident/
  (im Prinzip alle Daten )
- plain
  Ausgabe nur angegebener Displayfields, die mit dem Parameter display="field1, field2, field3,..."  
  angegeben sein müssen. Ausgabe erfolgt als unordered HTML-List.
  [[kontakt ...display="field1, field2, field3,..."]]
  Zusätzlich zu dem jeweils gewählten Kontakt und dem angegebenen Format (u.U. Default) werden       hier die angegebenen Zusatzfelder angezeigt. Reihenfolge wie angegeben.
- [[kontakt ...hide="field1, field2, field3,..."]]
  Die Felder werden bei der Ausgabe weggelassen. Beispiel: [[kontakt ...hide="telefon" format="index"]]
  Würde die Indexausgabe zeigen, aber ohne Telefon.
- [[kontakt list="id1, id2, id6, id5, id4" format="index"]]
  Zeigt nacheinander die Kontakte mit den Ids  id1, id2, id6, id5, id4 (in genau der gegebenen Reihenfolge) mit der Ausgabe aus dem Format index. Per default wird dies in einer unordered HTML-Liste getan. Einzelelemente in einem Listitem. 
- [[kontakt accordion="id1, id2, id6, id5, id4" format="index"]]
  Zeigt nacheinander die Kontalte mit den Ids   id1, id2, id6, id5, id4 (in genau der gegebenen Reihenfolge) mit der Ausgabe aus dem Format index. Jeder Kontakteintrag wird von einem Accordion-Div umrandet, der als Titel denn Fullname hat.
- [[kontakt table="id1, id2, id6, id5, id4" format="index"]]
  Zeigt nacheinander die Kontakte mit den Ids  id1, id2, id6, id5, id4 (in genau der gegebenen Reihenfolge) mit der Ausgabe aus dem Format index. Per default wird dies in einer HTML-Table getan. Einzelelemente mit Table-Reihen.

Zur Abwärtskomtabilitität wird [[person]] als ALias zu [[kontakt]] definiert und [persons]] als Alias zu [[kontakt list="..."]] .

**Comment by cibsell** [comment]
show="bild" funktioniert, showbild=1 funktioniert nicht...

**Comment by xwolfde** [comment]
Weiteres Format aus Wunsch aus #109 :

format = "compactindex"

Ausgabe wie hier: https://www.fau.de/universitaet/leitung-und-struktur/leitung/
und hier https://cloud.githubusercontent.com/assets/8234890/10943850/9c5a9bc4-8316-11e5-9b3b-c6048115b7ec.png 
Allerdings ohne zweite Spalte mit Zusatzinfo.

Ausgabeattribute: Thumbnail, Fullname, Position, Telefon, E-Mail, Adresse
Der Link zur Custom Post Type Seite oder definierter Kontaktseite soll auf dem Fullname erfolgen.
