### ISSUE TITLE
Ausgabe in der Sidebar mit großen Abständen

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#61]
Füllt man einige Felder nicht aus (zb Emailadresse) dann ist der Abstand zb zur Adresse sehr groß. Ebenso ist der Abstand zwischen einzelnen Personen sehr groß. 

Hinweis: Eingebunden wurde hier via Ansprechpartner-Modul für die Sidebar im Backend einer Seite. 
![bildschirmfoto 2015-05-18 um 16 39 00](https://cloud.githubusercontent.com/assets/11868989/7683008/6c0ed342-fd7c-11e4-9f90-e7ec1a7f882c.png)

**Comment by endv02** [comment]
Wenn noch mehr optimiert werden muss, dann Theme-Sache
