### ISSUE TITLE
Vereinfachung der Suche nach den IDs zur Nutzung der Shortcodes

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#62]
Damit man nicht nach jeder ID manuell in den Kontakten aufwändig und mit Zeitverlust suchen muss, wäre es eine erhebliche Erleichterung, wenn man in der Seitenmaske zur Suche der Ids eine Metabox hat, in der man durch Eingabe des Namens (wie bei der Suche nach den internen Links) die ID bekommt. 

Problem ist, dass die Redakteure evtl den Arbeitsaufwand meiden und statt Shortcode einen internen Link zu dem Kontakt nutzen. Falls sich aber ein Name ändert, hat man manuellen Arbeitsaufwand, da sich der manuell eingegebene Titel des link nicht ändert.

**Comment by endv02** [comment]
Box ist da, evtl. Sortierung nach Nachname möglich

**Comment by endv02** [comment]
Hm... Sortierung erfolgt nach Titel des Kontaktes, da steht Vorname Nachname drin, das Feld Nachname bleibt meist leer. Könnte alternativ nach dem letzten Wort im Titelfeld sortieren lassen, das wäre aber nicht 100% zuverlässig (Doppelname etc...). Drum lassen wir das lieber so?

**Comment by endv02** [comment]
Ist in Version 1.2.4 nach obigem Prinzip (letztes Wort wird als Nachname angenommen und danach sortiert) umgesetzt.

**Comment by steffigebel** [comment]
Super, das ist ja dann auch was zum #closen bei natfak von heute von cibsell :-)

Von meinem iPhone gesendet

Am 05.08.2015 um 17:05 schrieb endv02 <notifications@github.com<mailto:notifications@github.com>>:


Ist in Version 1.2.4 nach obigem Prinzip (letztes Wort wird als Nachname angenommen und danach sortiert) umgesetzt.
