### ISSUE TITLE
Idee: Anbindung an FAU-Karten für Wegbeschreibung/Routenplaner

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#63]
ZU jeder Adresse kann ein "Weg zu uns" via fau-karten angebunden werden bzw. könnte per dafault im kontaktformular angeboten werden.

Adresseingabe und automatische Koordinatensuche via FAU-Karte. Ein Zusatz-Feld in der Ausgabe der Vollansicht einer Person kann heißen: Ihr Weg zu xy. 

Zusätzlich dazu könnte das ebenso für Nicht-Personen angeboten werden (fast wichtiger) 

Zusätzlich zu FAU-Karten könnte nicht die Karte, sondern ein Feld: Anfahrtsbeschreibung eingeblendet werden (Shortcode: fau-route=URL oder ID).

**Comment by endv02** [comment]
Wird evtl. mit Umstrukturierung mit eingebaut, evtl. auch erst später, evtl. gar nicht

**Comment by uliried** [comment]
Man kann im Beschreibungsfeld manuell den Shortcode für FAU-Karte einsetzen. Damit hat man dann einen schönen Kartenausschnitt (z.B. [faukarte url="term/<Name>/address/<Adresse>" width="100%" height="150px" zoom="18"]) wenn man den Kontakt direkt aufruft. 

Wenn man allerdings den Kontakt per Shortcode woanders einfügt, dann wird der Shortcode, der im Kontakt hinterlegt wird, nicht interpretiert sonder direkt ausgegeben. Kann man vielleicht hier ansetzen?

**Comment by endv02** [comment]
siehe auch #130

**Comment by xwolfde** [comment]
Standorte mit Kartenanbindung versehen, die man dann nutzen kann.

**Comment by xwolfde** [comment]
#269

**Comment by xwolfde** [comment]
durch neues Plugin obsolet
