### ISSUE TITLE
Ausgabe des Shortcodes im Contentbereich

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#64]
Wäre es möglich, den SHortcode so auszugeben, dass - falls KEIN Bild oder MEHR-Link eingestellt ist - der Zeilenumbruch aufgehoben wird? So wird sehr viel Platz verschenkt und der Rahmen um die Ansprechpartnerbox erscheint sehr leer und weiss. 

![bildschirmfoto 2015-05-28 um 14 51 20](https://cloud.githubusercontent.com/assets/11868989/7860417/09cd1c64-0549-11e5-8ed5-be5fe168b5f5.png)

**Comment by endv02** [comment]
Muss ins Theme, da Optik
