### ISSUE TITLE
Verschachtelung von Kontakten sowie Wertübergabe

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#66]
Es wäre für Einrichtungen wünschenswert, wenn in diese die zugehörigen Ansprechpartner verknüpft werden könnten. 

Beispiel: Studien Service Center mit wert=1 oder 0 für Adressübernahme eines ausgewählten Kontaktes (wählbar, von welchem) und Zuordnung des Kontaktes als "Ansprechpartner".

Gut wäre auch die Anzeigbarkeit via Parameter der Sprechzeiten sowie Vereinheitlichung der Sprechzeiteinträge.

**Comment by endv02** [comment]
Ansprechpartner funktioniert ab Version 2.0, Sprechzeiten siehe auch #29
