### ISSUE TITLE
Websiteeintrag im Feld "Website" ohne Titel

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#67]
Meines Erachtens fehlt hier ein Feld für den Linktitel, denn das sieht nicht schön aus, wenn der Permalink angezeigt wird. Es gibt auch sehr sehr sehr lange Links ;-)
![bildschirmfoto 2015-06-01 um 17 13 08](https://cloud.githubusercontent.com/assets/11868989/7916034/aa304420-0881-11e5-896c-33679c04eda2.png)

**Comment by endv02** [comment]
Ist so gewünscht, weil ja explizit die URL als Information dargestellt werden soll.
