### ISSUE TITLE
Darstellung Email-Adresse bei einem Personen-Shortcode im Content-Bereich

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#68]
Liegt wahrscheinlich an der Länge der Email-Adresse. Vielleicht wäre der Umbruch innerhalb der Email-Adresse besser als die komplette umbrechen zu lassen. ODer man lässt insgesamt die Mail-Adresse nicht anzeigen, sondern setzt einen Titel drüber wie zb der Brief als Symbol und nur den Titel des Konteaktes. 
![bildschirmfoto 2015-06-02 um 09 36 10](https://cloud.githubusercontent.com/assets/11868989/7930729/3f13518e-090b-11e5-9bd8-b1b518bd860b.png)

**Comment by endv02** [comment]
Muss im Theme gelöst werden. E-Mail-Adresse soll ausführlich da stehen zur Information.
