### ISSUE TITLE
Link auf den Kontakt

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#69]
Wünschenswert wäre die Einstellung per default, egal wo und wie man einen Kontakt einbindet, dass der Titel mit dem Link belegt ist und zu dem Kontakt auf der Einzelseite linkt. 

Klick auf Kontakt zeigt Einzelheiten an.

**Comment by endv02** [comment]
Wenn ein Mehr-Link da ist soll dieser verwendet wenden, ansonsten per default der Link zur Personen-Detail-Seite. Standardmäßig soll der Name und das Bild verlinkt werden, außer es wird beim Shortcode showlink=1 verwendet.

**Comment by endv02** [comment]
Soll wie oben angedacht beibehalten werden, externe weiterführende Links sollen nicht zu den Kontakten gepackt werden sondern in den normalen Beitragstext.

**Comment by endv02** [comment]
Ist in Version 1.1.2 mit drin
