### ISSUE TITLE
Optischer Mangel

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/fau-person#7]
...die eine komische Einrückung werden wir doch sicher noch korrigieren, sieht kaputt aus?:
![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6367494/0fa7d696-bcd4-11e4-83b4-4dc81f4cbb7d.PNG)
CSS?

**Comment by endv02** [comment]
Ist ein css-Problem: im base.css muss bei person-info-address das padding weg. 
Der css-Eintrag person-info-address fliegt beim Einsatz des Plugins raus und wird durch 
person-info-street, 
person-info-city und 
person-info-country
ersetzt (vorher Adresse in Textarea-Feld, jetzt aufgeteilt).

**Comment by xwolfde** [comment]
Ja, da kümmere ich mich drum, das es auch bei FAU-Theme gut ausschaut. Mach erstmal das Plugin fertig, das ist ja unabhängig von dem Theme. Nur am besten gleich auch schema.org berücksichtigen und klassen so setzen wie vorher.

**Comment by xwolfde** [comment]
fixed
