### ISSUE TITLE
Neuer Parameter "abteílung"

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#70]
Es wäre wünschenswert, wenn zusätzlich der Parameter Abteilung eingeführt werden kann. Sowohl für die Ansichten in der Sidebar als auch im Contentbereich. ZU überlegen ist es, den Wert als Default =1 zu setzen, da in der Sidebar die Kontakte per Dropdown ausgewählt werden und nicht via Shortcode. Wenn der Wert nicht gewünscht ist, kann man das Feld ja auch einfach freilassen. 

Mit dem Shortcode soll der Wert dann, falls nicht gewünscht, auf =0 gesetzt werden können (Für den Contentbereich). Abteilung=wichtig, vor allem für die Nicht-Personen-Einträge, also Institutionen.

**Comment by endv02** [comment]
Ist drin ab Verison 1.1
