### ISSUE TITLE
Fau-Person Reihenfolge

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#71]
Es muss in der Sidebar möglich sein, die Reihenfolge bei der Personenauswahl aus der Dropdown-Box zu bestimmen. Bisher wird nach Alphabet des VORnamens geordnet.

**Comment by endv02** [comment]
Hinfällig, kann mit Shortcodes gelöst werden und betrifft eigentlich nur die Darstellung im Uni-Theme
