### ISSUE TITLE
Reihenfolge 

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#73]
Gibt es eine Möglichkeit im Content-Bereich (also nicht in der Sidebar) die Reihenfolge der Darstellung zu ändern? Speziell ist folgendes nicht optimal...

- Die Adresse (Straße, Ort, Raum) sollte unter dem Lehrstuhl stehen
- Die Raumnummer sollte unterhalb der Straße stehen
- Die Adresse sollte ebenfalls passend zum anderen Text eingerückt werden
- Es wäre schön, wenn die Adresse ebenfalls so ein hübsches Icon bekäme
- Bei der Raumnummer sollte per default der Text "Raum" dabei stehen.
- Kann die Angabe "Deutschland" mit einem Komma hinter dem Ort stehen?

Insgesamt wäre es optisch besser, wenn der Block "Telefon bis URL" nach dem Block "Straße bis Raum" stehen würde. Siehe hier:

![screenshot-person](https://cloud.githubusercontent.com/assets/8234890/8184603/9c6421e4-143f-11e5-92f8-7949636952eb.png)

**Comment by endv02** [comment]
Die aktuelle Darstellung entspricht der auf der FAU-Homepage. Das Problem ist, dass jeder vielleicht andere Präferenzen für die Reihenfolge hat. Daher versuchen wir, irgendwann einzubinden, dass man die Reihenfolge selbst auswählen kann. Wird aber noch ein Weilchen dauern...

**Comment by xwolfde** [comment]
Wie gestern schon in Randgesprächen gesagt, hab ich da ein schlechtes Gefühl wenn wir hier zu viel Flexibilität erlauben.
Ich möchte aber betonen: Das die Anfrage und der Wunsch berechtigt und richtig ist, sehe ich auch!

Zwei Dinge machen mir Magendrücken:
Durch die Flexibilität erhöhen wir gleichzeitig die Komplexität des Plugins für Anwender. Es gibt dann noch weitere Optionen, die gerade die Menge der unbedarften Anwender einfach dadurch dass sie da sind überfordern.... Jetzt schon ist das Plugin durch die große zahl an Optionen und Parametern nicht mehr so einfach.


Dann das Thema der Usability/Wiedererkennung. Wie kommt es denn an, wenn bei fau.de, phil.fau.de und med.fau.de in der Sidebar die Kontaktinfos einheitlich einen festen Satz an Angaben haben, dann aber bei nat.fau.de einige davon plötzlich weg und andere da sind oder gar die reihenfolge auch ganz anders ist.

Jeder hat irgendwie recht, der sagt: ich möchte nur diese Infos zeigen und in dieser Reihenfolge. Aber wenn es nun jeder anders macht, ist das nicht mehr einheitlich.

By the way: Diese Diskussion sprengt etwas den Rahmen des Issues. Sollten wir das lieber via Mailverteiler führen? ich würde in dieser Frage dann auch gern die Meinung von Karsten ( @wrkb  )
hören.

**Comment by wrkb** [comment]
Meine bescheidene Meinung (die Kolleginnen kommentieren ggf. separat):
Ist tatsächlich schwierig, da völlige Freiheit bei der Reihenfolge den Nutzer irritieren kann. Wir haben uns bei der Darstellung an echten Visitenkarten orientiert - bei denen käme niemand auf die Idee, alles durcheinander zu würfeln, wenn es professionell ausssehen soll. Im Web ist es m.E. genauso - es ist ja nicht so, dass man scrollen muss, um die Information zu finden - das Auge kann einfach hinspringen...

(Wir selbst haben auch ein paar Visitenkartenfelder anders ausgefüllt, als vorgesehen, aber das eher aus der Not heraus - mit der Umstellung aufs person-Plugin ist das hoffentlich Geschichte.)

Allerdings kenne ich die Anforderungen an anderen Einrichtungen nicht oder weiß nicht, wer diese stellt und warum und wie fachkundig. Optisch ansprechender ist m.E. subjektiv und es wäre wirklich interessant, warum das einen Bruch mit dem Corporate Design verursachen muss.

**Comment by cibsell** [comment]
Ich weiß nicht, wie Ihre "echten" Visitenkarten aussehen, aber auf unseren, die wir über die Pressestelle machen ließen, steht die Adresse vor (also über) Telefonnummer und Email... ?

**Comment by FlorianFiller** [comment]
Kann ich nur bestätigen - links "Web", rechts "Print":
![vcard_hp](https://cloud.githubusercontent.com/assets/12810141/11804102/40bd58e6-a301-11e5-9681-0683c97a43e7.png)

**Comment by xwolfde** [comment]
Wie sollen wir es denn jetzt machen? 

1. Streng: Fest eine Reihenfolge UND anzugebene Daten vorgeben 
2. Größte Freiheit: Freiheit sowohl in der Reihenfolge als auch in den Anzeigedaten
3. Strenge Reihenfolge, flexible Daten: Fest in Reihenfolge aber selbst wählöbar, welche Daten gezeigt werden
4. Flexible Reihenfolge, strenge Daten: Selbst änderbare Reihenfolge, aber feste Anzeigedaten

Egal was wir tun, jeder Vorschlag hat Nachteile.
Wenn wir fast fest setzen (egal ob Daten oder Reihenfolge), wird es jemand geben, der es anders haben will. Wenn wir alles flexibel lassen, dann kann es überall unterschiedlich sein und die Einheitlichkeit geht verloren.

**Comment by wrkb** [comment]
Meine Antwort von gestern ist weg... wie auch immer, nochmal:

Völlig korrekt, es ist genau umgekehrt - schönes Eigentor meinerseits ;)
Dass wir das damals für fau.de getauscht haben, liegt wohl daran, dass die meisten Leute auf FAU-Seiten Kontakt via Telefon/Mail suchen, das mag anderswo anders sein. Es wäre aber sicher kein Problem, hier fau.de/eu dem Visitenkartenstandard anzupassen, das macht kaum einen Unterschied.

Ansonsten - jenseits technischer Einschränkungen beim Relaunch - haben wir bewusst die Karten schlank gehalten, Motto; weniger ist mehr. Man kann sie freilich optisch aufpeppen, aber was hier möglich ist, weiß v.a. das RRZE (Einrückungen), was sinnvoll ist (noch mehr Icons), sollte man sich einfach anschauen.

Wenig sinnvoll finde ich nach wie vor, die Anordnung einzelner völlig flexibel zu machen - ich gebe hier Wolfgangs Bedenken Recht. Lieber einen guten gemeinsamen Nenner für alle - zur Not gibt es doch Standards für alles, DIN, ISO, Visitenkarten...

**Comment by wrkb** [comment]
@xwolfde 

1. - man muss ja nicht alles ausfüllen?
Wem das nicht reicht --> Freitext oder Limits akzeptieren. Man kann es nicht jedem Recht machen.

**Comment by xwolfde** [comment]
Ja, wenn Felder leer sind, ist das gleichbedeutend, wenn sie nicht angezeigt werden. Aber das wäre eigentlioch keine Lösung für den Wunsch, daß z.B. die URL auf der Sidebar nicht erscheint, aber dann im Profil dann doch. Denn das ginge dann gerade nicht.

**Comment by xwolfde** [comment]
@AstridSemm Bitte auch die Diskussion verfolgen, da das Ergebnis wichtig für die Doku sein wird.

**Comment by FlorianFiller** [comment]
"Wie sollen wir es denn jetzt machen?

 1. Streng: Fest eine Reihenfolge UND anzugebene Daten vorgeben
 2. Größte Freiheit: Freiheit sowohl in der Reihenfolge als auch in den Anzeigedaten
 3. Strenge Reihenfolge, flexible Daten: Fest in Reihenfolge aber selbst wählöbar, welche Daten gezeigt werden
 4. Flexible Reihenfolge, strenge Daten: Selbst änderbare Reihenfolge, aber feste Anzeigedaten
"
Ich würde für Variante 3 plädieren - dann aber in der Reihenfolge der oben abgebildten Print-Visitenkarte. Damit müsste m.E. genug "Einheitlichkeit" in der Optik erhalten bleiben.

**Comment by cibsell** [comment]
Ich stimme Herrn Filler zu.

**Comment by AstridSemm** [comment]
Formatierung von Adressen allgemein: Man kann sich da an die DIN 5008 anlehnen (siehe: https://de.wikipedia.org/wiki/DIN_5008 ), die aber eigentlich für Gedrucktes gedacht ist. Eine wirkliche Gestaltungsnorm für Internetangebote gibt es hier wohl nicht, es sind ja auch zwei vollkommen verschiedene Medien. 

Wer im Web unterwegs ist, wird wohl am ehesten Telefonnummern und Mailadressen benötigen (Fax eher nicht, das würde ich weglassen). Beim Print ist das etwas anderes, da kann man damit rechnen, dass die Leute vielleicht doch einen Brief schreiben, eventuell sogar ein Fax schicken oder persönlich hinkommen wollen. Insofern ist ein Reihenfolgenunterschied an der Stelle durchaus nicht störend.

Fazit: Wir können unsere eigene, uniweite Norm entwickeln (die dann aber bitteschön beispielsweise auch für UnivIS gelten sollte) oder wir können denen, die da Webangebote haben, Gestaltungsfreiheit lassen. 

Ich bin für letzteres, denn der Wiedererkennungswert liegt im allgemeinen Design; will heißen: Hauptsächlich die Homepage mit der Bühne, die generelle Seitenaufteilung. Das ist das, was in meinen Augen die CI ausmacht. Ich kann mir wenige Usecases vorstellen, in denen Menschen direkt nacheinander die FAU-Seiten und dann die einzelnen Fakultätsseiten besuchen. Insofern werden Reihenfolgen, in denen Kontaktangaben zu finden sind, kaum ins Gewicht fallen. Da ist das Standardtemplate in meinen Augen der härtere Bruch, weil die Leute da wirklich nach der Navi suchen müssen.

Dass das ein Stück Komplexität mit sich bringt, ist nur logisch. Nichtsdestoweniger: Sobald der User das Prinzip der Shortcodes und des "show" und "hide" einmal begriffen hat, sollte er damit klarkommen. 

Meiner Ansicht nach ist es also eher wichtig, dass wir uns auf einen brauchbaren Default einigen, der den Bedürfnissen über den Shortcode angepasst werden kann.

Ein Häuschen als Icon für die Hausanschrift und die entsprechende Einrückung halte ich persönlich für sehr sinnvoll und eine gute Anregung.

**Comment by wrkb** [comment]
Bin für 3., auch nach Astrids Anmerkungen. Fax muss einblendbar bleiben, mindestens in der ZUV gibt es Stellen, die offiziell per FAX erreichbar sein müssen.

**Comment by AstridSemm** [comment]
Ich habe ja auch nicht gesagt, dass das Fax nicht einblendbar sein sollte; nur, dass man es üblicherweise weglassen kann (deswegen hätte ich's gern möglichst flexibel).

**Comment by xwolfde** [comment]
Also Mehrheit für 3?

Ergänzende Dinge/Fragen:

* Auf der Visitenkarte fehlt das Foto. Wo soll das stehen in der Reihenfolge? Vor oder nach dem Namen?
* Auf der Visitenkarte ist eine URL angegeben. Angenommen die URL ist identisch mit der aktellen Website, macht es eigentlich keinen SInn diese zu zeigen. Z.B. beio Herrn Filler steht phil.fau.de . Wenn nun die Visitenkarte auf der Domain phil.fau.de angezeigt wird, ist man ja schon auf der Domain. Also nutzt die Info einen doch nichts, oder?

**Comment by cibsell** [comment]
Das Foto steht im Content-Bereich doch links neben dem Namen? 

Die URL sollte natürlich bleiben. Ich habe insbesondere bei Visitenkarten oft Verlinkungen auf die Arbeitskreis-Seite à la www.chemie.fau.de/guldi . 

Thematisch würde die URL weiterhin direkt unterhalb der Email-Adresse passen.

**Comment by wrkb** [comment]
Bei der URL sollte natürlich nur eine spezifische Seite zur Person/zum Arbeitsbereich eingegeben werden. Was genau meinst du mit der Domain, Wolfgang? Geht es um den Adressteil und dessen Anzeige?

**Comment by xwolfde** [comment]
@cibsell geht nur um die Sidebar, nicht um den Contentbereich. Im Contentbereich kann man alles ändern.
In der Sidebar haben wir bei langen URLs auch das Problem, dass wir dort nicht eindeutig und browserunabhängig umbrechen können.

**Comment by xwolfde** [comment]
@wrkb Siehe halt oben das Beispiel von Herrn Filler.
Er hat in seiner Visitenkarte nunmal phil.fau.de .
Macht es Sinn diese URL auf phil.fau.de zu verlinken wenn die Visitenkarte auf phil.fau.de angezeigt wird?

**Comment by wrkb** [comment]
...er linkt auf eine Unterseite - /qm - das wäre doch okay?

**Comment by endv02** [comment]
So, da schalte ich mich auch mal mit ein, damit ich dann auch weiß, WAS ich jetzt WIE anpassen muss...
- Über den Contentbereich sollten wir durchaus auch sprechen, da ist die Reihenfolge auch fest vorgegeben, nur weglassen und hinzufügen kann man tatsächlich beliebig.
- wenn keine URL angegeben ist, wird automatisch der Link zur Personen-Detailseite eingeblendet (und ich gehe davon aus, dass keiner im Internet hier als URL phil.fau.de angibt, sondern das Feld dann eher leer lässt)
- nachdem das mit der Anzeige in der Sidebar mittels der Auswahl des Ansprechpartners über das Widget geht und nicht über den Shortcode gehen soll, kann man hier auch nicht so einfach Feldinhalte anzeigen oder ausblenden lassen. Es wäre also gut, wenn von vorherein doch klar wäre, welche Felder angezeigt werden sollen.

**Comment by wrkb** [comment]
@endv02 
ohne der Felddiskussion vorzugreifen: Ist es grundsätzlich möglich, einen Link am Widget anzuzeigen ("Alle Details" oder "mehr"), wenn mehr Felder ausgefüllt sind, als sichtbar? Und wo könnte der hinführen (hier kenn ich das Plugin zuwenig)?

**Comment by endv02** [comment]
@wrkb Den können wir uns sparen, weil in der Personen-Detail-Seite definitiv immer alle Daten angezeigt werden, die ausgefüllt sind, und die wird automatisch vom Namen aus verlinkt und von der URL (sofern keine Arbeitsgruppen-URL oder so angegeben sind). Drum verwendet diesen mehr-Button ja auch keiner mehr auf den anderen Seiten und deshalb macht die zweispaltige Anzeige, nur zur Anzeige des mehr-Links, auch keinen Sinn mehr.

**Comment by endv02** [comment]
Ich halte hiermit nach der Diskussion folgende Reihenfolge verbindlich für die Sidebar (und für Widgets) fest (das Bild (falls vorhanden) oben drüber):
![reihenfolge_sidebar](https://cloud.githubusercontent.com/assets/5851793/12484482/ca8512f0-c05a-11e5-9fa3-c8dc80fffb34.png) 
Sollten noch weitere Social Media-Felder hinzukommen, werden diese oberhalb der Sprechzeiten eingefügt.
In einer Optionsseite kann eingestellt werden, welche Daten davon dann in der Sidebar (und den Widgets) angezeigt oder ausgeblendet werden sollen.
Wird ab der Version 2.1 implementiert sein.

**Comment by endv02** [comment]
Ist jetzt drin, kann über den Untermenüpunkt "Anzeigeoptionen" im Kontakte-Menü eingestellt werden (gilt für Widgets und für die Anzeige über Ansprechpartner in der Metabox Sidebar, die über das Theme kommt).
