### ISSUE TITLE
Anzeige "Abteilungen" wird nirgends angezeigt

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#74]
Wo wird es standardmäßig angezeigt und ist es via Shortcode ein- udn abschaltbar?

Wichtiges ENHANCEMENT für PhilFak!

@endv02 Ich bin mir nicht sicher, ob du es schon drin hast, wir sprachen auf jeden Fall schon mal drüber ;-) Bitte kurze Info an mich und evtl noch am Mittwoch mit in den Merge. Danke!

**Comment by endv02** [comment]
Ist drin ab Version 1.1
