### ISSUE TITLE
Format=Full bzw format=page bitte die Ausgabe Position/Funktion ändern

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#75]
Wohin? Unter Titel, Name, Nachname, Suffix siehe auch die anderen Darstellungsformen

![bildschirmfoto 2015-06-17 um 11 33 19](https://cloud.githubusercontent.com/assets/11868989/8203811/afecbd52-14e4-11e5-95d4-6ca231a9fe73.png)

**Comment by endv02** [comment]
Ist von FAU-Seite übernommen und wohl auch so gewünscht, soll also beibehalten werden.
