### ISSUE TITLE
Testergebnis

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/fau-person#76]
Es funktioniert lediglich die Kontaktanzeige in der Sidebar.

Ich habe auf der Seite 1253457 auf Test4 (Webhummel) Shsortcodes für den Testkontakt 1253319 angelegt. Im Contentbereich wird nur 1 Shortcode angezeigt. Alle anderen 14 nicht. Hmmm. 

Außerdem gibt es einen Konflikt mit Shariff. 

Ich denke allerdings, dass auf Test4 FAU-speziell eingestellt ist und nicht PhilFak. Das muss ich noch herausfinden.

Auf Test 5 geht es schon etwas besser, hat aber einige Macken.
http://test5.wordpress.webhummel.rrze.uni-erlangen.de/startseite/lehre/studium/lehramt/
![bildschirmfoto 2015-06-18 um 17 33 23](https://cloud.githubusercontent.com/assets/11868989/8235090/382ed294-15e0-11e5-8590-f40f6faefa67.png)
Das obige wird angezeigt, wenn ich Univis ausgeschalten haben (Plugin)

Zum Vergleich, wenn Univis an ist: (auf der Seite sind ca 15 Shortcodes drin + 3 in der Sidebar)
![bildschirmfoto 2015-06-18 um 17 35 18](https://cloud.githubusercontent.com/assets/11868989/8235134/7cbf7d28-15e0-11e5-8b88-263d9dd18a77.png)

-Die Meldung mit UnivIS ist seltsam und stört, da ich gar keine UNIVIS verwendet habe.
-Die meisten Shortcodes werden nicht angezeigt.
-Wenn angezeigt wird, dann zerschossen

Weiterer Hinweis: Die Shortcodes im Contentbereich gehen nicht. Wenn ich die Kontakte und Shortcoedes aus der Sidebar rausnehme, gibt es nur eine Fehlermeldung mit univis. Siehe Screenshot.

**Comment by endv02** [comment]
Probleme sollten jetzt behoben sein
