### ISSUE TITLE
Größe des Fotos

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#77]
Gibt es eine Standardgröße für das zu verwendende Foto? Falls ja, wie groß soll das Foto sein?

**Comment by xwolfde** [comment]
Welches genau?

Bilder werden beim Upload (eines Bildes) derzeit automatisch in 12 verschiedene weitere Bildformate gespeichert. Da braucht man sich nicht kümmern.
Wichtig ist eher, daß man versucht die Formate einzuhalten.
Wenn du Bilder in dem Format 2:3 hochlädst, gibt es keine Probleme, da dann WordPress automatisch runterskaliert.


Bilder folgender Auflösungen werden erstellt bzw. genutzt (siehe functions/constants.php ab Z33):

     /* Thumb for person-type; small for sidebar - Name: person-thumb */
    'default_person_thumb_width'    => 60,
    'default_person_thumb_height'   => 80,

     
     /* Thumb for person-type; small for content - Name: person-thumb-bigger */
    'default_person_thumb_bigger_width'    => 90,
    'default_person_thumb_bigger_height'   => 120,

     /* Thumb for person-type; small for content - Name: person-thumb-page */
    'default_person_thumb_page_width'    => 200,
    'default_person_thumb_page_height'   => 300,

**Comment by cibsell** [comment]
Wie erkläre ich das am besten... Bei den Kontakten werden die Bilder über "Beitragsbild" hochgeladen und verwendet. Ich habe nun z. B. unterschiedlich große Ausgangsbilder. Diese werden unterschiedlich groß dargestellt, wenn mehrere Kontakte untereinander stehen. Ich kann nirgends einstellen, welche Größe verwendet wird. Teilweise läuft das Bild in den Textbereich des nächsten Kontaktes hinein. 

![screenshot-bilder-kontakt](https://cloud.githubusercontent.com/assets/8234890/8283190/1940c716-18f6-11e5-8388-05f7563e8fa3.png)

**Comment by xwolfde** [comment]
hm... seltsam. das sollte nicht sein. ich muss mir das anschauen.

**Comment by xwolfde** [comment]
Wir brauchen im CSS ein Clear nach dem jeweiligen Kontakt. Hat allerdings dann auch die Folge, daß mgwl. Whitespace nach unten entsteht . Die größe des Bildes ist fest vorgegeben in der Breite und skaliert proportional nach unten.

**Comment by xwolfde** [comment]
Tritt das Problem noch auf? (Bin mir nicht sicher, ob es im Zuge der letzten Updates behoben wurde)

**Comment by cibsell** [comment]
Ja, soweit ich das gesehen habe, tritt das Problem noch auf.

**Comment by xwolfde** [comment]
Mir kommt das Screenshot oben spanisch vor. Das Plugin und das Theme haben mEn doch garnicht die Darstellung, dass das Foto in der LIste rechtsbündig auftaucht.
Bitte gebe mal die URL an, damit ich mir das genauer ansehen kann.

**Comment by cibsell** [comment]
Schau mal bitte hier: https://www.chemie.nat.fau.de/testseite/ 

Da ist auch ein merkwürdiger Fehler: die Forschungsschwerpunkte, die ganz unten stehen, sollten eigentlich noch zum ersten Kontakt (Prof. Bachmann) gehören. Beim dritten Kontakt (Geschäftsstelle) fehlt der Titel.

Der Shortcode lautet:

`[kontakt id="4847, 4919, 8151, 3702, 4925" format="full"]`

**Comment by steffigebel** [comment]
Der Shortcode mit der Ausgabe Format=full ist nicht für Listen gedacht, also mehr als eine id. Daher geht’s hier um eine falsche Nutzung und nicht um einen Bug. Alle auf einmal für mehrere Personen anzeigen lassen ist auch nicht unbedingt zu Gunsten der Leser und der Usability.



--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: cibsell <notifications@github.com>
Antworten an: RRZE-Webteam/fau-person <reply@reply.github.com>
Datum: Dienstag, 30. August 2016 um 08:29
An: RRZE-Webteam/fau-person <fau-person@noreply.github.com>
Betreff: Re: [RRZE-Webteam/fau-person] Größe des Fotos (#77)


Schau mal bitte hier: https://www.chemie.nat.fau.de/testseite/

Da ist auch ein merkwürdiger Fehler: die Forschungsschwerpunkte, die ganz unten stehen, sollten eigentlich noch zum ersten Kontakt (Prof. Bachmann) gehören. Beim dritten Kontakt (Geschäftsstelle) fehlt der Titel.

Der Shortcode lautet:

[kontakt id="4847, 4919, 8151, 3702, 4925" format="full"]

**Comment by cibsell** [comment]
Können Sie mir bitte mitteilen, wo das nachzulesen ist?

**Comment by steffigebel** [comment]
Eigentlich nirgends. Auf der Einstiegsseite des Plugins im Git steht das: page: vollständige Ausgabe des ganzen Kontaktes wie bei der Kontakt-Einzelseite, die Parameter show und hide haben hierauf keinen Einfluss
sidebar: Ausgabe wie bei der Anzeige in der Sidebar im Theme
liste: Ausgabe der Namen mit Listenpunkten, unten drunter Kurzbeschreibung
Beispiel: [kontakt id="42, 44, 56" format="name"]

Das hat mir vorhin Wolfgang erklärt, dass die Nutzung so nicht befürwortet wird. Format=full oder page: hier liegt der Fokus eben auf die Darstellung eines Kontaktes auf einer Einzelseite. Vielleicht kann man die Shortcodes ja einzeln und untereinander mal testen.

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: cibsell <notifications@github.com>
Antworten an: RRZE-Webteam/fau-person <reply@reply.github.com>
Datum: Mittwoch, 31. August 2016 um 13:23
An: RRZE-Webteam/fau-person <fau-person@noreply.github.com>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de>, Comment <comment@noreply.github.com>
Betreff: Re: [RRZE-Webteam/fau-person] Größe des Fotos (#77)


Können Sie mir bitte mitteilen, wo das nachzulesen ist?

**Comment by xwolfde** [comment]
Es gibt auch nirgends ein Text der sagt: Nutze die Shortcodes doch einfach mal so, wo es keinen Sinn macht.
Ich sehe kein Bedarf darin, zu dokumentieren, was man nicht tun soll.
Wir werden auch nicht dokumentieren, dass eine öffentliche Webseite öffentlich lesbar ist.

Wir haben allerdings eine Dokumentation, in der steht, wozu man was verwenden soll. Da steht nirgends ein Beispiel, darüber, dass man eine Liste mit einem Attribut format=page oder format=full ausstattet.
