### ISSUE TITLE
Undefined variable: contactselect

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/fau-person#79]
Fehlermeldung bei Neuinstallation:
Notice: Undefined variable: contactselect in /proj/websource/docs/RRZEWeb/www.test.rrze.uni-erlangen.de-2175/websource/wp-content/plugins/fau-person-master/fau-person.php on line 169

**Comment by endv02** [comment]
War nur, wenn noch kein Kontakt angelegt war - behoben in Version 1.1.1
