### ISSUE TITLE
Anzeige der Vorwahl bei UnivIS-Importen?

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-person#83]
Gibt es hier schon Überlegungen wie die zusätzl. Anzeige der Vorwahl am geschicktesten zu lösen wäre?  (Vorrausgesetzt die Einblendung der Vorwahl ist überhaupt gewünscht, wovon ich jetzt einmal stark ausgehen würde...)

**Comment by endv02** [comment]
Na ja, nachdem die Universität sich ja über mehrere Standorte mit mindestens zwei unterschiedlichen Vorwahlen erstreckt, müssen eigentlich auch in UnivIS zwingend die Vorwahlen eingepflegt werden. Also liegt das Problem hier bei der richtigen Dateneingabe in UnivIS und nicht beim Plugin, sorry.

**Comment by endv02** [comment]
Nebenbei bemerkt habe ich gerade mal die UnivIS-Einträge der Recht- und Wirtschaftswissenschaftlichen Fakultät angesehen (z.B. http://univis.uni-erlangen.de/form?__s=2&dsc=anew/tel&dir=rw/ogrw/rwfade&anonymous=1&ref=tel&sem=2015s&__e=618), da gibt es eine ganze Reihen von Einträgen, bei denen nur "App." mit der Durchwahl angegeben ist. Hier kann man sich also anhand der Länge der Durchwahlnummer durchraten, ob derjenige in Nürnberg oder in Erlangen sitzt und von einem externen Telefon anruft - dies ist zumindest für Studierende ein Ding der Unmöglichkeit, und auch viele Mitarbeiter kennen die Nummer für interne Gespräche zwischen Nürnberg und Erlangen nicht...
