### ISSUE TITLE
Weiße Seite

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#84]
In Verbindung mit dem aktuellen NAT-Theme bringt fau-person (master branch) eine weiße Seite. Ich hatte mir am 22.6. einen master branch heruntergeladen, der funktioniert.

**Comment by endv02** [comment]
Da gibt es einen Konflikt mit einer älteren Version des rrze-univis-Plugins geben. Wenn dieses auf den neuesten Master aktualisiert ist, sollte es funktionieren. Danke für den Hinweis, schreibe ich gleich noch in die readme rein!

**Comment by cibsell** [comment]
Super, vielen Dank, daran lag's!
