### ISSUE TITLE
Warning bei zwei Kontakten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-person#85]
Erhalte wenn ich vom Theme her zwei Kontakte mir anzeigen lassen will bei einem
die folgende Meldung:

"Notice: Undefined variable: content in /srv/www/vhosts/wordpress.webhummel.rrze.uni-erlangen.de/websource/wp-content/plugins/fau-person/shortcodes/fau-person-shortcodes.php on line 539 "

(Mein Debugmode ist on)

**Comment by endv02** [comment]
Wie, "vom Theme her zwei Kontakte anzeigen"? In der Sidebar? Hast Du ein Beispiel?

**Comment by xwolfde** [comment]
Nehm als Kontakt einen Eintrag, der nur aus dem Titel besteht bzw.  keinen Eintrag bei Nachname hat.

**Comment by endv02** [comment]
Ok, alles klar, danke.

**Comment by endv02** [comment]
Sollte ab der neuesten dev-Branch-Version behoben sein

**Comment by endv02** [comment]
gefixt
