### ISSUE TITLE
Extrem lange Ladezeiten

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#88]
Nach dem Update des Person-Plugins laden diverse Seiten der PhilFak länger als 5 Minuten. Beispiele:

https://phil.cms.rrze.uni-erlangen.de/studium/studienangebot/bachelor/

https://phil.cms.rrze.uni-erlangen.de/studium/studienangebot/master/

https://phil.cms.rrze.uni-erlangen.de/studium/studienangebot/lehramt/lehramt-grundschule/

https://phil.cms.rrze.uni-erlangen.de/studium/studienangebot/lehramt/lehramt-mittelschule/

https://phil.cms.rrze.uni-erlangen.de/studium/studienangebot/lehramt/lehramt-realschule/

https://phil.cms.rrze.uni-erlangen.de/studium/studienangebot/lehramt/lehramt-gymnasium/

Woran kann das liegen?

**Comment by endv02** [comment]
Sollte jetzt durch Zwischenspeicherung über das zusätzliche Plugin univis-data behoben sein
