### ISSUE TITLE
Rahmen um Visitenkarte und Sidebar

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/fau-person#91]
Im Standardtemplate und der Inhaltsseite mit Navi ist der Rahmen um die Visitenkarte nach rechts so breit, dass er sich mit der Sidebar übeschneidet. Siehe:
![bildschirmfoto 2015-07-09 um 12 08 50](https://cloud.githubusercontent.com/assets/11296947/8592959/bc1f9e36-2633-11e5-98c5-42bcff61fd90.png)

und 

![bildschirmfoto 2015-07-09 um 12 09 29](https://cloud.githubusercontent.com/assets/11296947/8592967/c825a734-2633-11e5-9d71-9e202811cd4e.png)

Auf der Portalseite, wo es die Sidebar nicht gibt, ist dann auch der Rahmen um die Visitenkarte schmaler: 

![bildschirmfoto 2015-07-09 um 12 10 24](https://cloud.githubusercontent.com/assets/11296947/8592973/ddcd80d4-2633-11e5-98e3-b58835e3c0ab.png)
Hat es einen Grund, dass der Rahmen so breit ist? oder kann man ihn standardmäßig nach rechts begrenzen, so dass er sich mit der Sidebar nicht überschneidet?

**Comment by cibsell** [comment]
1. Gibt es eine Möglichkeit den Rahmen ganz zu entfernen?

**Comment by cibsell** [comment]
2. Schrift geht über Rahmen hinaus, wenn Kontakt in Sidebar untergebracht ist:

![kontakt](https://cloud.githubusercontent.com/assets/8234890/8905464/c3ee66ba-3466-11e5-9ad2-a494350f00f6.png)

**Comment by endv02** [comment]
Wenn der Kontakt über den Bereich "Ansprechpartner" in der Metabox Sidebar ausgewählt wird, und nicht als Shortcode eingebunden wird, sollte kein Rahmen erscheinen.

**Comment by cibsell** [comment]
Das wäre wünschenswert, aber ich habe noch keine Möglichkeit gesehen den Kontakt über den Bereich "Ansprechpartner" so anzugeben, dass ich Einfluss auf die angezeigten Parameter habe. 

Beispiel: alte Seite: https://www.chemie.uni-erlangen.de/dcp/department/lehrstuehle/physikalische-chemie/studium/pc-anfaengerpraktikum/ 

Neue Seite: Ich möchte die Praktikumsleitung zuerst angezeigt haben, mit dem Professor an erster Stelle. Danach den akademischen Rat. Danach neuer Titel: Praktikumsaufsicht und die Kontakte der drei Laboranten. 

Über "Ansprechpartner" werden die Kontakte alphabetisch angezeigt afaik. Oder gibt es dafür eine Sortiermöglichkeit? Auch möchte ich nicht alle Standarddaten anzeigen lassen.

**Comment by cibsell** [comment]
Hier ein Screenshot, wie die neue Seite aussehen soll:

![kontakt2](https://cloud.githubusercontent.com/assets/8234890/8905754/2797f422-3469-11e5-8ae7-c78cb6824241.png)

Es sind viel zu viele Daten bei den drei unteren Kontakten angegeben, die so nicht benötigt werden. Das bedeutet aber, dass ich sie über shortcode in die Sidebar eingeben muss, oder? Dort stört aber der Rahmen.

**Comment by endv02** [comment]
Hm.... ja, schon, modifizieren geht eigentlich nur über den Shortcode, die Sidebar-Metabox nutzt die Widget-Funktion... da müssen wir über das Theme noch eine Lösung überlegen...

**Comment by cibsell** [comment]
Der Rahmen sieht einfach nicht schön aus. Selbst wenn er nicht über die Sidebar ragen würde, ist er störend. Kann man ihn nicht (optional) weglassen? 

![kontakt3](https://cloud.githubusercontent.com/assets/8234890/8931614/daac3f54-3537-11e5-8793-be58cb51ba8a.png)

Zudem sind Zeilenumbrüche vorhanden, die so nicht sein sollten (URL, Abteilung, Position).

**Comment by endv02** [comment]
@xwolfde: Bitte um Stellungsnahme, ist ja eigentlich eine Theme-Sache...

**Comment by cibsell** [comment]
Unter https://test.nat.fau.de/studium/qualitaetsmanagement/ sieht man, dass rechts Buchstaben in der Sidebar im Rahmen um die Visitenkarte verschluckt werden.

**Comment by xwolfde** [comment]
URL geht nicht

**Comment by cibsell** [comment]
https://test.nat.fau.de/studium/qm/

**Comment by xwolfde** [comment]
;)

**Comment by xwolfde** [comment]
Parameter hier: https://github.com/RRZE-Webteam/fau-person/issues/60 

Hier müsste also das Ausgabeformat 'sidebar' wirken. Ich fürchte aber das dies noch nicht umgesetzt ist.

**Comment by cibsell** [comment]
Ja, das ist ein Shortcode, weil nicht alle Kontaktdaten angezeigt werden sollen.

**Comment by endv02** [comment]
Seit Version 2.1 kann die Ausgabe der anzuzeigenden Felder in der Sidebar bei Nutzung der Option "Ansprechpartner" im Theme beeinflusst werden (geht über den Untermenüpunkt Anzeigeoptionen bei Kontakte). Damit ist der Shortcode hinfällig. Außerdem scheint das Problem inzwischen im Theme gefixed zu sein.
