### ISSUE TITLE
Redakteur kein Zugriff auf UnivIS-ID Suche

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#96]
Meine Mitarbeiterin soll als Redakteur an der Webseite arbeiten können. 

Für den Redakteur wurde im Workflow Plugin folgende Rechte vergeben:

- Freigabe Kontakte
- Redakteurrechte: 
    Kontakte
       Kontakte bearbeiten
       Kontakte veröffentlichen
       Kontakte löschen
       Veröffentlichte Kontakte bearbeiten
       Veröffentlichte Kontakte löschen

Trotzdem hat der Redakteur keine Rechte, um nach UnivIS-IDs zu suchen. Es kommt die wenig hilfreiche Fehlermeldung "Schummeln, was?".

Als Administratorin kann meine Mitarbeiterin nach UnivIS-IDs suchen, es liegt also offensichtlich an der Rechtevergabe.

**Comment by endv02** [comment]
Das Anlegen und Bearbeiten von Kontakten funktioniert aber?

**Comment by cibsell** [comment]
Ja, das funktioniert. Nur die UnivIS-Suche geht nicht.

**Comment by endv02** [comment]
Wird behoben in Version 1.2.4 (geht heute online)
