### ISSUE TITLE
Emeritus und Dr. h.c. mult.

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#97]
Es fehlt eine Möglichkeit diverse Titel (z. B. Prof. em. Dr. Dr. h.c. mult. oder... Prof. em. Dr. techn. Dr. math. h.c. Dr. rer. nat. h.c.) oder Dr. rer. nat. einzutragen. Manchen Professoren ist es sehr wichtig alle Titel auf ihrer Seite zu nennen, daher stellt sich die Frage, wo dies im Formular berücksichtigt wird?

**Comment by xwolfde** [comment]
Es gibt mehrere Hundert Titelkombinationen, wenn alle Fachrichtungen berücksichtigt werden sollen. Diese müssten hinsichtlich der Änderungen dann auch dauerhaft gepflegt werden.
Daher haben wir uns dagegen entschieden, diesen Wunsch auf genauere Angabe zu berücksichtigen.

**Comment by endv02** [comment]
Evtl. kann hier mal als Feature ein selbst einzupflegende Liste eingebaut werden.

**Comment by cibsell** [comment]
@endv02 : Das wäre gut!

**Comment by csw-** [comment]
Zu dem gleichen Problem kam ich auch gerade bei unserer englischen Seite. Die Leute mit Diplomen fallen etwa auch alle raus.

@endv02 @xwolfde Wie wäre es, wenn der Wert aus UnivIS auch als Option in die Auswahlliste geladen würde? (Nicht dauerhaft, nur temporär während des Edit-Vorgangs)

So kann man zumindest den Präfix verwenden, wenn man die UnivIS-Verknüpfung bei einem Kontakt rausnehmen möchte ohne auf das Präfix zu verzichten. (So dürfte es vielen Admins gehen die englische Seiten bauen, da hier UnivIS meistens leider sehr schlecht gepflegt worden ist)

**Comment by xwolfde** [comment]
@endv02 Liefert UnivIS denn inzwischen endlich mal das englische XML?

**Comment by endv02** [comment]
@xwolfde Ja, tut es. Zumindest das für orgunits und orgname. Muss aber noch reinprogrammiert werden.

**Comment by xwolfde** [comment]
Leider keine englischen Titel aus UnivIS. Dort ist alles unvalidiert.
Erstmal zurückgestellt.
