### ISSUE TITLE
Position/Funktion als h2-Titel

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#98]
Wieso wird auf der Kontaktseite zweimal die Position angezeigt? Einmal als h2-Titel und einmal unter dem Namen. Kann man die h2-Überschrift nicht weglassen?

**Comment by endv02** [comment]
Optisch schaut vermutlich das Weglassen der kleinen Position besser aus (zumindest auch in anderen Themes). Auch in den Fak-Themes ist das vermulich besser, weil sonst gleich zweimal untereinander der Name steht.
Später soll das Ganze mal modifizierbar sein, siehe auch #73

**Comment by endv02** [comment]
Hab es nochmal ausgetestet, einmal ist der Name ja mit vollständigem Titel, daher fällt die h2-Überschrift ab Version 1.2.5 weg, dafür hat ist dann der Name als h2 definiert. Wirkt sich auch auf den Shortcode mit dem Parameter format="page" aus.
