### ISSUE TITLE
Reihenfolge unter Auswahl Ansprechpartner

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/fau-person#99]
Bitte alphabetisch nach Nachnamen sortieren! Wenn in dem Mini-Auswahlkasten mehr als 10 Kontakte stehen, davon noch ein paar mit den Allerweltsnamen Andreas, Julia etc., dann ist es mühsam nach Vornamen sortiert zu suchen. Sortierung nach Nachnamen spart Zeit und ist üblicher (und vermeidet gegebenfalls Frust, wenn man die genauen Vornamen nicht weiß und erst im UnivIS nachsehen muss...).

**Comment by endv02** [comment]
Das gehört an dieser Stelle zum Theme, bitte da nochmal eintragen! Hier im Plugin kommt das gleiche Problem aber auch in der Metabox "Kontaktinformationen" vor.

**Comment by endv02** [comment]
siehe auch #62 umgesetzt ab Version 1.2.4 für die Metabox
